import { convertAccounts } from '../../../converters'

describe('convertAccounts', () => {
  it.each([
    [
      {
        accounts:
          [
            {
              id: 170522760,
              customName: false,
              name: 'Счет Mastercard Unembossed',
              productName: 'Счет Mastercard Unembossed',
              number: '40817810000015511074',
              state: 'Открыт',
              stateCode: 'open',
              amount: 7302.49,
              type: 'card',
              registryAmount: 0,
              registry2Amount: 0,
              balance: 36063.61,
              currency: 'RUB',
              availableBalance: 7302.49,
              availBalanceRub: 7302.49,
              startDate: '11.05.2019',
              order: 1,
              category: 'account',
              requisites:
                {
                  bankName: 'ФИЛИАЛ "ВОЛЖСКИЙ" ПАО "СКБ-БАНК"',
                  address: 'Россия, 400066, Волгоградская обл, Волгоград г, Коммунистическая ул, д.16',
                  bic: '041856890',
                  inn: '6608003052',
                  kpp: '343503001',
                  corrAccount: '30101810800000000890'
                },
              allowInPayments: true,
              allowOutPayments: true,
              allowLoanRepayment: true,
              tariffPlanName: 'Универсальный',
              tariffPlanCode: '',
              tariffPlanLinkToRules: '',
              specType: 'EX',
              mostActive: false,
              pdfLink: '/export/account/pdf?id=170522760',
              overdraft: false,
              sbpDefault: false,
              bonusProgramState: 'enabled',
              availableBonuses: 297.36,
              accruedBonuses: 425.22,
              nextAccrualDate: '2020-09-01',
              lockedAmount: 0,
              canClose: true,
              bonusProgramGroup:
                {
                  firstCategory: '3',
                  secondCategory: '3',
                  thirdCategory: '3',
                  selectCategoryDate: '2020-07-06T13:03:43.000+0500'
                },
              petitionId: null,
              tariffPlanCanChange: false,
              cards: [170537804, 310720201]
            }
          ],
        cards:
          [
            {
              id: '4136158',
              state_description: 'Действующая',
              blocked: false,
              name: 'Mastercard Unembossed',
              customName: false,
              amount: 7302.49,
              currency: 'RUB',
              pan: '548386******6004',
              cardholderName: '',
              category: 'card',
              expDate: '2023-10-31',
              balance: 36063.61,
              availableBalance: 7302.49,
              holdAmount: 28761.12,
              primaryAccount: '40817810000015511074',
              accountId: 170522760,
              tariffLink: 'https://www.skbbank.ru/chastnym-licam/karty/icard',
              order: '1',
              primary: true,
              cardId: '4136158',
              brand: 'Mastercard Unembossed',
              storedId: 170537804,
              limits: [],
              status: '00',
              status_desc: 'Карта не блокирована',
              state: '2',
              kind: 'debit',
              loan_funds: 0,
              own_funds: 7302.49,
              used_loan_funds: 0,
              most_active: false,
              smsPhone: '79033164152',
              smsType: null,
              packageCashBack: 'forbidden',
              packageFreeCashOut: 'off',
              packageServ: false,
              paymentSystem: 'MC',
              limit_set_available: false,
              own_customer_card: true,
              holder_name: 'Иванов Иван Иванович',
              design_id: '23006',
              design_front_url: '/export/card/design?code=23006&side=front',
              design_back_url: '/export/card/design?code=23006&side=back',
              textColor: 'white',
              canUnlock: false,
              canReissue: false,
              canAddCard: false,
              contactless: true,
              smsNotify: 30,
              highCashBack: 30,
              freeWithdraw: 30,
              canViewCvv2: false,
              smsService: false,
              canIssuePlastic: false
            },
            {
              id: '4136158',
              state_description: 'Действующая',
              blocked: false,
              name: 'Mastercard Unembossed',
              customName: false,
              amount: 7302.49,
              currency: 'RUB',
              pan: '123456******7890',
              cardholderName: '',
              category: 'card',
              expDate: '2023-10-31',
              balance: 36063.61,
              availableBalance: 7302.49,
              holdAmount: 28761.12,
              primaryAccount: '40817810000015511074',
              accountId: 170522760,
              tariffLink: 'https://www.skbbank.ru/chastnym-licam/karty/icard',
              order: '1',
              primary: true,
              cardId: '4136158',
              brand: 'Mastercard Unembossed',
              storedId: 310720201,
              limits: [],
              status: '00',
              status_desc: 'Карта не блокирована',
              state: '2',
              kind: 'debit',
              loan_funds: 0,
              own_funds: 7302.49,
              used_loan_funds: 0,
              most_active: false,
              smsPhone: '79033164152',
              smsType: null,
              packageCashBack: 'forbidden',
              packageFreeCashOut: 'off',
              packageServ: false,
              paymentSystem: 'MC',
              limit_set_available: false,
              own_customer_card: true,
              holder_name: 'Иванов Иван Иванович',
              design_id: '23006',
              design_front_url: '/export/card/design?code=23006&side=front',
              design_back_url: '/export/card/design?code=23006&side=back',
              textColor: 'white',
              canUnlock: false,
              canReissue: false,
              canAddCard: false,
              contactless: true,
              smsNotify: 30,
              highCashBack: 30,
              freeWithdraw: 30,
              canViewCvv2: false,
              smsService: false,
              canIssuePlastic: false
            }
          ],
        loans: [],
        deposits: []
      },
      [
        {
          id: '40817810000015511074',
          type: 'ccard',
          title: 'Счет Mastercard Unembossed',
          instrument: 'RUB',
          balance: 7302.49,
          creditLimit: 0,
          syncIds: [
            '40817810000015511074',
            '548386******6004',
            '123456******7890'
          ],
          storedId: [170537804, 310720201]
        }
      ]
    ],
    [
      {
        accounts: [
          {
            id: 457842767,
            customName: false,
            name: 'Счет Visa Classic',
            productName: 'Счет Visa Classic',
            number: '40817810411724047117',
            state: 'Открыт',
            stateCode: 'open',
            amount: 3459.94,
            type: 'card',
            registryAmount: 0,
            registry2Amount: 0,
            balance: 3459.94,
            currency: 'RUB',
            availableBalance: 3459.94,
            availBalanceRub: 3459.94,
            startDate: '15.08.2019',
            order: 1,
            category: 'account',
            requisites: {
              bankName: 'ПАО "СКБ-БАНК"',
              address: 'Россия, 620026, Свердловская обл, Екатеринбург г, Куйбышева ул, д.75',
              bic: '046577756',
              inn: '6608003052',
              kpp: '668501001',
              corrAccount: '30101810800000000756'
            },
            allowInPayments: true,
            allowOutPayments: true,
            allowLoanRepayment: true,
            tariffPlanName: 'Коллеги',
            tariffPlanCode: '',
            tariffPlanLinkToRules: '',
            specType: 'EV',
            mostActive: true,
            pdfLink: '/export/account/pdf?id=457842767',
            overdraft: false,
            sbpDefault: true,
            bonusProgramState: 'forbidden',
            availableBonuses: 0,
            accruedBonuses: 0,
            nextAccrualDate: null,
            lockedAmount: 0,
            canClose: true,
            bonusProgramGroup: {
              firstCategory: '0',
              secondCategory: '0',
              thirdCategory: '0',
              selectCategoryDate: null
            },
            bonusProgram: [],
            petitionId: null,
            tariffPlanCanChange: false,
            cards: [457848533]
          },
          {
            id: 880815350,
            customName: false,
            name: 'Счет Visa Gold',
            productName: 'Счет Visa Gold',
            number: '40817810426224071050',
            state: 'Открыт',
            stateCode: 'open',
            amount: 15328.16,
            type: 'card',
            registryAmount: 0,
            registry2Amount: 0,
            balance: 0,
            currency: 'RUB',
            availableBalance: 15328.16,
            availBalanceRub: 15328.16,
            startDate: '04.10.2020',
            order: 2,
            category: 'account',
            requisites: {
              bankName: 'ПАО "СКБ-БАНК"',
              address: 'Россия, 190031, Санкт-Петербург г, Московский пр-кт, д.2, корп.6, пом.77Н, лит.А',
              bic: '046577756',
              inn: '6608003052',
              kpp: '668501001',
              corrAccount: '30101810800000000756'
            },
            allowInPayments: true,
            allowOutPayments: true,
            allowLoanRepayment: false,
            tariffPlanName: 'Карты с условием кредитования счета (Кредитка для покупок)',
            tariffPlanCode: '',
            tariffPlanLinkToRules: '',
            specType: 'EV',
            mostActive: false,
            pdfLink: '/export/account/pdf?id=880815350',
            overdraft: true,
            sbpDefault: false,
            bonusProgramState: 'forbidden',
            availableBonuses: 0,
            accruedBonuses: 0,
            nextAccrualDate: null,
            lockedAmount: 0,
            canClose: false,
            bonusProgramGroup: {
              firstCategory: '0',
              secondCategory: '0',
              thirdCategory: '0',
              selectCategoryDate: null
            },
            bonusProgram: [],
            petitionId: null,
            tariffPlanCanChange: false,
            cards: [730484252]
          }
        ],
        cards: [
          {
            id: '4294184',
            state_description: 'Действующая',
            blocked: false,
            name: 'Visa Classic',
            customName: false,
            amount: 3459.94,
            currency: 'RUB',
            pan: '472879******6230',
            cardholderName: 'NIKITA CHEREPANOV',
            category: 'card',
            expDate: '2024-07-31',
            balance: 3459.94,
            availableBalance: 3459.94,
            holdAmount: 0,
            primaryAccount: '40817810411724047117',
            accountId: 457842767,
            tariffLink: 'https://landings.skbbank.ru/tarifs/kollegi',
            order: '1',
            primary: true,
            cardId: '4294184',
            brand: 'Visa Classic',
            storedId: 457848533,
            limits: [],
            status: '00',
            status_desc: 'Карта не блокирована',
            state: '2',
            kind: 'debit',
            loan_funds: 0,
            own_funds: 3459.94,
            used_loan_funds: 0,
            most_active: false,
            smsPhone: '79533081003',
            smsType: 'SMS',
            packageCashBack: 'forbidden',
            packageFreeCashOut: 'forbidden',
            packageServ: false,
            paymentSystem: 'VISA',
            limit_set_available: false,
            own_customer_card: true,
            holder_name: 'Черепанов Никита Владимирович',
            design_id: '13802',
            design_front_url: '/export/card/design?code=13802&side=front',
            design_back_url: '/export/card/design?code=13802&side=back',
            textColor: 'black',
            canUnlock: false,
            canReissue: true,
            canAddCard: false,
            contactless: true,
            smsNotify: 0,
            highCashBack: 30,
            freeWithdraw: 0,
            canViewCvv2: false,
            smsService: true,
            canIssuePlastic: false,
            pinSet: true,
            rateStandardCashback: null,
            rateHighCashback: null
          },
          {
            id: '4152343',
            state_description: 'Действующая',
            blocked: false,
            name: 'Visa Gold',
            customName: false,
            amount: 15328.16,
            currency: 'RUB',
            pan: '437524******0402',
            cardholderName: '',
            category: 'card',
            expDate: '2023-10-31',
            balance: 0,
            availableBalance: 15328.16,
            holdAmount: 0,
            primaryAccount: '40817810426224071050',
            accountId: 880815350,
            tariffLink: 'https://landings.skbbank.ru/tarifs/ks_kreditka',
            order: '2',
            primary: true,
            cardId: '4152343',
            brand: 'Visa Gold',
            storedId: 730484252,
            limits: [],
            status: '00',
            status_desc: 'Карта не блокирована',
            state: '2',
            kind: 'credit',
            loan_funds: 30000,
            own_funds: 0,
            used_loan_funds: 14671.84,
            most_active: false,
            smsPhone: '79533081003',
            smsType: 'SMS',
            packageCashBack: 'forbidden',
            packageFreeCashOut: 'forbidden',
            packageServ: false,
            paymentSystem: 'VISA',
            limit_set_available: false,
            own_customer_card: true,
            holder_name: 'Черепанов Никита Владимирович',
            design_id: '13002',
            design_front_url: '/export/card/design?code=13002&side=front',
            design_back_url: '/export/card/design?code=13002&side=back',
            textColor: 'white',
            canUnlock: false,
            canReissue: false,
            canAddCard: false,
            contactless: true,
            smsNotify: 0,
            highCashBack: 30,
            freeWithdraw: 0,
            canViewCvv2: false,
            smsService: true,
            canIssuePlastic: false,
            pinSet: true,
            rateStandardCashback: null,
            rateHighCashback: null
          }
        ],
        loans: [
          {
            id: 730484164,
            bank_system_id: '16015980',
            productName: 'Кредитная карта',
            productCode: '2168',
            customName: false,
            name: 'Кредитная карта',
            amount: 0,
            currency: 'RUB',
            interestRate: 19.3,
            psk: null,
            contractDate: '11.02.2020',
            contractNumber: '38316589002',
            openDate: '11.02.2020',
            endDate: null,
            allowPaymentAmount: 14749.21,
            partialPaymentDate: null,
            planPaymentAmount: null,
            mainAccount: '45509810526216152200',
            repaymentAccount: '40817810426224071050',
            recommendedPaymentAmount: 0,
            partialPaymentAmount: null,
            prepayment: false,
            overdueDebtAmount: 0,
            overdraft: true,
            startPaymentPeriod: null,
            gracePeriodDate: null,
            creditLimit: 30000,
            availableLimit: 15328.16,
            prepaymentApplication: false,
            changeDate: false,
            ownFounds: 0,
            changeRepaymentAccount: false,
            partialPaymentMarker: true,
            reduceLimit: false,
            closeLimit: false,
            prepaymentAmount: null,
            prepaymentId: null,
            prepaymentType: null,
            loanHolder: 'ПАО "СКБ-банк"',
            paymentsDelay: false,
            paymentsDelayId: null,
            scheduleChanged: false,
            mortgage: false,
            onlineRepayment: true,
            petitionId: null,
            minLimit: 20000
          }],
        deposits: [],
        external_cards: [],
        accounts_update: '2020-12-24T22:08:57.213+05:00',
        cards_update: '2020-12-24T22:08:57.181+05:00',
        deposits_update: '2020-12-24T22:08:57.179+05:00',
        loans_update: '2020-12-24T22:08:57.180+05:00'
      },
      [
      ]
    ]
  ])('converts account with card', (apiAccounts, accounts) => {
    expect(convertAccounts(apiAccounts)).toEqual(accounts)
  })

  it.each([
    [
      {
        accounts:
          [
            {
              id: 42424242,
              customName: false,
              name: 'Счет RUB',
              productName: 'Счет RUB',
              number: '40817810900087654321',
              state: 'Открыт',
              stateCode: 'open',
              amount: 1000.00,
              type: 'current',
              registryAmount: 0,
              registry2Amount: 0,
              balance: 1000.00,
              currency: 'RUB',
              availableBalance: 1000.00,
              availBalanceRub: 1000.00,
              startDate: '08.08.2020',
              order: 99,
              category: 'account',
              requisites: {
                bankName: 'ФИЛИАЛ "МОСКОВСКИЙ" ПАО "СКБ-БАНК"',
                address: 'Россия, 109004, Москва г, Москва г, Николоямская ул, д.40/22, корп.4',
                bic: '044520000',
                inn: '',
                kpp: '775002001',
                corrAccount: '30101810045250000472'
              },
              allowInPayments: true,
              allowOutPayments: true,
              allowLoanRepayment: true,
              tariffPlanName: 'Универсальный',
              tariffPlanCode: '',
              tariffPlanLinkToRules: '',
              specType: 'EX',
              mostActive: false,
              pdfLink: '/export/account/pdf?id=42424242',
              overdraft: false,
              sbpDefault: false,
              bonusProgramState: 'forbidden',
              availableBonuses: 0,
              accruedBonuses: 0,
              nextAccrualDate: null,
              lockedAmount: 0,
              canClose: true,
              bonusProgramGroup: {
                firstCategory: '0',
                secondCategory: '0',
                thirdCategory: '0',
                selectCategoryDate: null
              },
              petitionId: 850361797
            }
          ],
        cards: [],
        loans: [],
        deposits: []
      },
      [
        {
          id: '40817810900087654321',
          type: 'checking',
          title: 'Счет RUB',
          instrument: 'RUB',
          balance: 1000.00,
          creditLimit: 0,
          syncIds: ['40817810900087654321']
        }
      ]
    ]
  ])('converts account', (apiAccounts, accounts) => {
    expect(convertAccounts(apiAccounts)).toEqual(accounts)
  })
})
