import { convertAccounts } from '../../../converters'

describe('convertAccounts', () => {
  it.each([
    [
      {
        accounts: [
          {
            id: 880815350,
            customName: false,
            name: 'Счет Visa Gold',
            productName: 'Счет Visa Gold',
            number: '40817810426224099832',
            state: 'Открыт',
            stateCode: 'open',
            amount: 15328.16,
            type: 'card',
            registryAmount: 0,
            registry2Amount: 0,
            balance: 0,
            currency: 'RUB',
            availableBalance: 15328.16,
            availBalanceRub: 15328.16,
            startDate: '04.10.2020',
            order: 2,
            category: 'account',
            requisites: {
              bankName: 'ПАО "СКБ-БАНК"',
              address: 'Россия, 190031, Санкт-Петербург г, Московский пр-кт, д.2, корп.6, пом.77Н, лит.А',
              bic: '046577756',
              inn: '6608003052',
              kpp: '668501001',
              corrAccount: '30101810800000000756'
            },
            allowInPayments: true,
            allowOutPayments: true,
            allowLoanRepayment: false,
            tariffPlanName: 'Карты с условием кредитования счета (Кредитка для покупок)',
            tariffPlanCode: '',
            tariffPlanLinkToRules: '',
            specType: 'EV',
            mostActive: false,
            pdfLink: '/export/account/pdf?id=880815350',
            overdraft: true,
            sbpDefault: false,
            bonusProgramState: 'forbidden',
            availableBonuses: 0,
            accruedBonuses: 0,
            nextAccrualDate: null,
            lockedAmount: 0,
            canClose: false,
            bonusProgramGroup: {
              firstCategory: '0',
              secondCategory: '0',
              thirdCategory: '0',
              selectCategoryDate: null
            },
            bonusProgram: [],
            petitionId: null,
            tariffPlanCanChange: false,
            cards: [730484252]
          }
        ],
        cards: [
          {
            id: '4152343',
            state_description: 'Действующая',
            blocked: false,
            name: 'Visa Gold',
            customName: false,
            amount: 15328.16,
            currency: 'RUB',
            pan: '437524******6732',
            cardholderName: '',
            category: 'card',
            expDate: '2023-10-31',
            balance: 0,
            availableBalance: 15328.16,
            holdAmount: 0,
            primaryAccount: '40817810426224099832',
            accountId: 880815350,
            tariffLink: 'https://landings.skbbank.ru/tarifs/ks_kreditka',
            order: '2',
            primary: true,
            cardId: '4152343',
            brand: 'Visa Gold',
            storedId: 730484252,
            limits: [],
            status: '00',
            status_desc: 'Карта не блокирована',
            state: '2',
            kind: 'credit',
            loan_funds: 30000,
            own_funds: 0,
            used_loan_funds: 14671.84,
            most_active: false,
            smsPhone: '79533081003',
            smsType: 'SMS',
            packageCashBack: 'forbidden',
            packageFreeCashOut: 'forbidden',
            packageServ: false,
            paymentSystem: 'VISA',
            limit_set_available: false,
            own_customer_card: true,
            holder_name: 'Николаев Николай Николаевич',
            design_id: '13002',
            design_front_url: '/export/card/design?code=13002&side=front',
            design_back_url: '/export/card/design?code=13002&side=back',
            textColor: 'white',
            canUnlock: false,
            canReissue: false,
            canAddCard: false,
            contactless: true,
            smsNotify: 0,
            highCashBack: 30,
            freeWithdraw: 0,
            canViewCvv2: false,
            smsService: true,
            canIssuePlastic: false,
            pinSet: true,
            rateStandardCashback: null,
            rateHighCashback: null
          }
        ],
        loans: [
          {
            id: 730484164,
            bank_system_id: '16015980',
            productName: 'Кредитная карта',
            productCode: '2168',
            customName: false,
            name: 'Кредитная карта',
            amount: 0,
            currency: 'RUB',
            interestRate: 19.3,
            psk: null,
            contractDate: '11.02.2020',
            contractNumber: '38316589002',
            openDate: '11.02.2020',
            endDate: null,
            allowPaymentAmount: 14749.21,
            partialPaymentDate: null,
            planPaymentAmount: null,
            mainAccount: '45509810526216152200',
            repaymentAccount: '40817810426224099832',
            recommendedPaymentAmount: 0,
            partialPaymentAmount: null,
            prepayment: false,
            overdueDebtAmount: 0,
            overdraft: true,
            startPaymentPeriod: null,
            gracePeriodDate: null,
            creditLimit: 30000,
            availableLimit: 15328.16,
            prepaymentApplication: false,
            changeDate: false,
            ownFounds: 0,
            changeRepaymentAccount: false,
            partialPaymentMarker: true,
            reduceLimit: false,
            closeLimit: false,
            prepaymentAmount: null,
            prepaymentId: null,
            prepaymentType: null,
            loanHolder: 'ПАО "СКБ-банк"',
            paymentsDelay: false,
            paymentsDelayId: null,
            scheduleChanged: false,
            mortgage: false,
            onlineRepayment: true,
            petitionId: null,
            minLimit: 20000
          }
        ],
        deposits: [],
        external_cards: [],
        accounts_update: '2020-12-24T22:08:57.213+05:00',
        cards_update: '2020-12-24T22:08:57.181+05:00',
        deposits_update: '2020-12-24T22:08:57.179+05:00',
        loans_update: '2020-12-24T22:08:57.180+05:00'
      },
      [
        {
          id: '40817810426224099832',
          instrument: 'RUB',
          syncIds: [
            '40817810426224099832',
            '437524******6732'
          ],
          title: 'Счет Visa Gold',
          type: 'ccard',
          balance: 15328.16,
          creditLimit: 30000,
          storedId: [
            730484252
          ]
        }
      ]
    ]
  ])('converts credit cards', (apiAccounts, accounts) => {
    expect(convertAccounts(apiAccounts)).toEqual(accounts)
  })
})
