import { convertAccounts } from '../../../converters'

describe('convertAccounts', () => {
  it.each([
    [
      [
        {
          id: 852256,
          acc_id: '5410418',
          type: 'Card_Visa_Electron.png',
          account20: 'KZ928560000007119689',
          card_num: '466720******8787',
          note: 'Visa Electron',
          module: '10',
          currency: 'KZT',
          holder: '',
          exp_date: '05.2022',
          psys: 'VISA',
          branch: 'Отделение №0502',
          product_code: '0.300.010',
          reissue: false,
          credit_limit: 0,
          is_with_deposit: false,
          gained: 0,
          visible: true,
          virtual: false,
          social: false,
          junior: false,
          direct_credit: false,
          card_group: 'GROUP_1',
          has_applepay: true,
          has_installment: false,
          own_balance: 0,
          card_type: 'debit',
          allow_db: 1,
          allow_cr: 1,
          main_card: 1,
          card_design: 'group_1_visa.png',
          card_color_text: 'ffffff',
          ext_conversion: true,
          bccpay: 0,
          multicard: false,
          alias: false,
          access_level: 0,
          repay_amount: 0,
          hide_balance: 0,
          debt: 0,
          limit: '0',
          blocked: '6069.15',
          balance: '-6069.15',
          card_status: 'Card Closed TEMP',
          percent: '',
          close_date: '',
          structType: 'card'
        },
        {
          id: 2852541,
          acc_id: 'I/200730/1/4787',
          type: 'Visa_Gold_Reward.png',
          account20: 'KZ138562204109314730',
          card_num: '489993******6762',
          note: 'Стипендия',
          module: '10',
          currency: 'KZT',
          holder: '',
          exp_date: '07.2025',
          psys: 'VISA',
          branch: 'Центральное отделение №0110',
          product_code: '0.300.1500.8',
          reissue: false,
          credit_limit: 200000,
          is_with_deposit: false,
          gained: 0,
          visible: true,
          virtual: false,
          social: false,
          junior: false,
          direct_credit: true,
          card_group: 'GROUP_5',
          has_applepay: true,
          has_installment: true,
          own_balance: 0,
          card_type: 'credit',
          allow_db: 1,
          allow_cr: 1,
          main_card: 1,
          card_design: 'group_5_kartakarta.png',
          card_color_text: 'ffffff',
          ext_conversion: true,
          bccpay: 0,
          multicard: false,
          alias: true,
          access_level: 2,
          repay_amount: 201576.55,
          hide_balance: 0,
          cr_int_pay: 0,
          cr_exp_pay: 0,
          l_contract: 'SOK/2020/F/S/014028',
          l_procent: 24.99,
          l_start_date: '03.11.2021',
          l_end_date: '03.05.2025',
          lastdea: '03.05.2025',
          paydate: '25.04.2022',
          l_limit: 200000,
          l_available_limit: 219.44,
          l_debt_sum: 193876.97,
          l_percent_sum: 0,
          l_over_debt: 7585.79,
          l_fine: 113.79,
          l_grace: 0,
          l_mandatory_pay: 7699.58,
          debt_status: 'expired_debt',
          limit: '200000',
          blocked: '7699.58',
          balance: '-7699.58',
          card_status: '00',
          percent: '',
          close_date: '',
          structType: 'card',
          details:
            {
              id: 2852541,
              iban: 'KZ138562204109314730',
              installment_enabled: false,
              categories_selected: 2,
              categories_chose: true,
              debt_info:
                {
                  credit_line:
                    {
                      acc_name: 'SOK/2020/F/S/014028',
                      pay_amount: 7699.58,
                      prc_amount: 0,
                      cms_amount: 0,
                      min_amount: 7699.58
                    },
                  fine_amount: 113.79,
                  over_debt_amount: 7585.79,
                  total_cms_amount: 0,
                  total_prc_amount: 0,
                  total_min_amount: 7699.58,
                  grace_amount: 191633.95,
                  total_debt_amount: 193876.97,
                  full_amount: 201576.55,
                  status: 'expired_debt'
                }
            }
        },
        {
          id: 2183258,
          acc_id: 'I/200115/1/424',
          type: 'Visa_Gold_Reward.png',
          account20: 'KZ828562204107750236',
          card_num: '489993******7448',
          note: '#картакарта',
          module: '10',
          currency: 'KZT',
          holder: '',
          exp_date: '11.2024',
          psys: 'VISA',
          branch: 'Отделение №0901 Elite',
          product_code: '0.300.1500.8',
          reissue: false,
          credit_limit: 200000,
          is_with_deposit: false,
          gained: 0,
          visible: true,
          virtual: false,
          social: false,
          junior: false,
          direct_credit: false,
          card_group: 'GROUP_5',
          has_applepay: true,
          has_installment: true,
          own_balance: 141.99,
          card_type: 'credit',
          allow_db: 1,
          allow_cr: 1,
          main_card: 1,
          card_design: 'group_5_kartakarta.png',
          card_color_text: 'ffffff',
          ext_conversion: true,
          bccpay: 0,
          multicard: false,
          alias: true,
          access_level: 0,
          repay_amount: 0,
          hide_balance: 0,
          cr_int_pay: 0,
          cr_exp_pay: 0,
          l_contract: 'AE7/2020/F/S/008997',
          l_procent: 22.99,
          l_start_date: '28.10.2021',
          l_end_date: '28.04.2025',
          lastdea: '28.04.2025',
          paydate: '25.03.2022',
          l_limit: 200000,
          l_available_limit: 200000,
          l_debt_sum: 0,
          l_percent_sum: 0,
          l_over_debt: 0,
          l_fine: 0,
          l_grace: 1,
          l_mandatory_pay: 0,
          debt_status: 'no_debt',
          limit: '200000',
          blocked: '0',
          balance: '200141.99',
          card_status: '00',
          percent: '',
          close_date: '',
          structType: 'card',
          details: {
            id: 2183258,
            iban: 'KZ828562204107750236',
            installment_enabled: false,
            categories_selected: 2,
            categories_chose: true,
            debt_info:
              {
                credit_line:
                  {
                    acc_name: 'AE7/2020/F/S/008997',
                    pay_amount: 0,
                    prc_amount: 0,
                    cms_amount: 0,
                    min_amount: 0
                  },
                fine_amount: 0,
                over_debt_amount: 0,
                total_cms_amount: 0,
                total_prc_amount: 0,
                total_min_amount: 0,
                grace_amount: 0,
                total_debt_amount: 0,
                full_amount: 0,
                status: 'no_debt'
              }
          }
        },
        {
          id: 5087169,
          type: 'CURRENT',
          account20: 'KZ078562204115680851',
          product: 'Текущий счет физического лица',
          open_date: '25.02.2022',
          accPTPSum: 0,
          visible: true,
          direct_credit: false,
          allow_db: 1,
          allow_cr: 1,
          can_close: true,
          is_epv: false,
          is_zhv: false,
          note: 'Текущий счет',
          acc_status: 'Рабочий',
          module: '01',
          currency: 'KZT',
          access_level: 0,
          for_credit: 'FALSE',
          balance: '0',
          blocked: '0',
          structType: 'deposit'
        },
        {
          id: 2306499,
          type: 'CURRENT',
          account20: 'KZ828562204108091676',
          product: 'Договора РКО Social',
          open_date: '09.04.2020',
          accPTPSum: 0,
          visible: true,
          direct_credit: false,
          allow_db: 1,
          allow_cr: 0,
          can_close: true,
          is_epv: false,
          is_zhv: false,
          note: 'Договора РКО Social',
          acc_status: 'Рабочий',
          module: '01',
          currency: 'KZT',
          access_level: 0,
          for_credit: 'FALSE',
          balance: '0',
          blocked: '0',
          structType: 'current'
        },
        {
          id: 4364018,
          type: 'CURRENT',
          account20: 'KZ428562204313629479',
          product: 'Текущий счет физического лица',
          open_date: '21.09.2021',
          accPTPSum: 0,
          visible: true,
          direct_credit: false,
          allow_db: 1,
          allow_cr: 1,
          can_close: true,
          is_epv: false,
          is_zhv: false,
          note: 'Счёт RUB Visa #RentaCar',
          acc_status: 'Рабочий',
          module: '01',
          currency: 'RUB',
          access_level: 2,
          for_credit: 'FALSE',
          is_cardacc: true,
          balance: '0',
          blocked: '0',
          structType: 'current'
        }
      ],
      [
        {
          product: {
            productId: '2852541',
            productType: 'ccard'
          },
          accounts: [
            {
              available: -7699.58,
              creditLimit: 200000,
              gracePeriodEndDate: new Date('2022-04-24T18:00:00.000Z'),
              id: '2852541',
              instrument: 'KZT',
              savings: false,
              syncIds: ['KZ138562204109314730', '489993******6762'],
              title: 'Стипендия',
              totalAmountDue: 191633.95,
              type: 'ccard'
            }
          ]
        },
        {
          product: {
            productId: '4364018',
            productType: 'checking'
          },
          accounts: [
            {
              balance: 0,
              id: '4364018',
              instrument: 'RUB',
              savings: false,
              syncIds: ['KZ428562204313629479'],
              title: 'Счёт RUB Visa #RentaCar',
              type: 'checking'
            }
          ]
        }
      ]
    ]
  ])('converts skipped accounts', (apiAccounts, accounts) => {
    expect(convertAccounts(apiAccounts)).toEqual(accounts)
  })
})
