image: node:20

variables:
  SHARED_CACHE_ROOT: /opt/plugins-cache
  WEBPACK_CACHE_DIR: .webpack-cache

before_script:
  - scripts/setupDependenciesCache.sh

stages:
  - test
  - build

test:
  stage: test
  script:
    - yarn test

build:
  stage: build
  script:
    - /opt/ZenPlugins/bin/build
  only:
    - master
    - develop
    - /^[^/]+_beta$/
