import { parseTransactions } from '../../../api'

describe('parseTransactions', () => {
  it.each([
    [
      require('./holds.html'),
      [
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '23.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '2.73',
          operationCurrency: 'BYN',
          operationSum: '2.73',
          place: 'STOLOVAYA N1>GRODNOBY/5812',
          status: 'operResultProcess',
          time: '11:24:31'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '22.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '5.00',
          operationCurrency: 'BYN',
          operationSum: '5.00',
          place: 'PARIKMAHERSK."IMIDZH GRUPP"/7230',
          status: 'operResultOk',
          time: '13:23:41'
        },
        {
          accountID: 'accountId',
          comment: 'Снятие наличных',
          date: '21.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '60.00',
          operationCurrency: 'BYN',
          operationSum: '60.00',
          place: 'BELARUSBANK BR.400/4003 ATM/6011',
          status: 'operResultOk',
          time: '18:46:06'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '21.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '36.48',
          operationCurrency: 'BYN',
          operationSum: '36.48',
          place: 'SHOP "DE FACTO" BPSB/5651',
          status: 'operResultOk',
          time: '16:48:17'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '21.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '17.98',
          operationCurrency: 'BYN',
          operationSum: '17.98',
          place: 'SHOP N16 "TVOE" BPSB/5651',
          status: 'operResultOk',
          time: '15:41:47'
        },
        {
          accountID: 'accountId',
          comment: 'Плата за предоставление мини-выписки',
          date: '20.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '0.35',
          operationCurrency: 'BYN',
          operationSum: '0.35',
          place: 'OPLATA USLUG/4900',
          status: 'operResultOk',
          time: '16:54:07'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '20.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '0.50',
          operationCurrency: 'BYN',
          operationSum: '0.50',
          place: 'SMS BANKING / MTS/4814',
          status: 'operResultOk',
          time: '16:47:16'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '20.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '3.19',
          operationCurrency: 'BYN',
          operationSum: '3.19',
          place: 'STOLOVAYA N1/5812',
          status: 'operResultOk',
          time: '11:41:44'
        },
        {
          accountID: 'accountId',
          comment: 'Безналичное зачисление на счет',
          date: '20.03.2020',
          debitFlag: '+',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '100.00',
          operationCurrency: 'BYN',
          operationSum: '100.00',
          status: 'operResultOk',
          time: '00:00:00'
        },
        {
          accountID: 'accountId',
          comment: 'Безналичное списание со счета',
          date: '20.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '3.00',
          operationCurrency: 'BYN',
          operationSum: '3.00',
          place: '/',
          status: 'operResultOk',
          time: '00:00:00'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '19.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '2.52',
          operationCurrency: 'BYN',
          operationSum: '2.52',
          place: 'STOLOVAYA N1/5812',
          status: 'operResultOk',
          time: '11:47:36'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '18.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '3.39',
          operationCurrency: 'BYN',
          operationSum: '3.39',
          place: 'STOLOVAYA N1/5812',
          status: 'operResultOk',
          time: '11:45:20'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '17.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '3.08',
          operationCurrency: 'BYN',
          operationSum: '3.08',
          place: 'STOLOVAYA N1/5812',
          status: 'operResultOk',
          time: '11:45:55'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '17.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '4.67',
          operationCurrency: 'USD',
          operationSum: '1.92',
          place: 'GOOGLE*LEONYDOV/5816',
          status: 'operResultOk',
          time: '00:00:00'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '16.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '3.18',
          operationCurrency: 'BYN',
          operationSum: '3.18',
          place: 'STOLOVAYA N1/5812',
          status: 'operResultOk',
          time: '11:46:08'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '15.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '7.82',
          operationCurrency: 'BYN',
          operationSum: '7.82',
          place: 'GRODNENSKIY TC "KORONA"/5411',
          status: 'operResultOk',
          time: '20:52:40'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '14.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '6.85',
          operationCurrency: 'BYN',
          operationSum: '6.85',
          place: 'GRODNENSKIY TC "KORONA"/5411',
          status: 'operResultOk',
          time: '12:11:02'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '14.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '19.90',
          operationCurrency: 'BYN',
          operationSum: '19.90',
          place: 'SHOP "5 ELEMENT"/5732',
          status: 'operResultOk',
          time: '11:51:24'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '13.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '2.40',
          operationCurrency: 'BYN',
          operationSum: '2.40',
          place: 'KIOSK N400173 BAPB/5993',
          status: 'operResultOk',
          time: '12:08:05'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '13.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '4.06',
          operationCurrency: 'BYN',
          operationSum: '4.06',
          place: 'STOLOVAYA N1/5812',
          status: 'operResultOk',
          time: '11:41:44'
        },
        {
          accountID: 'accountId',
          comment: 'Безналичное зачисление на счет',
          date: '13.03.2020',
          debitFlag: '+',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '80.48',
          operationCurrency: 'BYN',
          operationSum: '80.48',
          place: 'УЗ "ГРОДНЕНСКИЙ ГОСУДАРСТВЕННЫЙ ПОЛИТЕХН',
          status: 'operResultOk',
          time: '00:00:00'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '12.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '2.54',
          operationCurrency: 'BYN',
          operationSum: '2.54',
          place: 'STOLOVAYA N1/5812',
          status: 'operResultOk',
          time: '11:48:01'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '11.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '6.06',
          operationCurrency: 'BYN',
          operationSum: '6.06',
          place: 'SHOP "EVROOPT" MVV/5411',
          status: 'operResultOk',
          time: '11:52:33'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '11.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '5.49',
          operationCurrency: 'BYN',
          operationSum: '5.49',
          place: 'MUSIC PLUS.YANDEX.RU/5815',
          status: 'operResultOk',
          time: '00:00:00'
        },
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '10.03.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'BYN',
          inAccountSum: '3.51',
          operationCurrency: 'BYN',
          operationSum: '3.51',
          place: 'GRODNENSKIY TC "KORONA"/5411',
          status: 'operResultOk',
          time: '11:58:51'
        }
      ]
    ],
    [
      require('./holds2.html'),
      [
        {
          accountID: 'accountId',
          comment: 'Покупка/оплата/перевод',
          date: '14.09.2020',
          debitFlag: '-',
          fee: '0.00',
          inAccountCurrency: 'USD',
          inAccountSum: '0.86',
          operationCurrency: 'BYN',
          operationSum: '2.20',
          place: 'OPLATA USLUG/4900',
          status: 'operResultOk',
          time: '14:36:34'
        },
        {
          accountID: 'accountId',
          comment: 'Возврат покупки/оплаты/зачисление перевода',
          date: '14.09.2020',
          debitFlag: '+',
          fee: '0.00',
          inAccountCurrency: 'USD',
          inAccountSum: '1.14',
          operationCurrency: 'BYN',
          operationSum: '3.00',
          place: 'PEREVOD BAPB/6012',
          status: 'operResultOk',
          time: '13:56:23'
        }
      ]
    ]
  ])('parses holds', (html, transactions) => {
    expect(parseTransactions(html, 'accountId', 'hold')).toEqual(transactions)
  })
})
