// Выписка STATEM_XLS в формате SpreadsheetML 2003, строки взяты из настоящего
// файла: операция в валюте счёта, пополнение в рублях, итог по дню, покупка
// в лирах, комиссия, операция без ссылки, евро (курс в обратную сторону)
// и операция в валюте счёта со ссылкой в описании
export const STATEMENT_XML = `<?xml version="1.0"?><?mso-application progid="Excel.Sheet"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet" xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet">
<Worksheet ss:Name="Account ENG"><Table>
<Row ss:Index="21"><Cell ss:Index="1"><Data ss:Type="String">Date</Data></Cell><Cell ss:Index="2"><Data ss:Type="String">Amount</Data></Cell><Cell ss:Index="3"><Data ss:Type="String">Currency</Data></Cell><Cell ss:Index="4" ss:MergeAcross="1"><Data ss:Type="String">Credits</Data></Cell><Cell ss:Index="6" ss:MergeAcross="1"><Data ss:Type="String">Debits</Data></Cell><Cell ss:Index="8" ss:MergeAcross="1"><Data ss:Type="String">Exchange rate</Data></Cell></Row>
<Row ss:Index="22"><Cell ss:Index="1"><Data ss:Type="String">13.08.2026</Data></Cell><Cell ss:Index="2"><Data ss:Type="String">54.66</Data></Cell><Cell ss:Index="3"><Data ss:Type="String">USD</Data></Cell><Cell ss:Index="4" ss:MergeAcross="1"></Cell><Cell ss:Index="6" ss:MergeAcross="1"><Data ss:Type="String">-54.66</Data></Cell><Cell ss:Index="8" ss:MergeAcross="1"></Cell><Cell ss:Index="10" ss:MergeAcross="1"><Data ss:Type="String">13.08.2026</Data></Cell><Cell ss:Index="12" ss:MergeAcross="1"></Cell><Cell ss:Index="14" ss:MergeAcross="3"><Data ss:Type="String">Annual fee by pl.cards</Data></Cell></Row>
<Row ss:Index="23"><Cell ss:Index="1"><Data ss:Type="String">13.08.2026</Data></Cell><Cell ss:Index="2"><Data ss:Type="String">10,000.00</Data></Cell><Cell ss:Index="3"><Data ss:Type="String">RUR</Data></Cell><Cell ss:Index="4" ss:MergeAcross="1"><Data ss:Type="String">+115.33</Data></Cell><Cell ss:Index="6" ss:MergeAcross="1"></Cell><Cell ss:Index="8" ss:MergeAcross="1"><Data ss:Type="String">86.71</Data></Cell><Cell ss:Index="10" ss:MergeAcross="1"><Data ss:Type="String">13.08.2026</Data></Cell><Cell ss:Index="12" ss:MergeAcross="1"></Cell><Cell ss:Index="14" ss:MergeAcross="3"><Data ss:Type="String">POPOLNENIE SVOEGO ScETA 22300100000001, NDS NE OBLAGAETSa PL-K V.303 - ARTSAKHBANK CJSC</Data></Cell></Row>
<Row ss:Index="24"><Cell ss:Index="1"></Cell><Cell ss:Index="2"></Cell><Cell ss:Index="3"></Cell><Cell ss:Index="4" ss:MergeAcross="1"></Cell><Cell ss:Index="6" ss:MergeAcross="1"></Cell><Cell ss:Index="8" ss:MergeAcross="1"></Cell><Cell ss:Index="10" ss:MergeAcross="1"></Cell><Cell ss:Index="12" ss:MergeAcross="1"><Data ss:Type="String">60.67</Data></Cell><Cell ss:Index="14" ss:MergeAcross="3"><Data ss:Type="String">Balance at the end of day</Data></Cell></Row>
<Row ss:Index="25"><Cell ss:Index="1"><Data ss:Type="String">26.08.2026</Data></Cell><Cell ss:Index="2"><Data ss:Type="String">650.95</Data></Cell><Cell ss:Index="3"><Data ss:Type="String">TLY</Data></Cell><Cell ss:Index="4" ss:MergeAcross="1"></Cell><Cell ss:Index="6" ss:MergeAcross="1"><Data ss:Type="String">-13.87</Data></Cell><Cell ss:Index="8" ss:MergeAcross="1"><Data ss:Type="String">46.93</Data></Cell><Cell ss:Index="10" ss:MergeAcross="1"><Data ss:Type="String">28.08.2026</Data></Cell><Cell ss:Index="12" ss:MergeAcross="1"></Cell><Cell ss:Index="14" ss:MergeAcross="3"><Data ss:Type="String">01324422\\TUR\\ISTANBUL\\ASMA\\CARREFOURSA</Data></Cell></Row>
<Row ss:Index="26"><Cell ss:Index="1"><Data ss:Type="String">27.08.2026</Data></Cell><Cell ss:Index="2"><Data ss:Type="String">16,798.50</Data></Cell><Cell ss:Index="3"><Data ss:Type="String">TLY</Data></Cell><Cell ss:Index="4" ss:MergeAcross="1"></Cell><Cell ss:Index="6" ss:MergeAcross="1"><Data ss:Type="String">-8.28</Data></Cell><Cell ss:Index="8" ss:MergeAcross="1"><Data ss:Type="String">46.99</Data></Cell><Cell ss:Index="10" ss:MergeAcross="1"><Data ss:Type="String">31.08.2026</Data></Cell><Cell ss:Index="12" ss:MergeAcross="1"></Cell><Cell ss:Index="14" ss:MergeAcross="3"><Data ss:Type="String">Commission 00924236\\TUR\\ISTANBUL\\ISTA\\MESRUTIYET CA</Data></Cell></Row>
<Row ss:Index="27"><Cell ss:Index="1"><Data ss:Type="String">28.08.2026</Data></Cell><Cell ss:Index="2"><Data ss:Type="String">40.00</Data></Cell><Cell ss:Index="3"><Data ss:Type="String">TLY</Data></Cell><Cell ss:Index="4" ss:MergeAcross="1"></Cell><Cell ss:Index="6" ss:MergeAcross="1"><Data ss:Type="String">-0.85</Data></Cell><Cell ss:Index="8" ss:MergeAcross="1"><Data ss:Type="String">47.06</Data></Cell><Cell ss:Index="10" ss:MergeAcross="1"><Data ss:Type="String">31.08.2026</Data></Cell><Cell ss:Index="12" ss:MergeAcross="1"></Cell><Cell ss:Index="14" ss:MergeAcross="3"><Data ss:Type="String">\\NLD\\help.uber.com\\UBER *TRIP HE</Data></Cell></Row>
<Row ss:Index="28"><Cell ss:Index="1"><Data ss:Type="String">26.08.2026</Data></Cell><Cell ss:Index="2"><Data ss:Type="String">60.00</Data></Cell><Cell ss:Index="3"><Data ss:Type="String">EUR</Data></Cell><Cell ss:Index="4" ss:MergeAcross="1"></Cell><Cell ss:Index="6" ss:MergeAcross="1"><Data ss:Type="String">-71.46</Data></Cell><Cell ss:Index="8" ss:MergeAcross="1"><Data ss:Type="String">1.19</Data></Cell><Cell ss:Index="10" ss:MergeAcross="1"><Data ss:Type="String">28.08.2026</Data></Cell><Cell ss:Index="12" ss:MergeAcross="1"></Cell><Cell ss:Index="14" ss:MergeAcross="3"><Data ss:Type="String">04262266\\TUR\\ISTANBUL\\ISTA\\THE MARMARA O</Data></Cell></Row>
<Row ss:Index="29"><Cell ss:Index="1"><Data ss:Type="String">19.08.2026</Data></Cell><Cell ss:Index="2"><Data ss:Type="String">9.60</Data></Cell><Cell ss:Index="3"><Data ss:Type="String">USD</Data></Cell><Cell ss:Index="4" ss:MergeAcross="1"></Cell><Cell ss:Index="6" ss:MergeAcross="1"><Data ss:Type="String">-9.60</Data></Cell><Cell ss:Index="8" ss:MergeAcross="1"></Cell><Cell ss:Index="10" ss:MergeAcross="1"><Data ss:Type="String">24.08.2026</Data></Cell><Cell ss:Index="12" ss:MergeAcross="1"></Cell><Cell ss:Index="14" ss:MergeAcross="3"><Data ss:Type="String">G0A3LMSE\\USA\\SAN FRANCISCO\\ANTHROPIC</Data></Cell></Row>
</Table></Worksheet></Workbook>`
