import { convertTransaction } from '../../../converters'
import { accountGel } from '../../../tests-common/accounts'

describe('convertTransaction', () => {
  it.each([
    [
      {
        statmentId: 30747573761,
        acctKey: 11572944337,
        entryId: 51217870869,
        docKey: 13433317117,
        essId: null,
        nomination: 'Payment - Amount GEL1.50; Account Package Maintenance Fee.Acct #',
        entryGroup: null,
        merchantId: null,
        postDate: 1653681600000,
        authDateStr: null,
        inpSysdate: 1653771778000,
        operationDate: 1653681600000,
        amount: 1.5,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 1.5,
        entryGroupDKey: 'text.entry.group.name.FEE',
        entryGroupDValue: null,
        entryGroupNameId: 8,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623077,
        nominationOriginal: 'Account Package Maintenance Fee.Acct #',
        productName: null,
        prodGroup: 'FEE',
        entryType: 'FEE',
        printSwift: 'N',
        isPrintable: 'N',
        printFormType: 'OTHER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'Y',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623077&hashCode=CA894874A1F7E367A862FD192A412106',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623077&hashCode=CA894874A1F7E367A862FD192A412106',
        benefProfilePicture: null,
        operationTitle: 'Account Package Maintenance Fee.Acct #',
        entryDetailType: null,
        pfmId: 5139204236,
        pfmForecast: false,
        pfmCatId: 540,
        pfmCatName: null,
        pfmParentCatId: 520,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: false,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        comment: 'Account Package Maintenance Fee.Acct #',
        date: new Date('2022-05-29T01:02:58.000+04:00'),
        hold: false,
        merchant: null,
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '30747573761',
            invoice: null,
            sum: -1.5
          }
        ]
      }
    ],
    [
      {
        statmentId: 30787698311,
        acctKey: 11578997519,
        entryId: 51273332616,
        docKey: 13449171194,
        essId: null,
        nomination: 'Payment - Amount GEL2.00; Funds transfer from electronic till to the deposit, Agreement number# GE97BG0000000537338615',
        entryGroup: null,
        merchantId: null,
        postDate: 1653854400000,
        authDateStr: null,
        inpSysdate: 1653942757000,
        operationDate: 1653854400000,
        amount: 2,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 2,
        entryGroupDKey: 'text.entry.group.name.El.Money.Box',
        entryGroupDValue: null,
        entryGroupNameId: 11,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 386243,
        nominationOriginal: 'Funds transfer from electronic till to the deposit, Agreement number# GE97BG0000000537338615',
        productName: null,
        prodGroup: 'CAS',
        entryType: 'CAS',
        printSwift: 'N',
        isPrintable: 'N',
        printFormType: 'OTHER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'Y',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=386243&hashCode=E863EBC43B530EC03D04FAB5BB80261E',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=386243&hashCode=E863EBC43B530EC03D04FAB5BB80261E',
        benefProfilePicture: null,
        operationTitle: 'Funds transfer from electronic till to the deposit, Agreement number# GE97BG0000000537338615',
        entryDetailType: null,
        pfmId: 5151813480,
        pfmForecast: false,
        pfmCatId: 630,
        pfmCatName: null,
        pfmParentCatId: 590,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: false,
        isRuleCreationEnabled: false,
        canSplit: false,
        isCarTemplateAllowed: false
      },
      {
        comment: null,
        date: new Date('2022-05-31T00:32:37.000+04:00'),
        hold: false,
        merchant: null,
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '30787698311',
            invoice: null,
            sum: -2
          },
          {
            account: {
              company: null,
              instrument: 'GEL',
              syncIds: null,
              type: 'checking'
            },
            fee: 0,
            id: null,
            invoice: null,
            sum: 2
          }
        ]
      }
    ],
    [
      {
        statmentId: 30014161775,
        acctKey: 11565901492,
        entryId: 50695816022,
        docKey: 13278509966,
        essId: null,
        nomination: 'Payment - Amount GEL0.01; Overdraft Interest deduction',
        entryGroup: null,
        merchantId: null,
        postDate: 1652126400000,
        authDateStr: null,
        inpSysdate: 1652218600000,
        operationDate: 1652126400000,
        amount: 0.01,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 0.01,
        entryGroupDKey: 'text.entry.group.name.overdraft',
        entryGroupDValue: null,
        entryGroupNameId: 12,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 60233554,
        nominationOriginal: 'Overdraft Interest deduction',
        productName: null,
        prodGroup: 'CDS',
        entryType: 'CDS',
        printSwift: 'N',
        isPrintable: 'N',
        printFormType: 'OTHER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=60233554&hashCode=F067AB79385BA78874C50E34D2E14B29',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=60233554&hashCode=F067AB79385BA78874C50E34D2E14B29',
        benefProfilePicture: null,
        operationTitle: 'Overdraft Interest deduction',
        entryDetailType: null,
        pfmId: 5005114619,
        pfmForecast: false,
        pfmCatId: 567,
        pfmCatName: null,
        pfmParentCatId: 520,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: false,
        canSplit: false,
        isCarTemplateAllowed: false
      },
      {
        comment: 'Overdraft Interest deduction',
        date: new Date('2022-05-11T01:36:40.000+04:00'),
        hold: false,
        merchant: null,
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '30014161775',
            invoice: null,
            sum: -0.01
          }
        ]
      }
    ],
    [
      {
        statmentId: 30752187905,
        acctKey: 11579180847,
        entryId: 51242615006,
        docKey: 13438528624,
        essId: null,
        nomination: 'Payment - Amount GEL1.00; Payment - Amount: GEL1.00; Tbilisi Bus - route number 300; Date: 29/05/2022 15:12:17; Card No: ****8031',
        entryGroup: null,
        merchantId: null,
        postDate: 1653768000000,
        authDateStr: null,
        inpSysdate: 1653822854000,
        operationDate: 1653768000000,
        amount: 1,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 1,
        entryGroupDKey: 'text.entry.group.name.Payment',
        entryGroupDValue: null,
        entryGroupNameId: 7,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623083,
        nominationOriginal: 'Payment - Amount: GEL1.00; Tbilisi Bus - route number 300; Date: 29/05/2022 15:12:17; Card No: ****8031',
        productName: null,
        prodGroup: 'TCC',
        entryType: 'TCT',
        printSwift: 'N',
        isPrintable: 'N',
        printFormType: 'OTHER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        benefProfilePicture: null,
        operationTitle: 'Payment - Amount: GEL1.00; Tbilisi Bus - route number 300; Date: 29/05/2022 15:12:17; Card No: ****8031',
        entryDetailType: null,
        pfmId: 5146898024,
        pfmForecast: false,
        pfmCatId: 160,
        pfmCatName: null,
        pfmParentCatId: 120,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: false,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        comment: 'Payment - Amount: GEL1.00; Tbilisi Bus - route number 300; Date: 29/05/2022 15:12:17; Card No: ****8031',
        date: new Date('2022-05-29T15:14:14.000+04:00'),
        hold: false,
        merchant: null,
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '30752187905',
            invoice: null,
            sum: -1
          }
        ]
      }
    ],
    [
      {
        statmentId: 31124567663,
        acctKey: 11574837328,
        entryId: 51480229020,
        docKey: 13508448330,
        essId: null,
        nomination: 'Withdrawal - Amount: GEL1,000.00; ATM: Bank Of Georgia, Batumi, Zubalashvili st. 18; MCC:6011; Date: 05/06/2022 16:49; Card No: ****6663; Payment transaction amount and currency: 1,000.00 GEL',
        entryGroup: null,
        merchantId: 'ATM11042',
        postDate: 1654459200000,
        authDateStr: '05/06/2022 16:49',
        inpSysdate: 1654501228000,
        operationDate: 1654433340000,
        amount: 2,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: 'სს საქართველოს ბანკი, ბათუმი, ზუბალაშვილის ქ. N18',
        merchantNameInt: 'Bank Of Georgia, Batumi, Zubalashvili st. 18',
        amountBase: 2,
        entryGroupDKey: 'text.entry.group.name.widthroval',
        entryGroupDValue: null,
        entryGroupNameId: 1,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623075,
        nominationOriginal: 'Withdrawal - Amount: GEL1,000.00; ATM: Bank Of Georgia, Batumi, Zubalashvili st. 18; MCC:6011; Date: 05/06/2022 16:49; Card No: ****6663; Payment transaction amount and currency: 1,000.00 GEL',
        productName: null,
        prodGroup: 'PLC',
        entryType: 'COM',
        printSwift: 'N',
        isPrintable: 'N',
        printFormType: 'OTHER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'A',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: 1654372800000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623075&hashCode=D2617C8163F094FEA7E491FC27535EFA',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623075&hashCode=D2617C8163F094FEA7E491FC27535EFA',
        benefProfilePicture: null,
        operationTitle: 'Bank Of Georgia, Batumi, Zubalashvili st. 18',
        entryDetailType: null,
        pfmId: 5201536919,
        pfmForecast: false,
        pfmCatId: 540,
        pfmCatName: null,
        pfmParentCatId: 520,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: false,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        date: new Date('2022-06-05T16:49:00+04:00'),
        hold: false,
        merchant: null,
        movements: [
          {
            account: { id: '1337' },
            fee: 0,
            id: '31124567663',
            invoice: null,
            sum: -2
          }
        ],
        comment: 'cash withdrawal fee'
      }
    ],
    [
      {
        statmentId: 31317445544,
        acctKey: 11579489835,
        entryId: 51638665375,
        docKey: 13555449096,
        essId: null,
        nomination: 'Payment - Amount GEL102.98; Loan repayment, Loan N 8409346',
        entryGroup: null,
        merchantId: null,
        postDate: 1654891200000,
        authDateStr: null,
        inpSysdate: 1654933623000,
        operationDate: 1654891200000,
        amount: 102.98,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 102.98,
        entryGroupDKey: 'text.entry.group.name.Loan.Repayment',
        entryGroupDValue: null,
        entryGroupNameId: 9,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623081,
        nominationOriginal: 'Loan repayment, Loan N 8409346',
        productName: 'Cash Cover Loan',
        prodGroup: 'LND',
        entryType: 'LND',
        printSwift: 'N',
        isPrintable: 'N',
        printFormType: 'OTHER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623081&hashCode=FB9A554FBC2110BF4B77ADC3C321C4F9',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623081&hashCode=FB9A554FBC2110BF4B77ADC3C321C4F9',
        benefProfilePicture: null,
        operationTitle: 'Cash Cover Loan',
        entryDetailType: null,
        pfmId: 5241452564,
        pfmForecast: false,
        pfmCatId: 570,
        pfmCatName: null,
        pfmParentCatId: 520,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: false,
        canSplit: false,
        isCarTemplateAllowed: false
      },
      {
        date: new Date('2022-06-11T07:47:03.000Z'),
        hold: false,
        merchant: null,
        movements: [
          {
            account: { id: '1337' },
            fee: 0,
            id: '31317445544',
            invoice: null,
            sum: -102.98
          }
        ],
        comment: 'Loan repayment, Loan N 8409346'
      }
    ],
    [
      {
        statmentId: 31273841405,
        acctKey: 11579489835,
        entryId: 51611480771,
        docKey: 13547630868,
        essId: null,
        nomination: 'Income - Amount GEL102.98; Loan disbursement',
        entryGroup: null,
        merchantId: null,
        postDate: 1654804800000,
        authDateStr: null,
        inpSysdate: 1654859614000,
        operationDate: 1654804800000,
        amount: -102.98,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: -102.98,
        entryGroupDKey: 'text.entry.group.name.Income',
        entryGroupDValue: null,
        entryGroupNameId: 5,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623078,
        nominationOriginal: 'Loan disbursement',
        productName: 'Cash Cover Loan',
        prodGroup: 'LND',
        entryType: 'LND',
        printSwift: 'N',
        isPrintable: 'N',
        printFormType: 'OTHER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623078&hashCode=DE3E0F781F86C1E3C9652CBF00F43784',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623078&hashCode=DE3E0F781F86C1E3C9652CBF00F43784',
        benefProfilePicture: null,
        operationTitle: 'Cash Cover Loan',
        entryDetailType: null,
        pfmId: 5233226028,
        pfmForecast: false,
        pfmCatId: 920,
        pfmCatName: null,
        pfmParentCatId: 840,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: false,
        canSplit: false,
        isCarTemplateAllowed: false
      },
      {
        date: new Date('2022-06-10T11:13:34.000Z'),
        hold: false,
        merchant: null,
        movements: [
          {
            account: { id: '1337' },
            fee: 0,
            id: '31273841405',
            invoice: null,
            sum: 102.98
          }
        ],
        comment: 'Loan disbursement'
      }
    ],
    [
      {
        statmentId: 32432123143243,
        acctKey: 11579489835,
        entryId: 89993651519,
        docKey: 25521517507,
        essId: null,
        nomination: 'Withdrawal - Amount: MAD3,850.00; ATM: 0000011619, Morocco; MCC:6011; Date: 15/01/2025 15:37; Card No: ****2285; Payment transaction amount and currency: 390.47 USD; Bank conversion commission fee: 7.66 USD; Card scheme conversion rate  (USD-MAD): 10.0572',
        entryGroup: null,
        merchantId: 'EDMA0214',
        postDate: '2025-01-16T00:00:00', // 1736971200000
        authDateStr: '15/01/2025 15:37',
        inpSysdate: 1654859614000, // 1737035610000
        operationDate: '2025-01-15T15:37:00', // 1736941020000
        amount: 21.79,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: '0000011619, მაროკო',
        merchantNameInt: '0000011619, Morocco',
        amountBase: 21.79,
        entryGroupDKey: 'text.entry.group.name.widthroval',
        entryGroupDValue: null,
        entryGroupNameId: 1,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: '35623075',
        nominationOriginal: 'Withdrawal - Amount: MAD3,850.00; ATM: 0000011619, Morocco; MCC:6011; Date: 15/01/2025 15:37; Card No: ****2285; Payment transaction amount and currency: 390.47 USD; Bank conversion commission fee: 7.66 USD; Card scheme conversion rate  (USD-MAD): 10.0572',
        productName: null,
        prodGroup: 'PLC',
        entryType: 'COM',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'CASH_WITHDRAWAL',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'A',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: 1736884800000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: true,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: '<dummy>',
        imageUrl: '<dummy>',
        benefProfilePicture: null,
        operationTitle: '0000011619, Morocco',
        entryDetailType: null,
        pfmId: 12398819414,
        pfmForecast: false,
        pfmCatId: 540, // 'text.pfm.child.category.bank.fees'
        pfmCatName: null,
        pfmParentCatId: 520,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: false,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        comment: 'Cash withdrawal comission / Withdrawal - Amount: MAD3,850.00; ATM: 0000011619, Morocco; MCC:6011; Date: 15/01/2025 15:37; Card No: ****2285; Payment transaction amount and currency: 390.47 USD; Bank conversion commission fee: 7.66 USD; Card scheme conversion rate  (USD-MAD): 10.0572',
        date: new Date('2025-01-15T15:37:00+04:00'),
        hold: false,
        merchant: {
          city: null,
          country: 'Morocco',
          location: null,
          mcc: 6011,
          title: '0000011619'
        },
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '32432123143243',
            invoice: null,
            sum: -21.79
          }
        ]
      }
    ],
    [
      {
        accountKey: '12596401624',
        entryId: '123552312311',
        docKey: 28943212313,
        clientKey: '60588505',
        language: 'EN',
        sourceEntryGroup: 'OTHER',
        nomination: ' Credit Funds - Amount: USD12.40; Merchant: Trip.com, United Kingdom of Great Britain and Northern Ireland; MCC:4722; Date: 23/08/2025 05:06; Card No: ****4346; Payment transaction amount and currency: 12.40 USD',
        postDate: '2025-08-23T00:00:00',
        authDate: '23/08/2025 05:06',
        operationDate: '2025-08-23T00:00:00',
        amount: '-12.4',
        oppositeAmount: '12.4',
        ccy: 'GEL',
        canCopy: 'N',
        status: 'P',
        merchantName: 'Trip.com, გაერთიანებული სამეფო',
        merchantNameInt: 'Trip.com, United Kingdom of Great Britain and Northern Ireland',
        nominationOriginal: 'Credit Funds - Amount: USD12.40; Merchant: Trip.com, United Kingdom of Great Britain and Northern Ireland; MCC:4722; Date: 23/08/2025 05:06; Card No: ****4346; Payment transaction amount and currency: 12.40 GEL',
        prodGroup: 'PLC',
        entryType: 'TRN',
        printSwift: 'N',
        isInternalOperation: 'N',
        entryGroupNameId: '4',
        groupImageId: '35623082',
        groupImageIdSolo: '3127030266',
        groupImageIdWm: '3127057174',
        hasTransferBack: 'N',
        printFormType: 'OTHER',
        printForm: 'Y',
        entryGroupDValue: 'text.entry.group.name.Other',
        operationTitle: 'Trip.com, United Kingdom of Great Britain and Northern Ireland',
        cardLastDigits: '4346',
        sort: [
          '1755892800000',
          '28943212313',
          '123552312311'
        ],
        isStatementAllowed: true,
        trIdentifierForPostBnpl: '28943212313',
        isTransactionForPostBnpl: 'N',
        pfmId: '123552312311',
        pfmCatId: '900',
        pfmCatName: 'text.pfm.child.category.transfer.in',
        pfmParentCatId: '840'
      },
      {
        comment: null,
        date: new Date('2025-08-23T01:06:00.000Z'),
        groupKeys: [
          '28943212313'
        ],
        hold: false,
        merchant: null,
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '123552312311',
            invoice: null,
            sum: 12.4
          }
        ]
      }
    ]
  ])('converts other', (apiTransaction, transaction) => {
    expect(convertTransaction(apiTransaction, accountGel)).toEqual(transaction)
  })
})
