import { convertTransaction } from '../../../converters'
import { accountGel, accountUsd } from '../../../tests-common/accounts'

describe('convertTransaction', () => {
  it.each([
    [
      {
        statmentId: 28673866172,
        acctKey: 11570661145,
        entryId: 49719366874,
        docKey: 12983595645,
        essId: null,
        nomination: 'Payment - Amount: GEL11.00; Merchant: shawarmania, Tbilisi, vekua 3a; MCC:5812; Date: 04/04/2022 21:01; Card No: ****5585; Payment transaction amount and currency: 11.00 GEL',
        entryGroup: null,
        merchantId: 'POS1RY16',
        postDate: 1649102400000,
        authDateStr: '04/04/2022 21:01',
        inpSysdate: 1649091699000,
        operationDate: 1649091660000,
        amount: 11,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'F',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: 'shawarmania, თბილისი, ვეკუას 3ა',
        merchantNameInt: 'shawarmania, Tbilisi, vekua 3a',
        amountBase: 11,
        entryGroupDKey: 'text.entry.group.name.Payment',
        entryGroupDValue: null,
        entryGroupNameId: 7,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623083,
        nominationOriginal: 'Payment - Amount: GEL11.00; Merchant: shawarmania, Tbilisi, vekua 3a; MCC:5812; Date: 04/04/2022 21:01; Card No: ****5585; Payment transaction amount and currency: 11.00 GEL',
        productName: null,
        prodGroup: 'PLC',
        entryType: 'GCE',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'PAYMENT',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'P',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: 1649016000000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        benefProfilePicture: null,
        operationTitle: 'shawarmania, Tbilisi, vekua 3a',
        entryDetailType: null,
        pfmId: null,
        pfmForecast: null,
        pfmCatId: null,
        pfmCatName: null,
        pfmParentCatId: null,
        pfmParentCatName: null,
        pfmRecurring: null,
        pfmSplit: null,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: null,
        isRuleCreationEnabled: null,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        comment: null,
        date: new Date('2022-04-04T21:01:00+04:00'),
        hold: true,
        merchant: {
          country: null,
          city: 'Tbilisi',
          title: 'shawarmania',
          location: null,
          mcc: 5812
        },
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '28673866172',
            invoice: { instrument: 'GEL', sum: -11 },
            sum: -11
          }
        ]
      }
    ],
    [
      {
        statmentId: 28403593963,
        acctKey: 11570661145,
        entryId: 49501187219,
        docKey: 12919098479,
        essId: null,
        nomination: 'Payment - Amount: GEL23.20; Merchant: BOLT.EU/C/2203261556, Estonia; MCC:4121; Date: 26/03/2022 15:56; Card No: ****5585; Payment transaction amount and currency: 23.20 GEL; Card scheme conversion rate (USD-GEL): 3.1868; Bank conversion rate (USD-GEL): 3.2234',
        entryGroup: null,
        merchantId: null,
        postDate: 1648324800000,
        authDateStr: '26/03/2022 15:56',
        inpSysdate: 1648379733000,
        operationDate: 1648295760000,
        amount: 23.2,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: 'BOLT.EU/C/2203261556, ესტონეთი',
        merchantNameInt: 'BOLT.EU/C/2203261556, Estonia',
        amountBase: 23.2,
        entryGroupDKey: 'text.entry.group.name.Payment',
        entryGroupDValue: null,
        entryGroupNameId: 7,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623083,
        nominationOriginal: 'Payment - Amount: GEL23.20; Merchant: BOLT.EU/C/2203261556, Estonia; MCC:4121; Date: 26/03/2022 15:56; Card No: ****5585; Payment transaction amount and currency: 23.20 GEL; Card scheme conversion rate  (USD-GEL): 3.1868; Bank conversion rate (USD-GEL): 3.2234',
        productName: null,
        prodGroup: 'CCO',
        entryType: 'CCO',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'PAYMENT',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'P',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: 1648238400000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        benefProfilePicture: 'serviceId=IDENTITY_GET_USER_PUBLIC_AVATAR&entryId=49501187219',
        operationTitle: 'BOLT.EU/C/2203261556, Estonia',
        entryDetailType: null,
        pfmId: 4686186530,
        pfmForecast: false,
        pfmCatId: 140,
        pfmCatName: null,
        pfmParentCatId: 120,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        comment: null,
        date: new Date('2022-03-26T15:56:00+04:00'),
        hold: false,
        merchant: {
          country: 'Estonia',
          city: null,
          title: 'BOLT.EU/C/2203261556',
          location: null,
          mcc: 4121
        },
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '28403593963',
            invoice: { instrument: 'GEL', sum: -23.2 },
            sum: -23.2
          }
        ]
      }
    ],
    [
      {
        statmentId: 28633254551,
        acctKey: 11570661145,
        entryId: 49670550200,
        docKey: 12969270177,
        essId: '7096872816',
        nomination: '24/7 Payment, 03/04/2022 , payment service, Magticom, Phone number 595231337, payment code - 7096872816',
        entryGroup: null,
        merchantId: null,
        postDate: 1648929600000,
        authDateStr: null,
        inpSysdate: 1648931927000,
        operationDate: 1648929600000,
        amount: 5,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: '24/7 Payment, 03/04/2022 , payment service, Magticom, Phone number 595231337, payment code - 7096872816',
        beneficiary: 'Magticom',
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 5,
        entryGroupDKey: 'text.entry.group.name.Payment',
        entryGroupDValue: null,
        entryGroupNameId: 7,
        bonusInfo: null,
        essServiceId: 'bog-comp-magti-web',
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623083,
        nominationOriginal: '24/7 Payment, 03/04/2022 , payment service, Magticom, Phone number 595231337, payment code - 7096872816',
        productName: null,
        prodGroup: 'PMD',
        entryType: 'PMD',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'OTHER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: 'BAGAGE22',
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: true,
        isTemplateAllowed: false,
        isDDSTOAlllowed: true,
        isStatementAllowed: true,
        isPrintAllowed: true,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=564204&hashCode=AF2BF2E5DC5505FB751C07DA3D62FC8C',
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=564204&hashCode=AF2BF2E5DC5505FB751C07DA3D62FC8C',
        benefProfilePicture: null,
        operationTitle: 'Magticom',
        entryDetailType: null,
        pfmId: 4736584262,
        pfmForecast: false,
        pfmCatId: 220,
        pfmCatName: null,
        pfmParentCatId: 200,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: false,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        comment: '24/7 Payment, 03/04/2022 , payment service, Magticom, Phone number 595231337, payment code - 7096872816',
        date: new Date('2022-04-03T00:38:47.000+04:00'),
        hold: false,
        merchant: {
          city: null,
          country: null,
          location: null,
          mcc: null,
          title: 'Magticom'
        },
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '28633254551',
            invoice: null,
            sum: -5
          }
        ]
      }
    ],
    [
      {
        statmentId: 28556039562,
        acctKey: 11570661145,
        entryId: 49610479921,
        docKey: 12950423051,
        essId: null,
        nomination: 'Payment - Amount GEL0.50; Payment Fee, 31/03/2022 , payment service, Magti Internet Services, subscriber Phone Number 325981234, payment code - 7082227650',
        entryGroup: null,
        merchantId: null,
        postDate: 1648670400000,
        authDateStr: null,
        inpSysdate: 1648734466000,
        operationDate: 1648670400000,
        amount: 0.5,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 0.5,
        entryGroupDKey: 'text.entry.group.default.OTHER',
        entryGroupDValue: null,
        entryGroupNameId: 4,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623082,
        nominationOriginal: 'Payment Fee, 31/03/2022 , payment service, Magti Internet Services, subscriber Phone Number 325981234, payment code - 7082227650',
        productName: null,
        prodGroup: 'COM',
        entryType: 'COM',
        printSwift: 'N',
        isPrintable: 'N',
        printFormType: 'OTHER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623082&hashCode=CC523BC5233CAC03C9CE4DE4C93BB7CC',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623082&hashCode=CC523BC5233CAC03C9CE4DE4C93BB7CC',
        benefProfilePicture: null,
        operationTitle: 'Payment Fee, 31/03/2022 , payment service, Magti Internet Services, subscriber Phone Number 325981234, payment code - 7082227650',
        entryDetailType: null,
        pfmId: null,
        pfmForecast: null,
        pfmCatId: null,
        pfmCatName: null,
        pfmParentCatId: null,
        pfmParentCatName: null,
        pfmRecurring: null,
        pfmSplit: null,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: null,
        isRuleCreationEnabled: null,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        comment: 'Payment Fee, 31/03/2022 , payment service, Magti Internet Services, subscriber Phone Number 325981234, payment code - 7082227650',
        date: new Date('2022-03-31T17:47:46.000+04:00'),
        hold: false,
        merchant: null,
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '28556039562',
            invoice: null,
            sum: -0.5
          }
        ]
      }
    ],
    [
      {
        statmentId: 31187576494,
        acctKey: 11578984147,
        entryId: 51547036216,
        docKey: 13525466807,
        essId: '7452276362',
        nomination: 'Payment - Amount: GEL22.82; Merchant: DIDI DIGOMI GAZ-IMB, Tbilisi, საქართველო, ძველი თბილისი, ქუჩა/მასივი: სულხან-საბას ქ. # 5/1, სახლის/კორპუსის ნომერი: .; MCC:4900; Customer: 7452276362;12944; Date: 07/06/2022 12:20; Card No: ****6859; Payment transaction amount and currency: 22.82 GEL',
        entryGroup: null,
        merchantId: 'POS19F29',
        postDate: 1654632000000,
        authDateStr: '07/06/2022 12:20',
        inpSysdate: 1654676067000,
        operationDate: 1654590000000,
        amount: 22.82,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: 22.82,
        merchantName: 'DIDI DIGOMI GAZ-IMB, თბილისი, საქართველო, ძველი თბილისი, ქუჩა/მასივი: სულხან-საბას ქ. # 5/1, სახლის/კორპუსის ნომერი: .',
        merchantNameInt: 'DIDI DIGOMI GAZ-IMB, Tbilisi, საქართველო, ძველი თბილისი, ქუჩა/მასივი: სულხან-საბას ქ. # 5/1, სახლის/კორპუსის ნომერი: .',
        amountBase: 22.82,
        entryGroupDKey: 'text.entry.group.name.Payment',
        entryGroupDValue: null,
        entryGroupNameId: 7,
        bonusInfo: 'PLUS Points: 22.82',
        essServiceId: 'bog-comp-dididighomi',
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623083,
        nominationOriginal: 'Payment - Amount: GEL22.82; Merchant: DIDI DIGOMI GAZ-IMB, Tbilisi, საქართველო, ძველი თბილისი, ქუჩა/მასივი: სულხან-საბას ქ. # 5/1, სახლის/კორპუსის ნომერი: .; MCC:4900; Customer: 7452276362;12944; Date: 07/06/2022 12:20; Card No: ****6859; Payment transaction amount and currency: 22.82 GEL',
        productName: null,
        prodGroup: 'PLC',
        entryType: 'TRN',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'UTILITY_PAYMENT',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'V',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: 1654545600000,
        bonusPointType: 'PLUS',
        attachmentFileBase64: null,
        isRepeatAllowed: true,
        isTemplateAllowed: false,
        isDDSTOAlllowed: true,
        isStatementAllowed: true,
        isPrintAllowed: true,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35628718&hashCode=C6C4C532F6BDE79CBA562E06D93690EA',
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35628718&hashCode=C6C4C532F6BDE79CBA562E06D93690EA',
        benefProfilePicture: null,
        operationTitle: 'DIDI DIGOMI GAZ-IMB, Tbilisi, საქართველო, ძველი თბილისი, ქუჩა/მასივი: სულხან-საბას ქ. # 5/1, სახლის/კორპუსის ნომერი: .',
        entryDetailType: null,
        pfmId: 5216788573,
        pfmForecast: false,
        pfmCatId: 240,
        pfmCatName: null,
        pfmParentCatId: 200,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        comment: null,
        date: new Date('2022-06-07T12:20:00+04:00'),
        hold: false,
        merchant: {
          country: null,
          city: 'Tbilisi',
          title: 'DIDI DIGOMI GAZ-IMB',
          location: null,
          mcc: 4900
        },
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '31187576494',
            invoice: { instrument: 'GEL', sum: -22.82 },
            sum: -22.82
          }
        ]
      }
    ],
    [
      {
        statmentId: 31679675376,
        acctKey: 11570652305,
        entryId: 51914914098,
        docKey: 13635030958,
        essId: null,
        nomination: 'Payment - Amount: TRY40.00; Merchant: BIZTUR YIYECEK ICE.DAN, Turkey; MCC:5812; Date: 19/06/2022 10:40; Card No: ****0632; Payment transaction amount and currency: 7.02 GEL; Bank conversion commission fee: 0.05 USD; Card scheme conversion rate (USD-TRY): 17.0213; Bank conversion rate (USD-GEL): 2.9239',
        entryGroup: null,
        merchantId: 'S0VX1602',
        postDate: 1655668800000,
        authDateStr: '19/06/2022 10:40',
        inpSysdate: 1655722577000,
        operationDate: 1655620800000,
        amount: 7.02,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: 'BIZTUR YIYECEK ICE.DAN, თურქეთი',
        merchantNameInt: 'BIZTUR YIYECEK ICE.DAN, Turkey',
        amountBase: 7.02,
        entryGroupDKey: 'text.entry.group.name.Payment',
        entryGroupDValue: null,
        entryGroupNameId: 7,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623083,
        nominationOriginal: 'Payment - Amount: TRY40.00; Merchant: BIZTUR YIYECEK ICE.DAN, Turkey; MCC:5812; Date: 19/06/2022 10:40; Card No: ****0632; Payment transaction amount and currency: 7.02 GEL; Bank conversion commission fee: 0.05 USD; Card scheme conversion rate (USD-TRY): 17.0213; Bank conversion rate (USD-GEL): 2.9239',
        productName: null,
        prodGroup: 'CCO',
        entryType: 'CCO',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'PAYMENT',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'P',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: 1655582400000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        benefProfilePicture: null,
        operationTitle: 'BIZTUR YIYECEK ICE.DAN, Turkey',
        entryDetailType: null,
        pfmId: 5311831502,
        pfmForecast: false,
        pfmCatId: 20,
        pfmCatName: null,
        pfmParentCatId: 10,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        hold: false,
        date: new Date('2022-06-19T10:40:00+04:00'),
        movements:
          [
            {
              id: '31679675376',
              account: { id: '1337' },
              invoice: { instrument: 'TRY', sum: -40 },
              sum: -7.02,
              fee: 0
            }
          ],
        merchant:
          {
            country: 'Turkey',
            city: null,
            title: 'BIZTUR YIYECEK ICE.DAN',
            mcc: 5812,
            location: null
          },
        comment: null
      }
    ],
    [
      {
        statmentId: 31699353607,
        acctKey: 11572779360,
        entryId: 51895885420,
        docKey: 13629972863,
        essId: null,
        nomination: 'Payment - Amount: BYN50.00; Merchant: IR WWW.VERBITSKAYA.BY>MINSK BY, Belarus; MCC:8099; Date: 20/06/2022 00:07; Card No: ****0434; Payment transaction amount and currency: 58.45 GEL; Bank conversion rate (BYN-GEL): 1.169',
        entryGroup: null,
        merchantId: 'SWA27045',
        postDate: 1655841600000,
        authDateStr: '20/06/2022 00:07',
        inpSysdate: 1655672836000,
        operationDate: 1655669220000,
        amount: 58.45,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'F',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: 'IR WWW.VERBITSKAYA.BY>MINSK BY, ბელარუსი',
        merchantNameInt: 'IR WWW.VERBITSKAYA.BY>MINSK BY, Belarus',
        amountBase: 58.45,
        entryGroupDKey: 'text.entry.group.name.Payment',
        entryGroupDValue: null,
        entryGroupNameId: 7,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623083,
        nominationOriginal: 'Payment - Amount: BYN50.00; Merchant: IR WWW.VERBITSKAYA.BY>MINSK BY, Belarus; MCC:8099; Date: 20/06/2022 00:07; Card No: ****0434; Payment transaction amount and currency: 58.45 GEL; Bank conversion rate (BYN-GEL): 1.169',
        productName: null,
        prodGroup: 'PLC',
        entryType: 'GCE',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'PAYMENT',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'N',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: 1655668800000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        benefProfilePicture: null,
        operationTitle: 'IR WWW.VERBITSKAYA.BY>MINSK BY, Belarus',
        entryDetailType: null,
        pfmId: 5319342210,
        pfmForecast: false,
        pfmCatId: 450,
        pfmCatName: null,
        pfmParentCatId: 440,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        date: new Date('2022-06-20T00:07:00+04:00'),
        hold: true,
        movements: [
          {
            account: { id: '1337' },
            fee: 0,
            id: '31699353607',
            invoice: { instrument: 'BYN', sum: -50 },
            sum: -58.45
          }
        ],
        merchant: {
          city: 'MINSK BY',
          country: 'Belarus',
          title: 'IR WWW.VERBITSKAYA.BY',
          location: null,
          mcc: 8099
        },
        comment: null
      }
    ],
    [
      {
        statmentId: 30286011908,
        acctKey: 11576264704,
        entryId: 50884246019,
        docKey: 13336330846,
        essId: '7340388813',
        nomination: 'Payment - Amount GEL35.00; Payment - Amount: GEL35.00; &PROVIDER_NAME, Customer/Code# 7340388813;422922038; Date: ',
        entryGroup: null,
        merchantId: null,
        postDate: 1652731200000,
        authDateStr: null,
        inpSysdate: 1652776613000,
        operationDate: 1652731200000,
        amount: 35,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 35,
        entryGroupDKey: 'text.entry.group.default.OTHER',
        entryGroupDValue: null,
        entryGroupNameId: 4,
        bonusInfo: null,
        essServiceId: 'bog-comp-magticaucasus',
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623082,
        nominationOriginal: 'Payment - Amount: GEL35.00; &PROVIDER_NAME, Customer/Code# 7340388813;422922038; Date: ',
        productName: null,
        prodGroup: 'PBS',
        entryType: 'PBS',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'UTILITY_PAYMENT',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: true,
        isTemplateAllowed: false,
        isDDSTOAlllowed: true,
        isStatementAllowed: true,
        isPrintAllowed: true,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=656300&hashCode=A8354E47F358DF36B7238557E88B46CD',
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623082&hashCode=CC523BC5233CAC03C9CE4DE4C93BB7CC',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=656300&hashCode=A8354E47F358DF36B7238557E88B46CD',
        benefProfilePicture: null,
        operationTitle: 'Payment - Amount: GEL35.00; &PROVIDER_NAME, Customer/Code# 7340388813;422922038; Date: ',
        entryDetailType: null,
        pfmId: 5056615030,
        pfmForecast: false,
        pfmCatId: 230,
        pfmCatName: null,
        pfmParentCatId: 200,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: false,
        isCarTemplateAllowed: false
      },
      {
        date: new Date('2022-05-17T12:36:53+04:00'),
        hold: false,
        merchant: null,
        movements: [
          {
            account: { id: '1337' },
            fee: 0,
            id: '30286011908',
            invoice: { instrument: 'GEL', sum: -35 },
            sum: -35
          }
        ],
        comment: 'Payment - Amount: GEL35.00; &PROVIDER_NAME, Customer/Code# 7340388813;422922038; Date: '
      }
    ],
    [
      {
        statmentId: 33128066018,
        acctKey: 11578503896,
        entryId: 52658170613,
        docKey: 13859053808,
        essId: null,
        nomination: 'Payment - Amount: ILS50.00; Merchant: GETT>>TEL AVIV-JAF IL, Israel; MCC:4789; Date: 14/07/2022 06:39; Card No: ****5251; Payment transaction amount and currency: 43.32 GEL; Bank conversion rate (ILS-GEL): .8663',
        entryGroup: null,
        merchantId: '71520040',
        postDate: 1659038400000,
        authDateStr: '14/07/2022 06:39',
        inpSysdate: 1657780771000,
        operationDate: 1657766340000,
        amount: 43.32,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'F',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: 'GETT>>TEL AVIV-JAF IL, ისრაელი',
        merchantNameInt: 'GETT>>TEL AVIV-JAF IL, Israel',
        amountBase: 43.32,
        entryGroupDKey: 'text.entry.group.name.Payment',
        entryGroupDValue: null,
        entryGroupNameId: 7,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623083,
        nominationOriginal: 'Payment - Amount: ILS50.00; Merchant: GETT>>TEL AVIV-JAF IL, Israel; MCC:4789; Date: 14/07/2022 06:39; Card No: ****5251; Payment transaction amount and currency: 43.32 GEL; Bank conversion rate (ILS-GEL): .8663',
        productName: null,
        prodGroup: 'PLC',
        entryType: 'GCE',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'PAYMENT',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'N',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: 1657742400000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        benefProfilePicture: null,
        operationTitle: 'GETT>>TEL AVIV-JAF IL, Israel',
        entryDetailType: null,
        pfmId: 5525517078,
        pfmForecast: false,
        pfmCatId: 190,
        pfmCatName: null,
        pfmParentCatId: 120,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        hold: true,
        date: new Date('2022-07-14T06:39:00+04:00'),
        movements:
          [
            {
              id: '33128066018',
              account: { id: '1337' },
              invoice: { instrument: 'ILS', sum: -50 },
              sum: -43.32,
              fee: 0
            }
          ],
        merchant:
          {
            country: 'Israel',
            city: null,
            title: 'GETT',
            mcc: 4789,
            location: null
          },
        comment: null
      }
    ],
    [
      {
        statmentId: 87002157228,
        acctKey: 11621211351,
        entryId: 92835972518,
        docKey: 26374168116,
        essId: null,
        nomination: 'Payment - Amount: GEL78.35; Merchant: SAKARTV.FINANSTA SAMINISTRO, Tbilisi, ქ. თბილისი, რ-ნი: ვაკე-საბურთალო, ი. აბაშიძისს ქ.#70,; MCC:9399; Customer: 58P3E360212; Date: 15/03/2025 18:51; Card No: ****9759; Payment transaction amount and currency: 78.35 GEL',
        entryGroup: null,
        merchantId: 'POS18016',
        postDate: 1742068800000,
        authDateStr: '15/03/2025 18:51',
        inpSysdate: 1742112926000,
        operationDate: 1742050260000,
        amount: 1,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: 'SAKARTV.FINANSTA SAMINISTRO, თბილისი, ქ. თბილისი, რ-ნი: ვაკე-საბურთალო, ი. აბაშიძისს ქ.#70,',
        merchantNameInt: 'SAKARTV.FINANSTA SAMINISTRO, Tbilisi, ქ. თბილისი, რ-ნი: ვაკე-საბურთალო, ი. აბაშიძისს ქ.#70,',
        amountBase: 1,
        entryGroupDKey: 'text.entry.group.name.FEE',
        entryGroupDValue: null,
        entryGroupNameId: 8,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623077,
        nominationOriginal: 'Payment - Amount: GEL78.35; Merchant: SAKARTV.FINANSTA SAMINISTRO, Tbilisi, ქ. თბილისი, რ-ნი: ვაკე-საბურთალო, ი. აბაშიძისს ქ.#70,; MCC:9399; Customer: 58P3E360212; Date: 15/03/2025 18:51; Card No: ****9759; Payment transaction amount and currency: 78.35 GEL',
        productName: null,
        prodGroup: 'PLC',
        entryType: 'COM',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'PAYMENT',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'V',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        gifUrl: null,
        gifId: null,
        authDate: 1741982400000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: true,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623077&hashCode=CA894874A1F7E367A862FD192A412106',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623077&hashCode=CA894874A1F7E367A862FD192A412106',
        benefProfilePicture: null,
        operationTitle: 'SAKARTV.FINANSTA SAMINISTRO, Tbilisi, ქ. თბილისი, რ-ნი: ვაკე-საბურთალო, ი. აბაშიძისს ქ.#70,',
        entryDetailType: null,
        pfmId: 92835972518,
        pfmForecast: null,
        pfmCatId: 540,
        pfmCatName: '#text.pfm.child.category.bank.fees',
        pfmParentCatId: 520,
        pfmParentCatName: null,
        pfmRecurring: null,
        pfmSplit: null,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        comment: null,
        date: new Date('2025-03-15T14:51:00'),
        hold: false,
        merchant: {
          city: 'Tbilisi',
          country: null,
          location: null,
          mcc: 9399,
          title: 'SAKARTV.FINANSTA SAMINISTRO'
        },
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '87002157228',
            invoice: null,
            sum: -1
          }
        ]
      }
    ]
  ])('converts purchase accountGel', (apiTransaction, transaction) => {
    expect(convertTransaction(apiTransaction, accountGel)).toEqual(transaction)
  })

  it.each([
    [
      {
        statmentId: 32168247141,
        acctKey: 11579927194,
        entryId: 52319534735,
        docKey: 13754278581,
        essId: null,
        nomination: 'Payment - Amount: USD1.00; Merchant: AIRBNB> \\\\, ; MCC:4722; Date: 03/07/2022 07:53; Card No: ****2718; Payment transaction amount and currency: 1.00 USD; Bank conversion rate (USD-GEL): 2.92',
        entryGroup: null,
        merchantId: 'FN00G440',
        postDate: 1656878400000,
        authDateStr: '03/07/2022 07:53',
        inpSysdate: 1656859980000,
        operationDate: 1656820380000,
        amount: 1,
        oppositeAmount: null,
        ccy: 'USD',
        clientComment: null,
        canCopy: 'N',
        status: 'F',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: 'AIRBNB> \\\\, ',
        merchantNameInt: 'AIRBNB> \\\\, ',
        amountBase: 2.91,
        entryGroupDKey: 'text.entry.group.name.Payment',
        entryGroupDValue: null,
        entryGroupNameId: 7,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623083,
        nominationOriginal: 'Payment - Amount: USD1.00; Merchant: AIRBNB> \\\\, ; MCC:4722; Date: 03/07/2022 07:53; Card No: ****2718; Payment transaction amount and currency: 1.00 USD; Bank conversion rate (USD-GEL): 2.92',
        productName: null,
        prodGroup: 'PLC',
        entryType: 'GCE',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'PAYMENT',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'P',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: 1656792000000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        benefProfilePicture: null,
        operationTitle: 'AIRBNB> \\\\, ',
        entryDetailType: null,
        pfmId: 5414203948,
        pfmForecast: false,
        pfmCatId: 730,
        pfmCatName: null,
        pfmParentCatId: 720,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        hold: true,
        date: new Date('2022-07-03T07:53:00+04:00'),
        movements:
          [
            {
              id: '32168247141',
              account: { id: '1338' },
              invoice: null,
              sum: -1,
              fee: 0
            }
          ],
        merchant:
          {
            country: null,
            city: null,
            title: 'AIRBNB',
            mcc: 4722,
            location: null
          },
        comment: null
      }
    ],
    [
      {
        statmentId: 52795765971,
        acctKey: 11598288203,
        entryId: 67700476298,
        docKey: 18434745315,
        essId: null,
        nomination: 'Payment - Amount: USD33.88; Merchant: MAILGUN TECHNOLOGIES,, United States of America; MCC:5734; Date: 02/09/2023 08:42; Card No: ****3035; Payment transaction amount and currency: 33.88 USD',
        entryGroup: null,
        merchantId: '3LYQJFJV',
        postDate: 1693684800000,
        authDateStr: '02/09/2023 08:42',
        inpSysdate: 1693744055000,
        operationDate: 1693629720000,
        amount: 33.88,
        oppositeAmount: null,
        ccy: 'USD',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: null,
        bonusPoint: null,
        merchantName: 'MAILGUN TECHNOLOGIES,, აშშ',
        merchantNameInt: 'MAILGUN TECHNOLOGIES,, United States of America',
        amountBase: 88.94,
        entryGroupDKey: 'text.entry.group.name.Payment',
        entryGroupDValue: null,
        entryGroupNameId: 7,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623083,
        nominationOriginal: 'Payment - Amount: USD33.88; Merchant: MAILGUN TECHNOLOGIES,, United States of America; MCC:5734; Date: 02/09/2023 08:42; Card No: ****3035; Payment transaction amount and currency: 33.88 USD',
        productName: null,
        prodGroup: 'PLC',
        entryType: 'TRN',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'PAYMENT',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: 'P',
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        gifUrl: null,
        gifId: null,
        authDate: 1693598400000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: true,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623083&hashCode=DD5F6CD11009BB54294BF433E9AEA0C5',
        benefProfilePicture: null,
        operationTitle: 'MAILGUN TECHNOLOGIES,, United States of America',
        entryDetailType: null,
        pfmId: 8785310918,
        pfmForecast: false,
        pfmCatId: 380,
        pfmCatName: null,
        pfmParentCatId: 300,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      {
        hold: false,
        date: new Date('2023-09-02T07:42:00+03:00'),
        movements: [
          {
            id: '52795765971',
            account: { id: '1338' },
            invoice: { instrument: 'USD', sum: -33.88 },
            sum: -33.88,
            fee: 0
          }
        ],
        merchant: {
          country: null,
          city: null,
          title: 'MAILGUN TECHNOLOGIES',
          mcc: 5734,
          location: null
        },
        comment: null
      }
    ]
  ])('converts purchase accountUsd', (apiTransaction, transaction) => {
    expect(convertTransaction(apiTransaction, accountUsd)).toEqual(transaction)
  })
})
