import { convertTransaction } from '../../../converters'
import { accountGel, accountUsd } from '../../../tests-common/accounts'

describe('convertTransaction', () => {
  it.each([
    [
      {
        statmentId: 28671901118,
        acctKey: 11570661145,
        entryId: 49706961903,
        docKey: 12979175436,
        essId: null,
        nomination: 'Incoming Transfer - Amount: GEL50.00; Sender: anton antonov, RU,754991234; Account: GE55TB7489445064400001; Bank: JSC TBC Bank TBCBGE22; Details: pay',
        entryGroup: null,
        merchantId: null,
        postDate: 1649016000000,
        authDateStr: null,
        inpSysdate: 1649054322000,
        operationDate: 1649016000000,
        amount: -50,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: 'pay',
        beneficiary: 'anton antonov, RU,754991234',
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: -50,
        entryGroupDKey: 'text.entry.group.name.Income',
        entryGroupDValue: null,
        entryGroupNameId: 5,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623078,
        nominationOriginal: 'Incoming Transfer - Amount: GEL50.00; Sender: anton antonov, RU,754991234; Account: GE55TB7489445064400001; Bank: JSC TBC Bank TBCBGE22; Details: pay',
        productName: null,
        prodGroup: 'PMD',
        entryType: 'PMD',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'IN_TRANSFER',
        hasTransferBack: 'Y',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: 'TBCBGE22',
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623078&hashCode=DE3E0F781F86C1E3C9652CBF00F43784',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623078&hashCode=DE3E0F781F86C1E3C9652CBF00F43784',
        benefProfilePicture: null,
        operationTitle: 'anton antonov, RU,754991234',
        entryDetailType: null,
        pfmId: 4743092543,
        pfmForecast: false,
        pfmCatId: 900,
        pfmCatName: null,
        pfmParentCatId: 840,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: false,
        isCarTemplateAllowed: false
      },
      accountGel,
      {
        comment: 'pay',
        date: new Date('2022-04-04T10:38:42.000+04:00'),
        hold: false,
        merchant: {
          country: null,
          city: null,
          title: 'anton antonov, RU,754991234',
          location: null,
          mcc: null
        },
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '28671901118',
            invoice: null,
            sum: 50
          },
          {
            account: {
              company: null,
              instrument: 'GEL',
              syncIds: null,
              type: 'ccard'
            },
            fee: 0,
            id: null,
            invoice: null,
            sum: -50
          }
        ],
        groupKeys: [
          '12979175436'
        ]
      }
    ],
    [
      {
        statmentId: 28556039565,
        acctKey: 11570661145,
        entryId: 49606046063,
        docKey: 12948761956,
        essId: null,
        nomination: 'Outgoing Transfer - Amount: GEL10.00; Beneficiary: ANTONOV ANTON; Account: GE02BG0000000528336203GEL; Bank: JSC Bank of Georgia BAGAGE22; Details: Private transfer',
        entryGroup: null,
        merchantId: null,
        postDate: 1648670400000,
        authDateStr: null,
        inpSysdate: 1648719107000,
        operationDate: 1648670400000,
        amount: 10,
        oppositeAmount: null,
        ccy: 'GEL',
        clientComment: null,
        canCopy: 'Y',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: 'Private transfer',
        beneficiary: 'ANTONOV ANTON',
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 10,
        entryGroupDKey: 'text.entry.group.name.Transfer',
        entryGroupDValue: null,
        entryGroupNameId: 6,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623084,
        nominationOriginal: 'Outgoing Transfer - Amount: GEL10.00; Beneficiary: ANTONOV ANTON; Account: GE02BG0000000528336203GEL; Bank: JSC Bank of Georgia BAGAGE22; Details: Private transfer',
        productName: null,
        prodGroup: 'PMD',
        entryType: 'PMD',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'OUT_TRANSFER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: 'BAGAGE22',
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: true,
        isTemplateAllowed: false,
        isDDSTOAlllowed: true,
        isStatementAllowed: true,
        isPrintAllowed: true,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623084&hashCode=F87F8788EE5FCD976B8E8D01B3ACC654',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623084&hashCode=F87F8788EE5FCD976B8E8D01B3ACC654',
        benefProfilePicture: null,
        operationTitle: 'ANTONOV ANTON',
        entryDetailType: null,
        pfmId: null,
        pfmForecast: null,
        pfmCatId: null,
        pfmCatName: null,
        pfmParentCatId: null,
        pfmParentCatName: null,
        pfmRecurring: null,
        pfmSplit: null,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: null,
        isRuleCreationEnabled: null,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      accountGel,
      {
        comment: 'Private transfer',
        date: new Date('2022-03-31T13:31:47.000+04:00'),
        hold: false,
        merchant: {
          country: null,
          city: null,
          title: 'ANTONOV ANTON',
          location: null,
          mcc: null
        },
        movements: [
          {
            account: {
              id: '1337'
            },
            fee: 0,
            id: '28556039565',
            invoice: null,
            sum: -10
          },
          {
            account: {
              company: null,
              instrument: 'GEL',
              syncIds: null,
              type: 'ccard'
            },
            fee: 0,
            id: null,
            invoice: null,
            sum: 10
          }
        ],
        groupKeys: [
          '12948761956'
        ]
      }
    ],
    [
      {
        statmentId: 31247275352,
        acctKey: 11572826802,
        entryId: 51619971787,
        docKey: 13549206345,
        essId: null,
        nomination: 'Incoming Transfer - Amount: USD12,540.00; Sender: KAVYOS CONSULTING INC.\\485 C ROUTE 1 SOUTH STE 320\\ISELIN NJ 08830; Account: 9760234853; Bank: LAKELAND BANK\\250 OAK RIDGE ROAD\\OAK RIDGE NJ 07438-8906',
        entryGroup: null,
        merchantId: null,
        postDate: 1654804800000,
        authDateStr: null,
        inpSysdate: 1654869753000,
        operationDate: 1654804800000,
        amount: -12540,
        oppositeAmount: null,
        ccy: 'USD',
        clientComment: null,
        canCopy: 'N',
        status: 'A',
        groupDescription: null,
        groupType: null,
        docNomination: null,
        beneficiary: 'KAVYOS CONSULTING INC.\\485 C ROUTE 1 SOUTH STE 320\\ISELIN NJ 08830',
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: -37227.5,
        entryGroupDKey: 'text.entry.group.name.Income',
        entryGroupDValue: null,
        entryGroupNameId: 5,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623078,
        nominationOriginal: 'Incoming Transfer - Amount: USD12,540.00; Sender: KAVYOS CONSULTING INC.\\485 C ROUTE 1 SOUTH STE 320\\ISELIN NJ 08830; Account: 9760234853; Bank: LAKELAND BANK\\250 OAK RIDGE ROAD\\OAK RIDGE NJ 07438-8906',
        productName: null,
        prodGroup: 'PMI',
        entryType: 'PMI',
        printSwift: 'Y',
        isPrintable: 'Y',
        printFormType: 'IN_TRANSFER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: 'Y',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623078&hashCode=DE3E0F781F86C1E3C9652CBF00F43784',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623078&hashCode=DE3E0F781F86C1E3C9652CBF00F43784',
        benefProfilePicture: null,
        operationTitle: 'KAVYOS CONSULTING INC.\\485 C ROUTE 1 SOUTH STE 320\\ISELIN NJ 08830',
        entryDetailType: null,
        pfmId: 5230286972,
        pfmForecast: false,
        pfmCatId: 900,
        pfmCatName: null,
        pfmParentCatId: 840,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: true,
        canSplit: false,
        isCarTemplateAllowed: false
      },
      accountUsd,
      {
        comment: null,
        date: new Date('2022-06-10T14:02:33.000Z'),
        hold: false,
        merchant: {
          country: null,
          city: null,
          title: 'KAVYOS CONSULTING INC.\\485 C ROUTE 1 SOUTH STE 320\\ISELIN NJ 08830',
          location: null,
          mcc: null
        },
        movements: [
          {
            account: { id: '1338' },
            fee: 0,
            id: '31247275352',
            invoice: null,
            sum: 12540
          },
          {
            account: {
              company: null,
              instrument: 'USD',
              syncIds: null,
              type: 'ccard'
            },
            fee: 0,
            id: null,
            invoice: null,
            sum: -12540
          }
        ],
        groupKeys: [
          '13549206345'
        ]
      }
    ],
    [
      {
        statmentId: 28054896088,
        acctKey: 11570838920,
        entryId: 49226052703,
        docKey: 12843289926,
        essId: null,
        nomination: 'Cash withdrawal - Amount: USD3,890.00; Recipient: ANTON ANTONOV; Details: tankhis gatana',
        entryGroup: null,
        merchantId: null,
        postDate: 1647374400000,
        authDateStr: null,
        inpSysdate: 1647434960000,
        operationDate: 1647374400000,
        amount: 3890,
        oppositeAmount: null,
        ccy: 'USD',
        clientComment: null,
        canCopy: 'N',
        status: 'P',
        groupDescription: null,
        groupType: null,
        docNomination: 'tankhis gatana',
        beneficiary: 'ANTON ANTONOV',
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 12517.24,
        entryGroupDKey: 'text.entry.group.name.widthroval',
        entryGroupDValue: null,
        entryGroupNameId: 1,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623075,
        nominationOriginal: 'Cash withdrawal - Amount: USD3,890.00; Recipient: ANTON ANTONOV; Details: tankhis gatana',
        productName: null,
        prodGroup: 'PMC',
        entryType: 'PMC',
        printSwift: 'N',
        isPrintable: 'N',
        printFormType: 'OTHER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: 'N',
        counterPartyClientKey: null,
        authDate: null,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623075&hashCode=D2617C8163F094FEA7E491FC27535EFA',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623075&hashCode=D2617C8163F094FEA7E491FC27535EFA',
        benefProfilePicture: null,
        operationTitle: 'ANTON ANTONOV',
        entryDetailType: null,
        pfmId: 4618152079,
        pfmForecast: false,
        pfmCatId: 600,
        pfmCatName: null,
        pfmParentCatId: 590,
        pfmParentCatName: null,
        pfmRecurring: false,
        pfmSplit: false,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: true,
        isRuleCreationEnabled: false,
        canSplit: false,
        isCarTemplateAllowed: false
      },
      accountUsd,
      {
        date: new Date('2022-03-16T12:49:20.000Z'),
        hold: false,
        movements: [
          {
            account: { id: '1338' },
            fee: 0,
            id: '28054896088',
            invoice: null,
            sum: -3890
          },
          {
            account: {
              company: null,
              instrument: 'USD',
              syncIds: null,
              type: 'cash'
            },
            fee: 0,
            id: null,
            invoice: null,
            sum: 3890
          }
        ],
        merchant: {
          country: null,
          city: null,
          title: 'ANTON ANTONOV',
          location: null,
          mcc: null
        },
        comment: null
      }
    ],
    [
      {
        statmentId: 14027011598,
        acctKey: 11573059596,
        entryId: 14027011598,
        docKey: 14027011598,
        essId: null,
        nomination: 'Private Transfer',
        entryGroup: null,
        merchantId: null,
        postDate: 1659297600000,
        authDateStr: '01/08/2022',
        inpSysdate: 1659351931000,
        operationDate: 1659297600000,
        amount: 600,
        oppositeAmount: null,
        ccy: 'USD',
        clientComment: null,
        canCopy: 'N',
        status: 'F',
        groupDescription: null,
        groupType: null,
        docNomination: 'Private Transfer',
        beneficiary: null,
        bonusPoint: null,
        merchantName: null,
        merchantNameInt: null,
        amountBase: 1659.12,
        entryGroupDKey: 'text.entry.group.name.Transfer',
        entryGroupDValue: null,
        entryGroupNameId: 6,
        bonusInfo: null,
        essServiceId: null,
        merchantClientId: null,
        cashbackAmount: null,
        groupImageId: 35623084,
        nominationOriginal: 'Private Transfer',
        productName: null,
        prodGroup: 'PMI',
        entryType: 'PMI',
        printSwift: 'N',
        isPrintable: 'Y',
        printFormType: 'OUT_TRANSFER',
        hasTransferBack: 'N',
        benefProfileId: null,
        positiveSum: null,
        negativeSum: null,
        isInternalOperation: 'N',
        transferBankBic: null,
        deviceType: null,
        swiftGpiFlag: null,
        counterPartyClientKey: null,
        authDate: 1659297600000,
        bonusPointType: null,
        attachmentFileBase64: null,
        isRepeatAllowed: false,
        isTemplateAllowed: false,
        isDDSTOAlllowed: false,
        isStatementAllowed: true,
        isPrintAllowed: false,
        isReversalAvailable: false,
        entryIconBase64: null,
        merchantIconBase64: null,
        providerIconUrl: null,
        groupImageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623084&hashCode=F87F8788EE5FCD976B8E8D01B3ACC654',
        imageUrl: 'serviceId=COMMON_GET_FILE&channel=MOBILE&id=35623084&hashCode=F87F8788EE5FCD976B8E8D01B3ACC654',
        benefProfilePicture: null,
        operationTitle: 'Private Transfer',
        entryDetailType: null,
        pfmId: null,
        pfmForecast: null,
        pfmCatId: null,
        pfmCatName: null,
        pfmParentCatId: null,
        pfmParentCatName: null,
        pfmRecurring: null,
        pfmSplit: null,
        pfmParentOpId: null,
        pfmTagId: null,
        pfmTagName: null,
        pfmTags: null,
        pfmComputable: null,
        isRuleCreationEnabled: null,
        canSplit: true,
        isCarTemplateAllowed: false
      },
      accountUsd,
      {
        date: new Date('2022-08-01T15:05:31+04:00'),
        hold: true,
        movements: [
          {
            account: { id: '1338' },
            fee: 0,
            id: '14027011598',
            invoice: null,
            sum: -600
          },
          {
            account: {
              company: null,
              instrument: 'USD',
              syncIds: null,
              type: 'ccard'
            },
            fee: 0,
            id: null,
            invoice: null,
            sum: 600
          }
        ],
        merchant: null,
        comment: 'Private Transfer'
      }
    ]
  ])('converts transfer', (apiTransaction, account, transaction) => {
    expect(convertTransaction(apiTransaction, account)).toEqual(transaction)
  })
})
