import { convertTransactions } from '../../../converters'

describe('convertTransaction', () => {
  it.each([
    [
      [
        {
          CurrencyCode: 'EUR',
          ID: -1,
          TransactionID: '12366693649181#4#81#374599481466', // '<string[32]>', // id:
          ProcessedDate: '2025-01-06T00:00:00',
          CurrentBalance: null,
          CurrencyCodeNumeric: 978,
          ChequeCardNumber: '405477******7026',
          fwStatus: 1,
          ClientDescription: 'Dinarsko knjigovodstvo',
          ToDate: '2025-03-25T00:00:00',
          CreditAmount: 0,
          TransactionBeneficiary: 'bankomat',
          fwNamespace: 'SagaBG.SeP.RetailOutput',
          BeneficiaryAccount: null,
          IBANNumber: '<string[22]>',
          ClientAddress: '<string[12]>',
          SocialIdentityNumber: '<string[13]>',
          DebitAmount: 178.41,
          PreviousBalance: null,
          Reference: '<string[12]>',
          AccountNumber: '265050000065879810', // '<string[18]>',
          SalesAgreementNumber: null,
          FromDate: '2024-12-31T00:00:00',
          Description: 'BANGKOK BANK THA CHIANGMAI',
          ClientLocality: '11050 BEOGRAD-VRAČAR',
          Note: '<string[6]>',
          ValueDate: '2025-01-06T00:00:00',
          ComplaintNumber: '<string[20]>',
          TransactionType: 'ATM',
          // IsInvestOrder: false,
          ProductCodeCore: 25,
          AmountTotal: null,
          ClientName: '<string[13]>',
          fwType: 'aoRetailAccountTurnoverPreview',
          Details: {
            e_UserLocality: null,
            ReceiveDate: null,
            fwType: 'aoFullTransactionDetails',
            m_PayDeskNumber: null,
            CurrencyCodeNumeric: null,
            p2p_Message: null,
            p2p_Status: null,
            s_Alias: null,
            m_UserGroup: null,
            Alias: null,
            dev_cred_bank_address_postal: null,
            e_UserName: null,
            c_Alias: null,
            m_ExchangeOfficeLocality: null,
            dev_Status: null,
            DebtorName: null,
            c_TerminalID: 'T092B523',
            m_Basics: null,
            p2p_CurrencyCodeNumeric: null,
            ValueDate: null,
            s_Note_st: '123456',
            UserName: null,
            dev_cred_bank_address_locality: null,
            m_DebtorCurrencyCode: null,
            m_CommissionCurrencyCode: null,
            DebtorAddress: null,
            m_UserCurrencyCode: null,
            PaymentPurpose: null,
            dev_Charge: null,
            dev_ComissionAccount: null,
            m_UserCurrencyCodeNumeric: null,
            e_ID: null,
            s_AccountPurpose: 'A vista računi fizičkih lica u stranoj valuti',
            p2p_PaymentCode: null,
            dev_cred_bank_address_country: null,
            m_TransactionID: null,
            m_AmountTotal: null,
            iBankingCreditorTypeFRN: null,
            dev_cred_bank_address_line: null,
            m_Course: null,
            dev_cred_address_locality: null,
            m_DebtorCurrencyCodeNumeric: null,
            m_OrderNumber: null,
            m_CommissionPercentage: null,
            fwNamespace: 'SagaBG.SeP.RetailOutput',
            p2p_RealizationDate: null,
            mpay_payment_type: null,
            e_UserAlias: null,
            s_StatementID: 379534387835,
            fwStatus: 1,
            iBankingProcessedDateCoreFRN: null,
            p2p_ExpiryDate: null,
            ReceiverReference: null,
            p2p_CreateDate: null,
            c_DebtorDetails: 'BANGKOK BANK THA CHIANGMAI',
            m_ExchangeNumber: null,
            s_ValueDate: '2025-01-06T00:00:00',
            dev_SwiftMessage: null,
            PaymentStatusName: null,
            DebtorLocality: null,
            m_JobType: null,
            PaymentState: null,
            dev_SpecAmount: null,
            c_Date_tx: '2025-01-04T00:00:00',
            dev_SpecCurrency: null,
            tn_ValueDate: null,
            c_DomesticAmount: 21166.20558,
            Priority: null,
            dev_SpecInvoiceNumber: null,
            e_DebtorAccount: null,
            m_CommissionCurrencyCodeNumeric: null,
            c_Amount_tx: 6220,
            m_UserID: null,
            m_UserName: null,
            dev_CreditorAddressCountry: null,
            m_UserType: null,
            s_ProcessedDate: '2025-01-06T00:00:00',
            m_Operator: null,
            ID: -1,
            s_Amount: 178.41,
            s_ConfirmationDate: '2025-01-07T08:19:46',
            m_UserAlias: null,
            dev_SpecPurposeCode: null,
            dev_SpecInvoiceYear: null,
            e_Channel: null,
            s_PaymentBasis: 894,
            s_CurrencyCode: 'EUR',
            m_BankLocality: null,
            c_CalculationDate: '2025-01-06T00:00:00',
            PaymentCode: null,
            m_CommissionAmount: null,
            tn_Description: null,
            CommissionCurrencyCodeNumeric: null,
            OrderNumber_pp: null,
            m_DebtorGroup: null,
            m_DebtorAlias: null,
            UserAddress: null,
            DebtorAccount: null,
            m_JobDescription: null,
            p2p_Alias: null,
            dev_creditor_bank: null,
            UserAccount: null,
            m_ExchangeName: null,
            Reference: null,
            CommissionCurrencyCode: null,
            p2p_IssueDate: null,
            End2endID: null,
            m_DebtorName: null,
            c_Reference: 374599481466,
            s_OrderNumber: '<string[14]>',
            dev_CreditorBankSwiftCode: null,
            PaymentAmount: null,
            mpay_merchant_code: null,
            // IsInvestOrder: false,
            dev_PersonalNumber: null,
            m_DebtorID: null,
            p2p_CurrencyCode: null,
            e_UserAccount: null,
            mpay_sales_point_code: null,
            Model: null,
            m_UserAmount: null,
            c_CardNumber: '405477******7026',
            CommissionAmount: null,
            dev_cred_address_postal_code: null,
            dev_SpecialMark: null,
            s_Group: '265050000065879810', // '<string[18]>',
            dev_cred_address_line: null,
            m_Date: null,
            CurrencyCode: null,
            UserLocality: null,
            p2p_Amount: null,
            e_DebtorName: null,
            s_CurrencyCodeNumeric: 978,
            dev_BulkId: null,
            p2p_DebtorGroup: null,
            e_DebtorAlias: null,
            dev_AuthorizationType: null,
            c_CurrencyCode_tx: 'THB',
            dev_SpecPaymentDescription: null,
            c_AuthorizationID: '193251',
            m_DebtorAmount: null,
            e_DebtorLocality: null
          }
        }
      ],
      [
        {
          date: new Date('2025-01-04T00:00:00'),
          hold: false,
          merchant: {
            fullTitle: 'BANGKOK BANK THA CHIANGMAI',
            location: null,
            mcc: null
          },
          movements: [
            {
              account: { id: '265050000065879810EUR' },
              fee: 0,
              id: '12366693649181#4#81#374599481466',
              invoice: { instrument: 'THB', sum: -6220 },
              sum: -178.41
            },
            {
              account: {
                company: null,
                instrument: 'THB',
                syncIds: null,
                type: 'cash'
              },
              fee: 0,
              id: '12366693649181#4#81#374599481466',
              invoice: null,
              sum: 6220
            }
          ],
          comment: '123456'
        }
      ]
    ]
  ])('converts cash withdrawal', (apiTransactions, transactions) => {
    expect(convertTransactions(apiTransactions)).toEqual(transactions)
  })
})

/*
import { convertTransaction, postProcessTransactions } from '../../../../converters/transactions'
import { card } from '../../../../test-common/commonAccounts'

it.each([
  {
  }
])('convert ExtCardCashIn',
  ({ cardOperation, details, result }) => {
    const cardOp = convertTransaction({ type: 'ExtCardCashIn', data: cardOperation, details }, card)
    expect(postProcessTransactions([cardOp], [card.account])).toEqual(result)
  })
*/
