import { convertTransaction } from '../../../converters'

describe('income transactions', () => {
  it('Income-1', () => {
    expect(convertTransaction({
      CurrencyCode: 'EUR',
      ID: -1,
      TransactionID: '10822637459181#3#81#336730037740',
      ProcessedDate: '2024-05-13T00:00:00',
      CurrentBalance: null,
      CurrencyCodeNumeric: 978,
      ChequeCardNumber: '402323******9476',
      fwStatus: 1,
      ClientDescription: 'Dinarsko knjigovodstvo',
      ToDate: '2024-05-17T00:00:00',
      CreditAmount: 0.02,
      TransactionBeneficiary: 'JP DRZAVNI PATISTA MKD SKOPJE',
      fwNamespace: 'SagaBG.SeP.RetailOutput',
      IBANNumber: '<string[22]>',
      ClientAddress: '<string[8]>',
      SocialIdentityNumber: '<string[13]>',
      DebitAmount: 0,
      PreviousBalance: null,
      Reference: '<string[12]>',
      AccountNumber: '265022000008421126',
      SalesAgreementNumber: null,
      FromDate: '2024-05-02T00:00:00',
      Description: 'JP DRZAVNI PATISTA MKD SKOPJE',
      ClientLocality: '11050 BEOGRAD-ZVEZDARA',
      Note: '<string[6]>',
      ValueDate: '2024-05-13T00:00:00',
      ComplaintNumber: '<string[20]>',
      TransactionType: 'Income',
      BeneficiaryAccount: null,
      ProductCodeCore: 25,
      AmountTotal: null,
      ClientName: '<string[16]>',
      fwType: 'aoRetailAccountTurnoverPreview',
      Details: {
        mpay_merchant_code: null,
        CommissionCurrencyCode: null,
        p2p_Message: null,
        e_UserName: null,
        tn_Description: null,
        fwType: 'aoFullTransactionDetails',
        p2p_ExpiryDate: null,
        dev_cred_bank_address_locality: null,
        e_DebtorName: null,
        s_Note_st: 'JP DRZAVNI PATISTA MKD SKOPJE',
        m_Date: null,
        DebtorAddress: null,
        c_CurrencyCode_tx: 'MKD',
        c_CalculationDate: '2024-05-13T00:00:00',
        dev_cred_address_locality: null,
        DebtorLocality: null,
        dev_Charge: null,
        Reference: null,
        c_CardNumber: '402323******9476',
        m_CommissionAmount: null,
        s_ValueDate: '2024-05-13T00:00:00',
        m_DebtorCurrencyCodeNumeric: null,
        dev_CreditorAddressCountry: null,
        UserAccount: '<value>',
        p2p_DebtorGroup: null,
        m_DebtorAmount: null,
        p2p_CurrencyCodeNumeric: null,
        CommissionAmount: null,
        m_UserCurrencyCode: null,
        p2p_PaymentCode: null,
        e_DebtorAlias: null,
        mpay_payment_type: null,
        p2p_CurrencyCode: null,
        p2p_RealizationDate: null,
        m_BankLocality: null,
        UserAddress: null,
        CurrencyCodeNumeric: null,
        m_UserID: null,
        Model: null,
        s_ProcessedDate: '2024-05-13T00:00:00',
        fwNamespace: 'SagaBG.SeP.RetailOutput',
        Alias: null,
        Priority: null,
        s_CurrencyCodeNumeric: 978,
        c_DomesticAmount: 2.372846,
        e_DebtorAccount: null,
        s_OrderNumber: '<string[14]>',
        m_JobDescription: null,
        m_AmountTotal: null,
        m_UserAmount: null,
        CurrencyCode: null,
        ReceiveDate: null,
        m_DebtorName: null,
        ValueDate: null,
        e_UserAlias: null,
        c_TerminalID: 'VP000680',
        s_StatementID: null,
        e_Channel: null,
        DebtorAccount: '<value>',
        e_ID: null,
        e_UserLocality: null,
        dev_SpecAmount: null,
        p2p_CreateDate: null,
        ID: -1,
        m_DebtorCurrencyCode: null,
        m_CommissionPercentage: null,
        dev_cred_address_postal_code: null,
        DebtorName: null,
        m_DebtorGroup: null,
        dev_SpecCurrency: null,
        fwStatus: 1,
        m_ExchangeNumber: null,
        dev_cred_bank_address_postal: null,
        m_UserAlias: null,
        e_DebtorLocality: null,
        m_PayDeskNumber: null,
        dev_cred_address_line: null,
        dev_SpecPurposeCode: null,
        c_DebtorDetails: 'JP DRZAVNI PATISTA MKD SKOPJE',
        PaymentAmount: null,
        p2p_Amount: null,
        CommissionCurrencyCodeNumeric: null,
        m_JobType: null,
        OrderNumber_pp: '<value>',
        dev_BulkId: null,
        ReceiverReference: null,
        iBankingCreditorTypeFRN: null,
        m_DebtorAlias: null,
        m_CommissionCurrencyCodeNumeric: null,
        UserLocality: null,
        c_AuthorizationID: '513523',
        s_CurrencyCode: 'EUR',
        m_Course: null,
        dev_PersonalNumber: null,
        dev_SpecInvoiceYear: null,
        tn_ValueDate: null,
        m_Basics: null,
        e_UserAccount: null,
        mpay_sales_point_code: null,
        s_AccountPurpose: 'A vista računi fizičkih lica u stranoj valuti',
        c_Reference: 336730037740,
        dev_cred_bank_address_line: null,
        PaymentCode: null,
        s_Alias: null,
        PaymentStatusName: null,
        dev_cred_bank_address_country: null,
        dev_SpecPaymentDescription: null,
        s_PaymentBasis: 894,
        End2endID: null,
        s_Group: '<string[18]>',
        m_TransactionID: null,
        p2p_Alias: null,
        m_DebtorID: null,
        iBankingProcessedDateCoreFRN: null,
        c_Date_tx: '2024-05-10T00:00:00',
        PaymentPurpose: null,
        c_Alias: null,
        s_ConfirmationDate: '2024-05-14T08:57:09',
        dev_creditor_bank: null,
        m_UserGroup: null,
        m_UserName: null,
        dev_SpecialMark: null,
        UserName: '<value>',
        m_CommissionCurrencyCode: null,
        dev_CreditorBankSwiftCode: null,
        m_ExchangeName: null,
        dev_SwiftMessage: null,
        PaymentState: null,
        s_Amount: 0.02,
        dev_Status: null,
        p2p_Status: null,
        m_Operator: null,
        m_UserCurrencyCodeNumeric: null,
        p2p_IssueDate: null,
        dev_AuthorizationType: null,
        dev_ComissionAccount: null,
        m_OrderNumber: null,
        m_UserType: null,
        c_Amount_tx: 1,
        dev_SpecInvoiceNumber: null,
        m_ExchangeOfficeLocality: null
      }
    })).toEqual({
      hold: false,
      date: new Date('2024-05-10T00:00:00'),
      movements: [
        {
          id: '10822637459181#3#81#336730037740',
          account: { id: '265022000008421126EUR' },
          invoice: {
            sum: 1,
            instrument: 'MKD'
          },
          sum: 0.02,
          fee: 0
        }
      ],
      merchant: {
        fullTitle: 'JP DRZAVNI PATISTA MKD SKOPJE',
        mcc: null,
        location: null
      },
      comment: null
    })
  })

  it('Income-2', () => {
    expect(convertTransaction({
      CurrencyCode: 'EUR',
      ID: -1,
      TransactionID: '11447445629181#3#81#351642627617',
      ProcessedDate: '2024-08-23T00:00:00',
      CurrentBalance: null,
      CurrencyCodeNumeric: 978,
      ChequeCardNumber: '402323******9476',
      fwStatus: 1,
      ClientDescription: 'Dinarsko knjigovodstvo',
      ToDate: '2024-08-27T00:00:00',
      CreditAmount: 1.55,
      TransactionBeneficiary: 'aliexpress LUX Luxembourg',
      fwNamespace: 'SagaBG.SeP.RetailOutput',
      IBANNumber: '<string[22]>',
      ClientAddress: '<string[8]>',
      SocialIdentityNumber: '<string[13]>',
      DebitAmount: 0,
      PreviousBalance: null,
      Reference: '<string[12]>',
      AccountNumber: '265022000008421126',
      SalesAgreementNumber: null,
      FromDate: '2024-08-13T00:00:00',
      Description: 'aliexpress LUX Luxembourg',
      ClientLocality: '11050 BEOGRAD-ZVEZDARA',
      Note: '<string[6]>',
      ValueDate: '2024-08-23T00:00:00',
      ComplaintNumber: '<string[20]>',
      TransactionType: 'Income',
      BeneficiaryAccount: null,
      ProductCodeCore: 25,
      AmountTotal: null,
      ClientName: '<string[16]>',
      fwType: 'aoRetailAccountTurnoverPreview',
      Details: {
        mpay_merchant_code: null,
        CommissionCurrencyCode: null,
        p2p_Message: null,
        e_UserName: null,
        tn_Description: null,
        fwType: 'aoFullTransactionDetails',
        p2p_ExpiryDate: null,
        dev_cred_bank_address_locality: null,
        e_DebtorName: null,
        s_Note_st: 'aliexpress LUX Luxembourg',
        m_Date: null,
        DebtorAddress: null,
        c_CurrencyCode_tx: 'USD',
        c_CalculationDate: '2024-08-23T00:00:00',
        dev_cred_address_locality: null,
        DebtorLocality: null,
        dev_Charge: null,
        Reference: null,
        c_CardNumber: '402323******9476',
        m_CommissionAmount: null,
        s_ValueDate: '2024-08-23T00:00:00',
        m_DebtorCurrencyCodeNumeric: null,
        dev_CreditorAddressCountry: null,
        UserAccount: '<value>',
        p2p_DebtorGroup: null,
        m_DebtorAmount: null,
        p2p_CurrencyCodeNumeric: null,
        CommissionAmount: null,
        m_UserCurrencyCode: null,
        p2p_PaymentCode: null,
        e_DebtorAlias: null,
        mpay_payment_type: null,
        p2p_CurrencyCode: null,
        p2p_RealizationDate: null,
        m_BankLocality: null,
        UserAddress: null,
        CurrencyCodeNumeric: null,
        m_UserID: null,
        Model: null,
        s_ProcessedDate: '2024-08-23T00:00:00',
        fwNamespace: 'SagaBG.SeP.RetailOutput',
        Alias: null,
        Priority: null,
        s_CurrencyCodeNumeric: 978,
        c_DomesticAmount: 183.797295,
        e_DebtorAccount: null,
        s_OrderNumber: '<string[14]>',
        m_JobDescription: null,
        m_AmountTotal: null,
        m_UserAmount: null,
        CurrencyCode: null,
        ReceiveDate: null,
        m_DebtorName: null,
        ValueDate: null,
        e_UserAlias: null,
        c_TerminalID: null,
        s_StatementID: null,
        e_Channel: null,
        DebtorAccount: '<value>',
        e_ID: null,
        e_UserLocality: null,
        dev_SpecAmount: null,
        p2p_CreateDate: null,
        ID: -1,
        m_DebtorCurrencyCode: null,
        m_CommissionPercentage: null,
        dev_cred_address_postal_code: null,
        DebtorName: null,
        m_DebtorGroup: null,
        dev_SpecCurrency: null,
        fwStatus: 1,
        m_ExchangeNumber: null,
        dev_cred_bank_address_postal: null,
        m_UserAlias: null,
        e_DebtorLocality: null,
        m_PayDeskNumber: null,
        dev_cred_address_line: null,
        dev_SpecPurposeCode: null,
        c_DebtorDetails: 'aliexpress LUX Luxembourg',
        PaymentAmount: null,
        p2p_Amount: null,
        CommissionCurrencyCodeNumeric: null,
        m_JobType: null,
        OrderNumber_pp: '<value>',
        dev_BulkId: null,
        ReceiverReference: null,
        iBankingCreditorTypeFRN: null,
        m_DebtorAlias: null,
        m_CommissionCurrencyCodeNumeric: null,
        UserLocality: null,
        c_AuthorizationID: '513637',
        s_CurrencyCode: 'EUR',
        m_Course: null,
        dev_PersonalNumber: null,
        dev_SpecInvoiceYear: null,
        tn_ValueDate: null,
        m_Basics: null,
        e_UserAccount: null,
        mpay_sales_point_code: null,
        s_AccountPurpose: 'A vista računi fizičkih lica u stranoj valuti',
        c_Reference: 351642627617,
        dev_cred_bank_address_line: null,
        PaymentCode: null,
        s_Alias: null,
        PaymentStatusName: null,
        dev_cred_bank_address_country: null,
        dev_SpecPaymentDescription: null,
        s_PaymentBasis: 894,
        End2endID: null,
        s_Group: '<string[18]>',
        m_TransactionID: null,
        p2p_Alias: null,
        m_DebtorID: null,
        iBankingProcessedDateCoreFRN: null,
        c_Date_tx: '2024-05-24T00:00:00',
        PaymentPurpose: null,
        c_Alias: null,
        s_ConfirmationDate: '2024-08-24T09:37:27',
        dev_creditor_bank: null,
        m_UserGroup: null,
        m_UserName: null,
        dev_SpecialMark: null,
        UserName: '<value>',
        m_CommissionCurrencyCode: null,
        dev_CreditorBankSwiftCode: null,
        m_ExchangeName: null,
        dev_SwiftMessage: null,
        PaymentState: null,
        s_Amount: 1.55,
        dev_Status: null,
        p2p_Status: null,
        m_Operator: null,
        m_UserCurrencyCodeNumeric: null,
        p2p_IssueDate: null,
        dev_AuthorizationType: null,
        dev_ComissionAccount: null,
        m_OrderNumber: null,
        m_UserType: null,
        c_Amount_tx: 1.75,
        dev_SpecInvoiceNumber: null,
        m_ExchangeOfficeLocality: null
      }
    })).toEqual({
      hold: false,
      date: new Date('2024-05-24T00:00:00'),
      movements: [
        {
          id: '11447445629181#3#81#351642627617',
          account: { id: '265022000008421126EUR' },
          invoice: { sum: 1.75, instrument: 'USD' },
          sum: 1.55,
          fee: 0
        }
      ],
      merchant:
        {
          fullTitle: 'aliexpress LUX Luxembourg',
          mcc: null,
          location: null
        },
      comment: null
    })
  })
})
