import { convertCashTransaction } from '../../../converters'

describe('Account topup', () => {
  it('Account topup', () => {
    expect(convertCashTransaction({
      CurrencyCode: 'USD',
      ID: -1,
      TransactionID: '10152214197777#2#81#320042687777',
      ProcessedDate: '2023-12-30T00:00:00',
      CurrentBalance: null,
      CurrencyCodeNumeric: 840,
      ChequeCardNumber: null,
      fwStatus: 1,
      ClientDescription: 'Dinarsko knjigovodstvo',
      ToDate: '2024-01-25T00:00:00',
      CreditAmount: 10000.0,
      TransactionBeneficiary: 'Uplata avista depozita',
      fwNamespace: 'SagaBG.SeP.RetailOutput',
      IBANNumber: 'RS35265057000005597777',
      ClientAddress: 'SECRET STREET 1',
      SocialIdentityNumber: '0803991667777',
      DebitAmount: 0.0,
      PreviousBalance: null,
      Reference: '318301527777',
      AccountNumber: '265057000005597777',
      SalesAgreementNumber: null,
      FromDate: '2023-12-18T00:00:00',
      Description: 'Uplata avista depozita',
      ClientLocality: '11172 BEOGRAD-NOVI BEOGRAD',
      Note: 'Uplata na avista devizni račun 265057000005597777 uplatilac  LUCKY MAN',
      ValueDate: '2023-12-30T00:00:00',
      ComplaintNumber: '7777233644555719000001',
      TransactionType: 'IncomeCash',
      BeneficiaryAccount: null,
      ProductCodeCore: 541,
      AmountTotal: null,
      ClientName: 'LUCKY MAN',
      fwType: 'aoRetailAccountTurnoverPreview',
      Details: {
        mpay_merchant_code: null,
        CommissionCurrencyCode: null,
        p2p_Message: null,
        e_UserName: null,
        tn_Description: null,
        fwType: 'aoFullTransactionDetails',
        p2p_ExpiryDate: null,
        dev_cred_bank_address_locality: null,
        e_DebtorName: null,
        s_Note_st: 'Uplata na avista devizni račun 265057000005597777 uplatilac  LUCKY MAN',
        m_Date: null,
        DebtorAddress: null,
        c_CurrencyCode_tx: null,
        c_CalculationDate: null,
        dev_cred_address_locality: null,
        DebtorLocality: null,
        dev_Charge: null,
        Reference: null,
        c_CardNumber: null,
        m_CommissionAmount: null,
        s_ValueDate: '2023-12-30T00:00:00',
        m_DebtorCurrencyCodeNumeric: null,
        dev_CreditorAddressCountry: null,
        UserAccount: null,
        p2p_DebtorGroup: null,
        m_DebtorAmount: null,
        p2p_CurrencyCodeNumeric: null,
        CommissionAmount: null,
        m_UserCurrencyCode: null,
        p2p_PaymentCode: null,
        e_DebtorAlias: null,
        mpay_payment_type: null,
        p2p_CurrencyCode: null,
        p2p_RealizationDate: null,
        m_BankLocality: null,
        UserAddress: null,
        CurrencyCodeNumeric: null,
        m_UserID: null,
        Model: null,
        s_ProcessedDate: '2023-12-30T00:00:00',
        fwNamespace: 'SagaBG.SeP.RetailOutput',
        Alias: null,
        Priority: null,
        s_CurrencyCodeNumeric: 840,
        c_DomesticAmount: null,
        e_DebtorAccount: null,
        s_OrderNumber: '1891233644557777',
        m_JobDescription: null,
        m_AmountTotal: null,
        m_UserAmount: null,
        CurrencyCode: null,
        ReceiveDate: null,
        m_DebtorName: null,
        ValueDate: null,
        e_UserAlias: null,
        c_TerminalID: null,
        s_StatementID: 318930207777.0,
        e_Channel: null,
        DebtorAccount: null,
        e_ID: null,
        e_UserLocality: null,
        dev_SpecAmount: null,
        p2p_CreateDate: null,
        ID: -1,
        m_DebtorCurrencyCode: null,
        m_CommissionPercentage: null,
        dev_cred_address_postal_code: null,
        DebtorName: null,
        m_DebtorGroup: null,
        dev_SpecCurrency: null,
        fwStatus: 1,
        m_ExchangeNumber: null,
        dev_cred_bank_address_postal: null,
        m_UserAlias: null,
        e_DebtorLocality: null,
        m_PayDeskNumber: null,
        dev_cred_address_line: null,
        dev_SpecPurposeCode: null,
        c_DebtorDetails: null,
        PaymentAmount: null,
        p2p_Amount: null,
        CommissionCurrencyCodeNumeric: null,
        m_JobType: null,
        OrderNumber_pp: null,
        dev_BulkId: null,
        ReceiverReference: null,
        iBankingCreditorTypeFRN: null,
        m_DebtorAlias: null,
        m_CommissionCurrencyCodeNumeric: null,
        UserLocality: null,
        c_AuthorizationID: null,
        s_CurrencyCode: 'USD',
        m_Course: null,
        dev_PersonalNumber: null,
        dev_SpecInvoiceYear: null,
        tn_ValueDate: null,
        m_Basics: null,
        e_UserAccount: null,
        mpay_sales_point_code: null,
        s_AccountPurpose: 'A vista računi fizičkih lica u stranoj valuti',
        c_Reference: null,
        dev_cred_bank_address_line: null,
        PaymentCode: null,
        s_Alias: null,
        PaymentStatusName: null,
        dev_cred_bank_address_country: null,
        dev_SpecPaymentDescription: null,
        s_PaymentBasis: 898,
        End2endID: null,
        s_Group: '265057000005597777',
        m_TransactionID: null,
        p2p_Alias: null,
        m_DebtorID: null,
        iBankingProcessedDateCoreFRN: null,
        c_Date_tx: null,
        PaymentPurpose: null,
        c_Alias: null,
        s_ConfirmationDate: '2023-12-30T14:34:07',
        dev_creditor_bank: null,
        m_UserGroup: null,
        m_UserName: null,
        dev_SpecialMark: null,
        UserName: null,
        m_CommissionCurrencyCode: null,
        dev_CreditorBankSwiftCode: null,
        m_ExchangeName: null,
        dev_SwiftMessage: null,
        PaymentState: null,
        s_Amount: 10000.0,
        dev_Status: null,
        p2p_Status: null,
        m_Operator: null,
        m_UserCurrencyCodeNumeric: null,
        p2p_IssueDate: null,
        dev_AuthorizationType: null,
        dev_ComissionAccount: null,
        m_OrderNumber: null,
        m_UserType: null,
        c_Amount_tx: null,
        dev_SpecInvoiceNumber: null,
        m_ExchangeOfficeLocality: null
      }
    })).toEqual({
      comment: 'Uplata na avista devizni račun 265057000005597777 uplatilac  LUCKY MAN',
      date: new Date('2023-12-30T00:00:00'),
      hold: false,
      merchant: {
        fullTitle: 'Uplata avista depozita',
        location: null,
        mcc: null
      },
      movements: [
        {
          account: {
            id: '265057000005597777USD'
          },
          fee: 0,
          id: '10152214197777#2#81#320042687777',
          invoice: null,
          sum: 10000
        },
        {
          account: {
            company: null,
            instrument: 'USD',
            syncIds: null,
            type: 'cash'
          },
          fee: 0,
          id: '10152214197777#2#81#320042687777',
          invoice: null,
          sum: -10000
        }]
    })
  })
})
