import { convertAccount } from '../../../converters'

describe('convertAccount', () => {
  it.each([
    [
      {
        id: '30732804',
        cardId: '1773133941',
        isCurrent: true,
        type: 'VISA',
        expdate: 1632949200,
        duration: '09/21',
        cardClass: 'type-logo_visa',
        cardImage: '/core/assets/redesign3/images/cardsLogo/visa-mini2.svg',
        corporative: 0,
        num: '**** 2226',
        cardHolder: 'ANDREI MAKAVETSKI',
        holderId: '55315895',
        accOwnerId: '55315895',
        fullNum: '434485******2226',
        cardName: 'Visa Gold',
        fixedBalance: 0,
        currency: 'BYN',
        currencyName: 'Белорусский рубль',
        blockingCode: '0',
        blocking: '',
        blockingText: '',
        balance: '3 473.46',
        international: 1,
        internet: 1,
        moneyBack: 0,
        moneyBackEdit: 0,
        msCardId: '650205',
        status3D: 1,
        statusPimp: -1,
        statusLimits: 1,
        isProlongable: 0,
        isReplaceable: 1,
        isCredit: 0,
        isBelcard: 0,
        isSendPinAllowed: 0,
        isDBO: 0,
        cardClassColor: '_type_gold',
        cardImg: 'visa-gold-chess.jpg',
        cardClassesVisual: 'newCard_type-visa-gold-chess',
        cardVisualDefault: false,
        imgPath: 'https://ibank.belinvestbank.by/core/assets/redesign3/images/cardsMobile/visa-gold-chess.png',
        isVirtual: '0',
        isCashelkoff: '0',
        isVisaVr: '0',
        isGroupPackage: '0',
        packageName: '',
        availableAmt: '3 473.46',
        overdraftAmt: '0',
        freeAmt: '3 473.46',
        commonId: 'ownBankCards_30732804',
        subTitle: '',
        finalName: 'Visa Gold',
        pimpText: 'Карта участвует в акции! Прокачайте карту - совершайте безналичные платежи!',
        widgetContent:
          [
            'js-transfer-card-card',
            'js-transfer-card-acc',
            'js-card-limits',
            'js-block-card',
            'js-rename-card',
            'js-card-history',
            'js-replace-card-info',
            'js-card-offer-block'
          ],
        cardsKey: 30732804
      },
      {
        id: '30732804',
        type: 'card',
        title: 'Visa Gold*2226',
        instrument: 'BYN',
        balance: 3473.46,
        creditLimit: 0,
        syncID: ['2226']
      }
    ],
    [
      {
        id: '30834523',
        cardId: '1828706889',
        isCurrent: false,
        type: 'VISA',
        expdate: 1640898000,
        duration: '12/21',
        cardClass: 'type-logo_visa',
        cardImage: '/core/assets/redesign3/images/cardsLogo/visa-mini2.svg',
        corporative: 1828706867,
        num: '**** 5655',
        cardHolder: 'ANDREI MAKAVETSKI',
        holderId: '55315895',
        accOwnerId: '106877621',
        fullNum: '434487******5655',
        cardName: 'Корпоративная',
        fixedBalance: 0,
        currency: 'USD',
        currencyName: 'Доллар США',
        blockingCode: '0',
        blocking: '',
        blockingText: '',
        balance: '50 975.14',
        international: 1,
        internet: 1,
        moneyBack: 0,
        moneyBackEdit: 0,
        msCardId: '2157256',
        status3D: 1,
        statusPimp: 0,
        statusLimits: 1,
        isProlongable: 0,
        isReplaceable: 0,
        isCredit: 0,
        isBelcard: 0,
        isSendPinAllowed: 0,
        isDBO: 0,
        cardClassColor: '_type_black',
        cardImg: 'visa-business-chess.jpg',
        cardClassesVisual: 'newCard_type-visa-business-chess',
        cardVisualDefault: false,
        imgPath: 'https://ibank.belinvestbank.by/core/assets/redesign3/images/cardsMobile/visa-business-chess.png',
        isVirtual: '0',
        isCashelkoff: '0',
        isVisaVr: '0',
        isGroupPackage: '0',
        packageName: '',
        availableAmt: '50 975.14',
        overdraftAmt: '0',
        freeAmt: '50 975.14',
        commonId: 'ownBankCards_30834523',
        subTitle: '',
        finalName: 'Корпоративная',
        pimpText: '',
        widgetContent:
          [
            'js-transfer-card-card',
            'js-transfer-card-acc',
            'js-card-limits',
            'js-block-card',
            'js-rename-card',
            'js-card-history'
          ],
        cardsKey: 30834523
      },
      {
        id: '30834523',
        type: 'card',
        title: 'Корпоративная*5655',
        instrument: 'USD',
        balance: 50975.14,
        creditLimit: 0,
        syncID: ['5655']
      }
    ],
    [
      {
        id: '30740546',
        cardId: '1777005128',
        isCurrent: false,
        type: 'БЕЛКАРТ-Maestro',
        expdate: 1698699600,
        duration: '10/23',
        cardClass: 'type-logo_belcard-maestro',
        cardImage: '/core/assets/redesign3/images/cardsLogo/belcard_mini2.svg',
        corporative: 0,
        num: '**** 7001',
        cardHolder: 'ANDREI MAKAVETSKI',
        holderId: '55315895',
        accOwnerId: '55315895',
        fullNum: '671127******7001',
        cardName: 'Моцная картка',
        fixedBalance: 0,
        currency: 'BYN',
        currencyName: 'Белорусский рубль',
        blockingCode: '0',
        blocking: '',
        blockingText: '',
        balance: '3 473.46',
        international: 0,
        internet: 1,
        moneyBack: 0,
        moneyBackEdit: 0,
        msCardId: '2337558',
        status3D: 0,
        statusPimp: 0,
        statusLimits: 0,
        isProlongable: 0,
        isReplaceable: 1,
        isCredit: 0,
        isBelcard: 0,
        isSendPinAllowed: 0,
        isDBO: 0,
        cardClassColor: '_type_blue',
        cardImg: 'maestro-strong.jpg',
        cardClassesVisual: 'newCard_type-maestro-strong',
        cardVisualDefault: false,
        imgPath: 'https://ibank.belinvestbank.by/core/assets/redesign3/images/cardsMobile/maestro-strong.png',
        isVirtual: '0',
        isCashelkoff: '0',
        isVisaVr: '0',
        isGroupPackage: '0',
        packageName: '',
        availableAmt: '3 473.46',
        overdraftAmt: '0',
        freeAmt: '3 473.46',
        commonId: 'ownBankCards_30740546',
        subTitle: '',
        finalName: 'Моцная картка',
        pimpText: '',
        widgetContent:
          [
            'js-transfer-card-card',
            'js-transfer-card-acc',
            'js-card-limits',
            'js-block-card',
            'js-rename-card',
            'js-card-history',
            'js-replace-card-info'
          ],
        cardsKey: 30740546
      },
      {
        id: '30740546',
        type: 'card',
        title: 'Моцная картка*7001',
        instrument: 'BYN',
        balance: 3473.46,
        creditLimit: 0,
        syncID: ['7001']
      }
    ]
  ])('converts ccard accounts', (apiAccount, account) => {
    expect(convertAccount(apiAccount)).toEqual(account)
  })
})
