import { UserInteractionError } from '../../errors'
import { fetchProducts, fetchTransactions, login } from './api'
import { convertAccounts, convertTransaction, groupAccountsById } from './converters'

export async function scrape ({ preferences, fromDate, toDate, isInBackground }) {
  ZenMoney.trustCertificates([
    // Expires: Dec 22 12:42:19 2026 GMT
    // Covers: ib.sinara.ru
    `-----BEGIN CERTIFICATE-----
MIIIpzCCBo+gAwIBAgIQSZUT778oQgmAT2hyyNAtczANBgkqhkiG9w0BAQsFADBv
MQswCQYDVQQGEwJSVTE/MD0GA1UECgw2VGhlIE1pbmlzdHJ5IG9mIERpZ2l0YWwg
RGV2ZWxvcG1lbnQgYW5kIENvbW11bmljYXRpb25zMR8wHQYDVQQDDBZSdXNzaWFu
IFRydXN0ZWQgU3ViIENBMB4XDTI1MTIyMjEyNDIxOVoXDTI2MTIyMjEyNDIxOVow
ggEiMQswCQYDVQQGEwJSVTEzMDEGA1UECAwqNjYg0KHQstC10YDQtNC70L7QstGB
0LrQsNGPINC+0LHQu9Cw0YHRgtGMMSEwHwYDVQQHDBjQldC60LDRgtC10YDQuNC9
0LHRg9GA0LMxRjBEBgNVBAoMPdCQ0JrQptCY0J7QndCV0KDQndCe0JUg0J7QkdCp
0JXQodCi0JLQniDQkdCQ0J3QmiDQodCY0J3QkNCg0JAxFDASBgNVBAMMCyouc2lu
YXJhLnJ1MRUwEwYFKoUDZAQMCjY2MDgwMDMwNTIxGDAWBgUqhQNkAQwNMTAyNjYw
MDAwMDQ2MDEsMCoGA1UECQwj0YPQuy7QmtGD0LnQsdGL0YjQtdCy0LAsINGB0YLR
gC4gNzUwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCfw+UHqGJT4kZf
pG9TUcxQJwN60XxKHJKkGBH9xq782hmmaAlQwlkMaONY2zEBaSeRNZQkxcRB5/S+
484C0cvh6qwhA+eqyzIKsYR0xUJhkJmIe67FMBzczByI01d6Iz3gAduJzE1St1+m
GI66uKn8RBcVNmYpFBXoxG1cU3j/b5DuyXnGWBcy3DCFsKUBAuAQBlAksD/KfEsI
6i0tvCKze7RpIIZqFA32dDwfMQxIAEaxFIE2eQtcHPambjhDeEE9AwJ853BpVQze
2VI3GMjkkoaGYAvZGIhybP+cUycBswoG0jZbWStcqIP1YyKyM+qvyKszg0Ma7KrA
1L+b0xN1AgMBAAGjggOIMIIDhDAfBgNVHSMEGDAWgBR3Pdk5r0K93FvKduru/c4+
YSkwXzAdBgNVHQ4EFgQUaoVOAc6kwW5pK4NFweLteGeLjukwCwYDVR0PBAQDAgOo
MB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDATAwBgNVHREEKTAnggsqLnNp
bmFyYS5ydYINd3d3LnNpbmFyYS5ydYIJc2luYXJhLnJ1MIGLBgNVHR8EgYMwgYAw
PKA6oDiGNmh0dHA6Ly9udWMtY2RwLnZvc2tob2QucnUvY2RwL3N1YmNhX3NzbF9y
c2EyMDI0X292LmNybDBAoD6gPIY6aHR0cDovL251Yy1jZHAuZGlnaXRhbC5nb3Yu
cnUvY2RwL3N1YmNhX3NzbF9yc2EyMDI0X292LmNybDCBvgYIKwYBBQUHAQEEgbEw
ga4wPwYIKwYBBQUHMAKGM2h0dHA6Ly9udWMtY2RwLnZvc2tob2QucnUvY2RwL3N1
YmNhX3NzbF9yc2EyMDI0LmNydDBDBggrBgEFBQcwAoY3aHR0cDovL251Yy1jZHAu
ZGlnaXRhbC5nb3YucnUvY2RwL3N1YmNhX3NzbF9yc2EyMDI0LmNydDAmBggrBgEF
BQcwAYYaaHR0cDovL251Yy1vY3NwLnZvc2tob2QucnUwEwYDVR0gBAwwCjAIBgZn
gQwBAgIwggF+BgorBgEEAdZ5AgQCBIIBbgSCAWoBaAB2AHjZEr5CCsACHLpdolQy
kVPbSMsGK/xDASQeEKvHFp5nAAABm0YWH/QAAAQDAEcwRQIhAK0WAkodaf4JaLiO
RBqUp4mgpLzp0jZ+49mOAf0IlimOAiAzxMiYJxoNXh2BOdC5S2JKrkgNvevSUnl+
yN6kvpO4AAB2AFYex0TfGvcC5iaDrd/Elc91oxsMbOigx+oBAzCQt0iFAAABm0YW
H/sAAAQDAEcwRQIgTvLagSXJOF8sgpBy0Y3A8U5VQ7zsEpfd06bsUiX5BAcCIQCv
hqJ+Yg6T6hRZpf6VIVSpJvNqsAFJ2H5oxea7i987IQB2AMm4EbzAHGJdyif01sRH
y19+Dr9yy1mRqDMvmb+aKj5KAAABm0YWH+8AAAQDAEcwRQIhANpyye5L0YEoLsuC
gJmJgdj3FsqMg2reajkhSqRpsIB0AiBG5Ylu0+BcB3kg4nl/bPwfunnIlqQDwLn5
07auktrbPzANBgkqhkiG9w0BAQsFAAOCAgEAtTAEuwB65dEDrYAmgarR7U+qkMez
S/QYMQx1nXFSOZlWOAXTsufMEIMZrydJ6X60Epv//HagOLUB7Z2VxeePYTw4FnMx
YNnFrM2aoXuTBhoq9KMlS6QGrOl1m6YDRxabr1vRMgAaBH4kyjggPz+pad+97CsQ
h7M97N82UGp4tgc5I3Rj1nRfssjhk8+61wq+9Vlpv5qpENAmfrgaQLoXVXDRj7e2
uqBe0fNVGinI/Fu3vQbBWeMHWTFwpNPudQhZY8W+UJ6+eC3gQZVSVvmEAAE2SiLh
WUxk/G20s3JjFjFUyYERI7uuagyabuulSFDr2ecjVNOEzDAS/i0Z0bQu6GHj/N0z
B5IspchFVCeoo883uk/HOb6Wce+BS/LhsDnywup0QysIMpNNIIlSyIwJeSUGPx+U
1MKNrmedCfJL+UZH5zhhVYzzqoGlEfaBCBCY1N5mQJp/IkpGLj3SbqMZ2VB1M44T
SZiqjguazz6niUVv6GrwBhGmC2HRv9ej4b86c64g0UNkTsBDg3xgn+eFU6NXnrgh
wLc8+VdYXc/dP8nvgGUglcnwyx9tMQ7/GYEPREcJIwIO6/M4g+QorCnkFdWkC/oX
QnT1MVvAZcT2rtZzQIaYOvG+phrLn8NK9Ie5GI2abcNeGSpMPNgAGqQWPiyccUR0
bB0/U2Lj6kTFw0s=
-----END CERTIFICATE-----`
  ])
  if (isInBackground) {
    throw new UserInteractionError()
  }
  await login(preferences.login, preferences.password)
  const products = await fetchProducts()
  const accounts = convertAccounts(products)
  const accountsById = groupAccountsById(accounts)
  const operations = await fetchTransactions(fromDate, toDate, accountsById)
  const transactions = operations.map(transaction => convertTransaction(transaction, accountsById)).filter(x => x)
  return {
    accounts,
    transactions
  }
}
