import { convertTransaction } from '../../../converters'

describe('convertTransaction', () => {
  it.each([
    [
      {
        id: 208535896,
        balanceBefore: '9626.86',
        date: '2021-06-25T04:28:21Z',
        createdAt: '2021-06-25T04:28:21Z',
        state: 'paid',
        cashbackAmount: null,
        comment: null,
        balanceAfter: '21626.86',
        amount: '12000.0',
        canRepeat: false,
        account: { id: 206329, currencyId: 16, currencyIsoCode: 'rur' },
        geoInfo: {},
        categoryId: null,
        operation: 'ПАО "ЧЕЛЯБИНВЕСТБАНК" Зачисление средств от СБП .\r\nАбонент:Николай Николаевич Н\r\nМоб:+79510000000\r\nБанк:Сбербанк\r\n 30233810690000009005 12000.0',
        cardOrAccount:
          {
            id: 206329,
            number: '40817810200880004220',
            title: 'Картсчет 0004220 (RUB)',
            displayTitle: 'Картсчет 0004220 (RUB)',
            currencyId: 16,
            currencyIsoCode: 'rur',
            reservedBalance: '0.0',
            arestedBalance: '0.0',
            closeDate: null,
            hidden: false,
            withdraw: true,
            refund: true,
            productType: null,
            dogovType: 5,
            cashback: false,
            closed: false,
            balance: '21626.86',
            ownAmount: '21626.86',
            creditAmount: 0,
            totalAmount: '21626.86',
            creditAvail: '-0.0',
            loanAmount: '-0.0',
            cards:
              [
                {
                  id: 313253,
                  accountId: 206329,
                  balance: '21626.86',
                  minimalBalance: '0.0',
                  currencyId: 16,
                  currencyIsoCode: 'rur',
                  cardholder: 'EXPRESS CARD',
                  number: '546844******2612',
                  authLimit: '78000000000000232318',
                  title: 'MasterCard Virtual 3 RUR',
                  displayTitle: 'MasterCard Virtual 3 RUR',
                  state: 'active',
                  issueAt: '2019-10-03',
                  expirationAt: '2022-10-31',
                  expiresIn: 488,
                  unaffordable: false,
                  lastOperationDate: '2021-06-25T04:28:24Z',
                  firstOperationDate: '2019-10-24T05:58:05Z',
                  blockedByDate: false,
                  hidden: false,
                  blankImageUrl: '/assets/cardblanks/mc_virtual.jpg',
                  imageUrl: '/assets/cardtypes/MC_VIRTUAL.png',
                  iconUrl: '/assets/cardicons/MC_VIRTUAL.png',
                  keychain: null,
                  svId: 636368,
                  isIbs: true,
                  cardType: { keyword: 'MC_VIRTUAL' },
                  canReissue: true,
                  canBlock: true,
                  isExpiring: false,
                  canTokenized: true,
                  canP2p: true
                },
                {
                  id: 313254,
                  accountId: 206329,
                  balance: '0.0',
                  minimalBalance: '0.0',
                  currencyId: 16,
                  currencyIsoCode: 'rur',
                  cardholder: null,
                  number: '40817***4220',
                  authLimit: null,
                  title: 'Свободные средства',
                  displayTitle: 'Средства не на карте',
                  state: 'pseudo',
                  issueAt: '2019-10-24',
                  expirationAt: null,
                  expiresIn: null,
                  unaffordable: false,
                  lastOperationDate: '2021-06-25T04:28:24Z',
                  firstOperationDate: '2019-10-24T05:58:05Z',
                  blockedByDate: false,
                  hidden: false,
                  blankImageUrl: '/assets/cardtypesblanks/X_AVAILABLE_FUNDS.jpg',
                  imageUrl: '/assets/cardtypes/X_AVAILABLE_FUNDS.png',
                  iconUrl: '/assets/cardicons/X_AVAILABLE_FUNDS.png',
                  keychain: null,
                  isIbs: false,
                  cardType: { keyword: 'X_AVAILABLE_FUNDS' },
                  canReissue: false,
                  canBlock: false,
                  isExpiring: true,
                  canTokenized: false,
                  canP2p: false
                }
              ]
          },
        cardOrAccountId: 'account_206329',
        event:
          {
            orderNumber: 1154528373,
            operationDate: '2021-06-25T04:28:21Z',
            orderDate: '2021-06-25',
            name: 'ПАО "ЧЕЛЯБИНВЕСТБАНК"',
            description: 'Зачисление средств от СБП .\r\nАбонент:Николай Николаевич Н\r\nМоб:+79510000000\r\nБанк:Сбербанк\r\n',
            state: 'paid',
            stateDescription: 'Документ проведен',
            fk: 'ibs_id|1|524048074C',
            documentNumber: 69,
            operationKindId: '01',
            paymentPriority: '5',
            incomeDate: '2021-06-25T04:28:21Z',
            amount: '12000.0',
            currencyIsoCode: 'rur',
            account: '30233810690000009005',
            destinationInn: '744718948971',
            destinationKpp: '0',
            destinationName: 'НИКОЛАЕВ НИКОЛАЙ НИКОЛАЕВИЧ',
            destinationAccount: '40817810200880004220',
            destinationBank: 'ПАО "ЧЕЛЯБИНВЕСТБАНК"',
            destinationAddress: 'Г. ЧЕЛЯБИНСК',
            destinationBic: '047501779',
            destinationCorrespondentAccount: '30101810400000000779',
            srcInn: '7421000200',
            srcKpp: '745101001',
            srcName: 'ПАО "ЧЕЛЯБИНВЕСТБАНК"',
            srcAccount: '30233810690000009005',
            srcBank: 'ПАО "ЧЕЛЯБИНВЕСТБАНК" Г ЧЕЛЯБИНСК',
            srcBic: '047501779',
            srcCorrespondentAccount: '30101810400000000779'
          }
      },
      {
        date: new Date('2021-06-25T04:28:21+00:00'),
        hold: false,
        movements: [
          {
            id: '208535896',
            account: { id: '206329' },
            invoice: null,
            sum: 12000,
            fee: 0
          },
          {
            id: null,
            account: {
              company: null,
              instrument: 'RUB',
              syncIds: null,
              type: 'ccard'
            },
            invoice: null,
            sum: -12000,
            fee: 0
          }
        ],
        merchant: {
          city: null,
          country: null,
          title: 'Николай Николаевич Н',
          location: null,
          mcc: null
        },
        comment: null
      }
    ],
    [
      {
        id: 196111359,
        balanceBefore: '0.0',
        date: '2021-05-20T11:05:36Z',
        createdAt: '2021-05-20T11:05:36Z',
        state: 'paid',
        cashbackAmount: null,
        comment: null,
        balanceAfter: '1275.94',
        amount: '1275.94',
        canRepeat: false,
        account: { id: 281832, currencyId: 16, currencyIsoCode: 'rur' },
        geoInfo: {},
        categoryId: null,
        operation: 'ПАО "ЧЕЛЯБИНВЕСТБАНК" Зачисление средств от СБП .\r\nАбонент:Николай Николаевич Н\r\nМоб:+79950000000\r\nБанк:Тинькофф Банк\r\nСообщение:На ЖКХ\r\n 30233810690000009005 1275.94',
        cardOrAccount:
          {
            id: 281832,
            number: '40817810100880023990',
            title: 'Картсчет 0023990 (RUB)',
            displayTitle: 'Картсчет 0023990 (RUB)',
            currencyId: 16,
            currencyIsoCode: 'rur',
            reservedBalance: '0.0',
            arestedBalance: '0.0',
            closeDate: null,
            hidden: false,
            withdraw: false,
            refund: true,
            productType: null,
            dogovType: 5,
            cashback: false,
            closed: false,
            balance: 0,
            ownAmount: 0,
            creditAmount: 0,
            totalAmount: '0.0',
            creditAvail: '-0.0',
            loanAmount: '-0.0',
            cards:
              [
                {
                  id: 405774,
                  accountId: 281832,
                  balance: '0.0',
                  minimalBalance: '0.0',
                  currencyId: 16,
                  currencyIsoCode: 'rur',
                  cardholder: 'NIKOLAY NIKOLAEV',
                  number: '546844******5791',
                  authLimit: '78000000000000683975',
                  title: 'MC Virtual - 3 года - Руб',
                  displayTitle: 'MC Virtual - 3 года - Руб',
                  state: 'active',
                  issueAt: '2021-05-19',
                  expirationAt: '2024-05-31',
                  expiresIn: 1066,
                  unaffordable: false,
                  lastOperationDate: '2021-06-20T23:42:31Z',
                  firstOperationDate: '2021-05-20T11:09:20Z',
                  blockedByDate: false,
                  hidden: false,
                  blankImageUrl: '/assets/cardblanks/mc_virtual.jpg',
                  imageUrl: '/assets/cardtypes/MC_VIRTUAL.png',
                  iconUrl: '/assets/cardicons/MC_VIRTUAL.png',
                  keychain: null,
                  svId: 755461,
                  isIbs: true,
                  cardType: { keyword: 'MC_VIRTUAL' },
                  canReissue: true,
                  canBlock: true,
                  isExpiring: false,
                  canTokenized: false,
                  canP2p: true
                },
                {
                  id: 405769,
                  accountId: 281832,
                  balance: '0.0',
                  minimalBalance: '0.0',
                  currencyId: 16,
                  currencyIsoCode: 'rur',
                  cardholder: null,
                  number: '40817***3990',
                  authLimit: null,
                  title: 'Свободные средства',
                  displayTitle: 'Средства не на карте',
                  state: 'pseudo',
                  issueAt: '2021-05-19',
                  expirationAt: null,
                  expiresIn: null,
                  unaffordable: false,
                  lastOperationDate: '2021-06-20T16:33:08Z',
                  firstOperationDate: '2021-05-20T11:09:20Z',
                  blockedByDate: false,
                  hidden: false,
                  blankImageUrl: '/assets/cardtypesblanks/X_AVAILABLE_FUNDS.jpg',
                  imageUrl: '/assets/cardtypes/X_AVAILABLE_FUNDS.png',
                  iconUrl: '/assets/cardicons/X_AVAILABLE_FUNDS.png',
                  keychain: null,
                  isIbs: false,
                  cardType: { keyword: 'X_AVAILABLE_FUNDS' },
                  canReissue: false,
                  canBlock: false,
                  isExpiring: true,
                  canTokenized: false,
                  canP2p: false
                }
              ]
          },
        cardOrAccountId: 'account_281832',
        event:
          {
            orderNumber: 1106803118,
            operationDate: '2021-05-20T11:05:36Z',
            orderDate: '2021-05-20',
            name: 'ПАО "ЧЕЛЯБИНВЕСТБАНК"',
            description: 'Зачисление средств от СБП .\r\nАбонент:Николай Николаевич Н\r\nМоб:+79950000000\r\nБанк:Тинькофф Банк\r\nСообщение:На ЖКХ\r\n',
            state: 'paid',
            stateDescription: 'Документ проведен',
            fk: 'ibs_id|1|517337207C',
            documentNumber: 204,
            operationKindId: '01',
            paymentPriority: '5',
            incomeDate: '2021-05-20T11:05:36Z',
            amount: '1275.94',
            currencyIsoCode: 'rur',
            account: '30233810690000009005',
            destinationInn: null,
            destinationKpp: '0',
            destinationName: 'НИКОЛАЕВ НИКОЛАЙ НИКОЛАЕВИЧ',
            destinationAccount: '40817810100880023990',
            destinationBank: 'ПАО "ЧЕЛЯБИНВЕСТБАНК"',
            destinationAddress: 'Г. ЧЕЛЯБИНСК',
            destinationBic: '047501779',
            destinationCorrespondentAccount: '30101810400000000779',
            srcInn: '7421000200',
            srcKpp: '745101001',
            srcName: 'ПАО "ЧЕЛЯБИНВЕСТБАНК"',
            srcAccount: '30233810690000009005',
            srcBank: 'ПАО "ЧЕЛЯБИНВЕСТБАНК" Г ЧЕЛЯБИНСК',
            srcBic: '047501779',
            srcCorrespondentAccount: '30101810400000000779'
          }
      },
      {
        date: new Date('2021-05-20T11:05:36+00:00'),
        hold: false,
        movements: [
          {
            id: '196111359',
            account: { id: '206329' },
            invoice: null,
            sum: 1275.94,
            fee: 0
          },
          {
            id: null,
            account: {
              company: null,
              instrument: 'RUB',
              syncIds: null,
              type: 'ccard'
            },
            invoice: null,
            sum: -1275.94,
            fee: 0
          }
        ],
        merchant: {
          city: null,
          country: null,
          title: 'Николай Николаевич Н',
          location: null,
          mcc: null
        },
        comment: 'На ЖКХ'
      }
    ],
    [
      {
        id: 214666438,
        balanceBefore: '6820.83',
        date: '2021-07-01T08:39:57Z',
        createdAt: '2021-07-01T08:39:57Z',
        state: 'paid',
        cashbackAmount: null,
        comment: null,
        balanceAfter: '13626.75',
        amount: '6805.92',
        canRepeat: false,
        account: { id: 69917, currencyId: 16, currencyIsoCode: 'rur' },
        geoInfo: {},
        categoryId: null,
        operation: 'ПАО "ЧЕЛЯБИНВЕСТБАНК" (Расчеты с ООО ЧОО "СТАТУС СБ") Сумма отпускных\r\nЗачисление на основании реестра SB20767.ZZZ 47422810990001013471 6805.92',
        cardOrAccount:
          {
            id: 69917,
            number: '40817810700211227354',
            title: 'Картсчет 1227354 (RUB)',
            displayTitle: 'Картсчет 1227354 (RUB)',
            currencyId: 16,
            currencyIsoCode: 'rur',
            reservedBalance: '0.0',
            arestedBalance: '0.0',
            closeDate: null,
            hidden: false,
            withdraw: true,
            refund: true,
            productType: null,
            dogovType: 1,
            cashback: false,
            closed: false,
            balance: '13626.75',
            ownAmount: '13626.75',
            creditAmount: 0,
            totalAmount: '13626.75',
            creditAvail: '-0.0',
            loanAmount: '-0.0',
            cards:
              [
                {
                  id: 106787,
                  accountId: 69917,
                  balance: '13626.75',
                  minimalBalance: '0.0',
                  currencyId: 16,
                  currencyIsoCode: 'rur',
                  cardholder: 'EVGENII GOSTEV',
                  number: '406149******6621',
                  authLimit: '78000000000000535626',
                  title: 'Visa Classic - Зарплатная - 5 лет - 0% - руб.',
                  displayTitle: 'Visa Classic - Зарплатная - 5 лет - 0% - руб.',
                  state: 'active',
                  issueAt: '2016-07-06',
                  expirationAt: '2021-07-31',
                  expiresIn: 29,
                  unaffordable: false,
                  lastOperationDate: '2021-07-01T08:40:04Z',
                  firstOperationDate: '2016-08-09T07:20:47Z',
                  blockedByDate: false,
                  hidden: false,
                  blankImageUrl: '/assets/cardblanks/visa_classic.jpg',
                  imageUrl: '/assets/cardtypes/VISA_CLASSIC.png',
                  iconUrl: '/assets/cardicons/VISA_CLASSIC.png',
                  keychain: null,
                  svId: 352876,
                  isIbs: true,
                  cardType: { keyword: 'VISA_CLASSIC' },
                  canReissue: true,
                  canBlock: true,
                  isExpiring: false,
                  canTokenized: false,
                  canP2p: true
                },
                {
                  id: 106788,
                  accountId: 69917,
                  balance: '0.0',
                  minimalBalance: '0.0',
                  currencyId: 16,
                  currencyIsoCode: 'rur',
                  cardholder: null,
                  number: '40817***7354',
                  authLimit: null,
                  title: 'Свободные средства',
                  displayTitle: 'Средства не на карте',
                  state: 'pseudo',
                  issueAt: '2016-07-06',
                  expirationAt: null,
                  expiresIn: null,
                  unaffordable: false,
                  lastOperationDate: '2021-07-01T08:40:04Z',
                  firstOperationDate: '2016-08-09T07:20:47Z',
                  blockedByDate: false,
                  hidden: false,
                  blankImageUrl: '/assets/cardtypesblanks/X_AVAILABLE_FUNDS.jpg',
                  imageUrl: '/assets/cardtypes/X_AVAILABLE_FUNDS.png',
                  iconUrl: '/assets/cardicons/X_AVAILABLE_FUNDS.png',
                  keychain: null,
                  isIbs: false,
                  cardType: { keyword: 'X_AVAILABLE_FUNDS' },
                  canReissue: false,
                  canBlock: false,
                  isExpiring: true,
                  canTokenized: false,
                  canP2p: false
                }
              ]
          },
        cardOrAccountId: 'account_69917',
        event:
          {
            orderNumber: 1172796038,
            operationDate: '2021-07-01T08:39:57Z',
            orderDate: '2021-07-01',
            name: 'ПАО "ЧЕЛЯБИНВЕСТБАНК" (Расчеты с ООО ЧОО "СТАТУС СБ")',
            description: 'Сумма отпускных\r\nЗачисление на основании реестра SB20767.ZZZ',
            state: 'paid',
            stateDescription: 'Документ проведен',
            fk: 'ibs_id|1|525223447C',
            documentNumber: 448,
            operationKindId: '01',
            paymentPriority: '5',
            incomeDate: '2021-07-01T08:39:57Z',
            amount: '6805.92',
            currencyIsoCode: 'rur',
            account: '47422810990001013471',
            destinationInn: '743001117869',
            destinationKpp: '0',
            destinationName: 'ГОСТЕВ ЕВГЕНИЙ АЛЕКСАНДРОВИЧ',
            destinationAccount: '40817810700211227354',
            destinationBank: 'ПАО "ЧЕЛЯБИНВЕСТБАНК"',
            destinationAddress: 'Г. ЧЕЛЯБИНСК',
            destinationBic: '047501779',
            destinationCorrespondentAccount: '30101810400000000779',
            srcInn: '7421000200',
            srcKpp: '745101001',
            srcName: 'ПАО "ЧЕЛЯБИНВЕСТБАНК" (Расчеты с ООО ЧОО "СТАТУС СБ")',
            srcAccount: '47422810990001013471',
            srcBank: 'ПАО "ЧЕЛЯБИНВЕСТБАНК" Г ЧЕЛЯБИНСК',
            srcBic: '047501779',
            srcCorrespondentAccount: '30101810400000000779'
          }
      },
      {
        date: new Date('2021-07-01T08:39:57+00:00'),
        hold: false,
        movements: [
          {
            id: '214666438',
            account: { id: '206329' },
            invoice: null,
            sum: 6805.92,
            fee: 0
          },
          {
            id: null,
            account: {
              company: null,
              instrument: 'RUB',
              syncIds: null,
              type: 'ccard'
            },
            invoice: null,
            sum: -6805.92,
            fee: 0
          }
        ],
        merchant: {
          city: null,
          country: null,
          title: 'ООО ЧОО "СТАТУС СБ"',
          location: null,
          mcc: null
        },
        comment: null
      }
    ]
  ])('converts outer income transfer', (apiTransaction, transaction) => {
    expect(convertTransaction(apiTransaction, { id: '206329', instrument: 'RUB' })).toEqual(transaction)
  })
})
