import { preprocessApiTransactions } from '../../converters'

describe('preprocessApiTransactions', () => {
  it.each([
    [
      [
        {
          id: '1',
          payment_id: '111111',
          utrnno: '0',
          amount: '439.8',
          cntrg_info_param2: '222222',
          cntrg_info_param3: '123456******7890',
          cntrg_info_param4: null,
          cntrg_info_param5: null,
          status_note: 'Успешно проведен',
          state: 2,
          paydoc_state: 2,
          service_name: 'CASHBACK',
          created: '2021-01-28 22:11:12',
          created_timestamp: 1611871872,
          abs_type: 'MDEPOSIT',
          account_id: 14257780,
          error: null,
          service_id: -9,
          is_invoice: 0,
          parameter_name: null,
          parameter_id: 0,
          comission_amount: 0,
          image: 'https://cdn.click.uz/app/rev2/service/300x230/logo_-9.png',
          is_indoor: 0,
          qr_image: null,
          qr_header: null,
          qr_footer: null,
          nds: 0,
          card_num: null,
          credit: 1,
          transType: 760,
          transType_desc: 'Зачисление на карту',
          card_sender: null,
          bank_sender: '880',
          card_recipient: null,
          bank_recipient: '880'
        },
        {
          id: '2',
          payment_id: '222222',
          utrnno: '0',
          amount: '21 990',
          cntrg_info_param2: '442444',
          cntrg_info_param3: '2236346767',
          cntrg_info_param4: null,
          cntrg_info_param5: null,
          status_note: 'Платеж аннулирован',
          state: -1,
          paydoc_state: -100,
          service_name: 'KORZINKA.UZ',
          created: '2021-01-28 22:11:12',
          created_timestamp: 1611871872,
          abs_type: 'WALLET ',
          account_id: 78900,
          error: null,
          service_id: 40134,
          is_invoice: 0,
          parameter_name: 'Сервис ID',
          parameter_id: 0,
          comission_amount: 0,
          image: 'https://cdn.click.uz/app/rev2/service/indoor/40134.png',
          is_indoor: 1,
          qr_image: null,
          qr_header: null,
          qr_footer: null,
          nds: 0,
          card_num: null,
          credit: 0,
          transType: 683,
          transType_desc: 'Онлайн оплата/перевод',
          card_sender: null,
          bank_sender: null,
          card_recipient: null,
          bank_recipient: null
        },
        {
          id: '3',
          payment_id: '333333',
          utrnno: '34646535757',
          amount: '11 000',
          cntrg_info_param2: '35456867',
          cntrg_info_param3: '123456****7890',
          cntrg_info_param4: null,
          cntrg_info_param5: null,
          status_note: 'Успешно проведен',
          state: 2,
          paydoc_state: 2,
          service_name: 'Пополнение кошелька',
          created: '2021-01-28 22:06:04',
          created_timestamp: 1611871564,
          abs_type: 'SMARTV ',
          account_id: 127586,
          error: null,
          service_id: -6,
          is_invoice: 0,
          parameter_name: 'Номер карты',
          parameter_id: 512,
          comission_amount: 0,
          image: 'https://cdn.click.uz/app/rev2/service/300x230/logo_-6.png',
          is_indoor: 0,
          qr_image: null,
          qr_header: null,
          qr_footer: null,
          nds: 0,
          card_num: null,
          credit: 0,
          transType: 683,
          transType_desc: 'Онлайн оплата/перевод',
          card_sender: 'IVAN IVANOV',
          bank_sender: '049',
          card_recipient: '',
          bank_recipient: '880'
        },
        {
          id: '4',
          payment_id: '333333',
          utrnno: '34646535757',
          amount: '11 000',
          cntrg_info_param2: '35456867',
          cntrg_info_param3: '123456****7890',
          cntrg_info_param4: null,
          cntrg_info_param5: null,
          status_note: 'Успешно проведен',
          state: 2,
          paydoc_state: 2,
          service_name: 'Пополнение кошелька',
          created: '2021-01-28 22:06:04',
          created_timestamp: 1611871564,
          abs_type: 'SMARTV ',
          account_id: 127586,
          error: null,
          service_id: -6,
          is_invoice: 0,
          parameter_name: 'Номер карты',
          parameter_id: 512,
          comission_amount: 0,
          image: 'https://cdn.click.uz/app/rev2/service/300x230/logo_-6.png',
          is_indoor: 0,
          qr_image: null,
          qr_header: null,
          qr_footer: null,
          nds: 0,
          card_num: null,
          credit: 1,
          transType: 760,
          transType_desc: 'Зачисление на карту',
          card_sender: 'IVAN IVANOV',
          bank_sender: '049',
          card_recipient: '',
          bank_recipient: '880'
        },
        {
          id: '5',
          payment_id: '1310346444',
          utrnno: '10414319252',
          amount: '27 000',
          cntrg_info_param2: '35456867',
          cntrg_info_param3: '123456****7890',
          cntrg_info_param4: null,
          cntrg_info_param5: null,
          status_note: 'Платеж аннулирован',
          state: -1,
          paydoc_state: -100,
          service_name: 'Пополнение кошелька',
          created: '2021-01-28 16:58:38',
          created_timestamp: 1611853118,
          abs_type: 'SMARTV ',
          account_id: 127586,
          error: 'Платеж аннулирован',
          service_id: -6,
          is_invoice: 0,
          parameter_name: 'Номер карты',
          parameter_id: 512,
          comission_amount: 0,
          image: 'https://cdn.click.uz/app/rev2/service/300x230/logo_-6.png',
          is_indoor: 0,
          qr_image: null,
          qr_header: null,
          qr_footer: null,
          nds: 0,
          card_num: null,
          credit: 0,
          transType: 683,
          transType_desc: 'Онлайн оплата/перевод',
          card_sender: 'IVAN IVANOV',
          bank_sender: '049',
          card_recipient: '',
          bank_recipient: '880'
        },
        {
          id: '6',
          payment_id: '1310346444',
          utrnno: '10414319252',
          amount: '27 000',
          cntrg_info_param2: '35456867',
          cntrg_info_param3: '123456****7890',
          cntrg_info_param4: null,
          cntrg_info_param5: null,
          status_note: 'Платеж аннулирован',
          state: -1,
          paydoc_state: -100,
          service_name: 'Пополнение кошелька',
          created: '2021-01-28 16:58:38',
          created_timestamp: 1611853118,
          abs_type: 'SMARTV ',
          account_id: 127586,
          error: 'Платеж аннулирован',
          service_id: -6,
          is_invoice: 0,
          parameter_name: 'Номер карты',
          parameter_id: 512,
          comission_amount: 0,
          image: 'https://cdn.click.uz/app/rev2/service/300x230/logo_-6.png',
          is_indoor: 0,
          qr_image: null,
          qr_header: null,
          qr_footer: null,
          nds: 0,
          card_num: null,
          credit: 1,
          transType: 760,
          transType_desc: 'Зачисление на карту',
          card_sender: 'IVAN IVANOV',
          bank_sender: '049',
          card_recipient: '',
          bank_recipient: '880'
        }
      ],
      [
        [
          {
            id: '1',
            payment_id: '111111',
            utrnno: '0',
            amount: '439.8',
            cntrg_info_param2: '222222',
            cntrg_info_param3: '123456******7890',
            cntrg_info_param4: null,
            cntrg_info_param5: null,
            status_note: 'Успешно проведен',
            state: 2,
            paydoc_state: 2,
            service_name: 'CASHBACK',
            created: '2021-01-28 22:11:12',
            created_timestamp: 1611871872,
            abs_type: 'MDEPOSIT',
            account_id: 14257780,
            error: null,
            service_id: -9,
            is_invoice: 0,
            parameter_name: null,
            parameter_id: 0,
            comission_amount: 0,
            image: 'https://cdn.click.uz/app/rev2/service/300x230/logo_-9.png',
            is_indoor: 0,
            qr_image: null,
            qr_header: null,
            qr_footer: null,
            nds: 0,
            card_num: null,
            credit: 1,
            transType: 760,
            transType_desc: 'Зачисление на карту',
            card_sender: null,
            bank_sender: '880',
            card_recipient: null,
            bank_recipient: '880'
          }
        ],
        [
          {
            id: '3',
            payment_id: '333333',
            utrnno: '34646535757',
            amount: '11 000',
            cntrg_info_param2: '35456867',
            cntrg_info_param3: '123456****7890',
            cntrg_info_param4: null,
            cntrg_info_param5: null,
            status_note: 'Успешно проведен',
            state: 2,
            paydoc_state: 2,
            service_name: 'Пополнение кошелька',
            created: '2021-01-28 22:06:04',
            created_timestamp: 1611871564,
            abs_type: 'SMARTV ',
            account_id: 127586,
            error: null,
            service_id: -6,
            is_invoice: 0,
            parameter_name: 'Номер карты',
            parameter_id: 512,
            comission_amount: 0,
            image: 'https://cdn.click.uz/app/rev2/service/300x230/logo_-6.png',
            is_indoor: 0,
            qr_image: null,
            qr_header: null,
            qr_footer: null,
            nds: 0,
            card_num: null,
            credit: 0,
            transType: 683,
            transType_desc: 'Онлайн оплата/перевод',
            card_sender: 'IVAN IVANOV',
            bank_sender: '049',
            card_recipient: '',
            bank_recipient: '880'
          },
          {
            id: '4',
            payment_id: '333333',
            utrnno: '34646535757',
            amount: '11 000',
            cntrg_info_param2: '35456867',
            cntrg_info_param3: '123456****7890',
            cntrg_info_param4: null,
            cntrg_info_param5: null,
            status_note: 'Успешно проведен',
            state: 2,
            paydoc_state: 2,
            service_name: 'Пополнение кошелька',
            created: '2021-01-28 22:06:04',
            created_timestamp: 1611871564,
            abs_type: 'SMARTV ',
            account_id: 127586,
            error: null,
            service_id: -6,
            is_invoice: 0,
            parameter_name: 'Номер карты',
            parameter_id: 512,
            comission_amount: 0,
            image: 'https://cdn.click.uz/app/rev2/service/300x230/logo_-6.png',
            is_indoor: 0,
            qr_image: null,
            qr_header: null,
            qr_footer: null,
            nds: 0,
            card_num: null,
            credit: 1,
            transType: 760,
            transType_desc: 'Зачисление на карту',
            card_sender: 'IVAN IVANOV',
            bank_sender: '049',
            card_recipient: '',
            bank_recipient: '880'
          }
        ]
      ]
    ]
  ])(
    'should return not rejected apiTransactions grouped by payment_id',
    (apiTransactions, processedApiTransactions) => {
      expect(preprocessApiTransactions(apiTransactions)).toEqual(processedApiTransactions)
    }
  )
})
