/**
 * @author Ryadnov Andrey <me@ryadnov.ru>
 */

const TYPES = {
  CASH: 'CASH',
  DEPOSIT_PROC: 'DEPOSIT_PROC',
  FDT_RBS_COMMISSION: 'FDT_RBS_COMMISSION',
  PAYMENT: 'PAYMENT',
  PURCHASE: 'PURCHASE',
  RECHARGE: 'RECHARGE',
  REFUND: 'REFUND',
  TRANSFER: 'TRANSFER',
  WALLET: 'WALLET',
  ZKDP: 'ZKDP'
}

export {
  TYPES
}
