import { filterTransactions } from '../../api'
import { adjustTransactionsAndCheckBalance } from '../../converters'

describe('adjustTransactionsAndCheckBalance', () => {
  it('adds missing convertable api transactions to payments', () => {
    expect(adjustTransactionsAndCheckBalance([
      {
        date: '19.01.2019T21:00:34',
        description: 'CH Debit RUS MOSCOW IDT:0513 1 RUS MOSCOW SBOL',
        sum: {
          amount: '-40000.00',
          currency: { code: 'RUB', name: 'руб.' }
        }
      },
      {
        date: '19.01.2019T20:15:31',
        description: 'Note Acceptance RUS SANKT-PETERBU Note Acceptance RUS SANKT-PETERBU ITT 702889',
        sum: {
          amount: '+50000.00',
          currency: { code: 'RUB', name: 'руб.' }
        }
      },
      {
        date: '19.01.2019T00:00:00',
        description: 'Mobile Fee 3200 Mobile Fee',
        sum: { amount: '-60.00', currency: { code: 'RUB', name: 'руб.' } }
      },
      {
        date: '09.01.2019T15:24:43',
        description: 'CH Debit RUS MOSCOW IDT:0513 1 RUS MOSCOW SBOL',
        sum: {
          amount: '-100.00',
          currency: { code: 'RUB', name: 'руб.' }
        }
      }
    ], filterTransactions([
      {
        autopayable: 'true',
        copyable: 'true',
        date: '19.01.2019T20:59:58',
        description: 'Перевод клиенту Сбербанка',
        form: 'RurPayment',
        from: 'MasterCard Mass 5298 26** **** 3389',
        id: '11669890219',
        imageId: { staticImage: { url: null } },
        invoiceReminderSupported: 'false',
        invoiceSubscriptionSupported: 'false',
        isMobilePayment: 'false',
        operationAmount: { amount: '-40000.00', currency: { code: 'RUB', name: 'руб.' } },
        state: 'EXECUTED',
        templatable: 'true',
        to: 'НИКОЛАЙ НИКОЛАЕВИЧ Н.                                                        5469 55** **** 6339',
        type: 'payment',
        ufsId: null
      },
      {
        autopayable: 'false',
        copyable: 'false',
        date: '19.01.2019T20:15:31',
        description: 'Внесение наличных',
        form: 'ExtCardCashIn',
        id: '11669837967',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/33355.jpg' } },
        invoiceReminderSupported: 'false',
        invoiceSubscriptionSupported: 'false',
        isMobilePayment: 'false',
        operationAmount: { amount: '50000.00', currency: { code: 'RUB', name: 'руб.' } },
        state: 'FINANCIAL',
        templatable: 'false',
        to: 'Банкомат Сбербанка',
        type: 'payment',
        ufsId: null
      }
    ]))).toEqual({
      isBalanceAmbiguous: false,
      transactions: [
        {
          autopayable: 'true',
          copyable: 'true',
          date: '19.01.2019T20:59:58',
          description: 'Перевод клиенту Сбербанка',
          form: 'RurPayment',
          from: 'MasterCard Mass 5298 26** **** 3389',
          id: '11669890219',
          imageId: { staticImage: { url: null } },
          invoiceReminderSupported: 'false',
          invoiceSubscriptionSupported: 'false',
          isMobilePayment: 'false',
          operationAmount: { amount: '-40000.00', currency: { code: 'RUB', name: 'руб.' } },
          state: 'EXECUTED',
          templatable: 'true',
          to: 'НИКОЛАЙ НИКОЛАЕВИЧ Н.                                                        5469 55** **** 6339',
          type: 'payment',
          ufsId: null
        },
        {
          autopayable: 'false',
          copyable: 'false',
          date: '19.01.2019T20:15:31',
          description: 'Внесение наличных',
          form: 'ExtCardCashIn',
          id: '11669837967',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/33355.jpg' } },
          invoiceReminderSupported: 'false',
          invoiceSubscriptionSupported: 'false',
          isMobilePayment: 'false',
          operationAmount: { amount: '50000.00', currency: { code: 'RUB', name: 'руб.' } },
          state: 'FINANCIAL',
          templatable: 'false',
          to: 'Банкомат Сбербанка',
          type: 'payment',
          ufsId: null
        },
        {
          autopayable: 'false',
          copyable: 'false',
          date: '19.01.2019T00:00:00',
          description: 'Комиссии',
          form: 'TakingMeans',
          from: 'MasterCard Mass',
          id: null,
          imageId: { staticImage: { url: null } },
          invoiceReminderSupported: 'false',
          invoiceSubscriptionSupported: 'false',
          isMobilePayment: 'false',
          operationAmount: { amount: '-60.00', currency: { code: 'RUB', name: 'руб.' } },
          state: 'AUTHORIZATION',
          templatable: 'false',
          type: 'payment',
          ufsId: null
        }
      ]
    })
  })

  it('detects ambiguous balance', () => {
    expect(adjustTransactionsAndCheckBalance([
      {
        date: '19.01.2019T20:15:31',
        description: 'Note Acceptance RUS SANKT-PETERBU Note Acceptance RUS SANKT-PETERBU ITT 702889',
        sum: {
          amount: '+50000.00',
          currency: { code: 'RUB', name: 'руб.' }
        }
      },
      {
        date: '19.01.2019T00:00:00',
        description: 'Mobile Fee 3200 Mobile Fee',
        sum: { amount: '-60.00', currency: { code: 'RUB', name: 'руб.' } }
      },
      {
        date: '09.01.2019T15:24:43',
        description: 'CH Debit RUS MOSCOW IDT:0513 1 RUS MOSCOW SBOL',
        sum: {
          amount: '-100.00',
          currency: { code: 'RUB', name: 'руб.' }
        }
      }
    ], filterTransactions([
      {
        autopayable: 'true',
        copyable: 'true',
        date: '19.01.2019T20:59:58',
        description: 'Перевод клиенту Сбербанка',
        form: 'RurPayment',
        from: 'MasterCard Mass 5298 26** **** 3389',
        id: '11669890219',
        imageId: { staticImage: { url: null } },
        invoiceReminderSupported: 'false',
        invoiceSubscriptionSupported: 'false',
        isMobilePayment: 'false',
        operationAmount: { amount: '-40000.00', currency: { code: 'RUB', name: 'руб.' } },
        state: 'EXECUTED',
        templatable: 'true',
        to: 'НИКОЛАЙ НИКОЛАЕВИЧ Н.                                                        5469 55** **** 6339',
        type: 'payment',
        ufsId: null
      },
      {
        autopayable: 'false',
        copyable: 'false',
        date: '19.01.2019T20:15:31',
        description: 'Внесение наличных',
        form: 'ExtCardCashIn',
        id: '11669837967',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/33355.jpg' } },
        invoiceReminderSupported: 'false',
        invoiceSubscriptionSupported: 'false',
        isMobilePayment: 'false',
        operationAmount: { amount: '50000.00', currency: { code: 'RUB', name: 'руб.' } },
        state: 'FINANCIAL',
        templatable: 'false',
        to: 'Банкомат Сбербанка',
        type: 'payment',
        ufsId: null
      }
    ]))).toEqual({
      isBalanceAmbiguous: true,
      transactions: [
        {
          autopayable: 'true',
          copyable: 'true',
          date: '19.01.2019T20:59:58',
          description: 'Перевод клиенту Сбербанка',
          form: 'RurPayment',
          from: 'MasterCard Mass 5298 26** **** 3389',
          id: '11669890219',
          imageId: { staticImage: { url: null } },
          invoiceReminderSupported: 'false',
          invoiceSubscriptionSupported: 'false',
          isMobilePayment: 'false',
          operationAmount: { amount: '-40000.00', currency: { code: 'RUB', name: 'руб.' } },
          state: 'EXECUTED',
          templatable: 'true',
          to: 'НИКОЛАЙ НИКОЛАЕВИЧ Н.                                                        5469 55** **** 6339',
          type: 'payment',
          ufsId: null
        },
        {
          autopayable: 'false',
          copyable: 'false',
          date: '19.01.2019T20:15:31',
          description: 'Внесение наличных',
          form: 'ExtCardCashIn',
          id: '11669837967',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/33355.jpg' } },
          invoiceReminderSupported: 'false',
          invoiceSubscriptionSupported: 'false',
          isMobilePayment: 'false',
          operationAmount: { amount: '50000.00', currency: { code: 'RUB', name: 'руб.' } },
          state: 'FINANCIAL',
          templatable: 'false',
          to: 'Банкомат Сбербанка',
          type: 'payment',
          ufsId: null
        },
        {
          autopayable: 'false',
          copyable: 'false',
          date: '19.01.2019T00:00:00',
          description: 'Комиссии',
          form: 'TakingMeans',
          from: 'MasterCard Mass',
          id: null,
          imageId: { staticImage: { url: null } },
          invoiceReminderSupported: 'false',
          invoiceSubscriptionSupported: 'false',
          isMobilePayment: 'false',
          operationAmount: { amount: '-60.00', currency: { code: 'RUB', name: 'руб.' } },
          state: 'AUTHORIZATION',
          templatable: 'false',
          type: 'payment',
          ufsId: null
        }
      ]
    })
  })

  it('compares transactions by date and order flexibly', () => {
    expect(adjustTransactionsAndCheckBalance([
      {
        date: '10.02.2019T09:17:25',
        sum: { amount: '-10196,85', currency: { code: 'RUB', name: 'руб.' } },
        description: 'BP Card - Acct RUS  BP Card - Acct RUS  SBERBANK ONL@IN KARTA-VKLAD'
      },
      {
        date: '08.02.2019T18:45:27',
        sum: { amount: '+33000,00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'CH Payment RUS MOSCOW IDT:0614 2 RUS MOSCOW SBOL'
      },
      {
        date: '08.02.2019T08:46:56',
        sum: { amount: '+44676,17', currency: { code: 'RUB', name: 'руб.' } },
        description: 'ESB Payment to Card RUS  ESB Payment to Card RUS  1'
      },
      {
        date: '08.02.2019T00:00:00',
        sum: { amount: '-30000,00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'CH Debit RUS Visa Direct  IDT:0513 1 RUS Visa Direct TINKOFF BANK CARD2CARD'
      },
      {
        date: '08.02.2019T00:00:00',
        sum: { amount: '-30000,00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'CH Debit RUS Visa Direct  IDT:0513 1 RUS Visa Direct TINKOFF BANK CARD2CARD'
      },
      {
        date: '08.02.2019T00:00:00',
        sum: { amount: '-4000,00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'CH Debit RUS Visa Direct  IDT:0513 1 RUS Visa Direct TINKOFF BANK CARD2CARD'
      },
      {
        date: '08.02.2019T00:00:00',
        sum: { amount: '-2554,45', currency: { code: 'RUB', name: 'руб.' } },
        description: 'Retail RUS MOSCOW        Retail RUS MOSCOW OZON.RU'
      },
      {
        date: '05.02.2019T00:00:00',
        sum: { amount: '+4000,00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'CH Payment RUS Visa Direct  IDT:0614 2 RUS Visa Direct TINKOFF BANK CARD2CARD'
      },
      {
        date: '05.02.2019T00:00:00',
        sum: { amount: '-2000,00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'CH Debit RUS Visa Direct  IDT:0513 1 RUS Visa Direct TINKOFF BANK CARD2CARD'
      },
      {
        date: '05.02.2019T00:00:00',
        sum: { amount: '+500,00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'CH Payment RUS Visa Direct  IDT:0614 2 RUS Visa Direct TINKOFF BANK CARD2CARD'
      }
    ], filterTransactions([
      {
        id: '12251735104',
        ufsId: null,
        state: 'EXECUTED',
        date: '10.02.2019T09:16:44',
        from: 'Visa Classic 4276 49** **** 2340',
        to: 'Сберегательный счет 40817810549782372548',
        description: 'Перевод между своими счетами',
        operationAmount: { amount: '-10196.85', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'true',
        templatable: 'true',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'InternalPayment',
        imageId: { staticImage: { url: null } }
      },
      {
        id: '12218793772',
        ufsId: null,
        state: 'FINANCIAL',
        date: '08.02.2019T18:45:27',
        from: '2202 20** **** 1290',
        to: 'Сбербанк Онлайн',
        description: 'Входящий перевод',
        operationAmount: { amount: '33000.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardTransferIn',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/6f904da7-1663-4e68-801f-fe288c3283f6.png' } }
      },
      {
        id: '12219040731',
        ufsId: null,
        state: 'FINANCIAL',
        date: '08.02.2019T15:49:52',
        from: 'Visa Classic 4276 49** **** 2340',
        to: 'Тинькофф Банк',
        description: 'Перевод',
        operationAmount: { amount: '-4000.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardTransferOut',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
      },
      {
        id: '12219040704',
        ufsId: null,
        state: 'FINANCIAL',
        date: '08.02.2019T15:49:24',
        from: 'Visa Classic 4276 49** **** 2340',
        to: 'Тинькофф Банк',
        description: 'Перевод',
        operationAmount: { amount: '-30000.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardTransferOut',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
      },
      {
        id: '12199610025',
        ufsId: null,
        state: 'FINANCIAL',
        date: '08.02.2019T08:46:56',
        to: 'Зачисление',
        description: 'Прочие поступления',
        operationAmount: { amount: '44676.17', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardOtherIn',
        imageId: { staticImage: { url: null } }
      },
      {
        id: '12202740545',
        ufsId: null,
        state: 'FINANCIAL',
        date: '08.02.2019T08:05:32',
        from: 'Visa Classic 4276 49** **** 2340',
        to: 'Тинькофф Банк',
        description: 'Перевод',
        operationAmount: { amount: '-30000.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardTransferOut',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
      },
      {
        id: '12244584823',
        ufsId: null,
        state: 'FINANCIAL',
        date: '08.02.2019T00:00:00',
        from: 'Visa Classic 4276 49** **** 2340',
        to: 'OZON.ru',
        description: 'Оплата товаров и услуг',
        operationAmount: { amount: '-2554.45', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardPayment',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/dbcf613f-9b21-4e1b-9d9a-bfc84f00741d.png' } }
      },
      {
        id: '12140627398',
        ufsId: null,
        state: 'FINANCIAL',
        date: '05.02.2019T17:38:16',
        from: 'Visa Classic 4276 49** **** 2340',
        to: 'Тинькофф Банк',
        description: 'Перевод',
        operationAmount: { amount: '-2000.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardTransferOut',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
      },
      {
        id: '12140627379',
        ufsId: null,
        state: 'FINANCIAL',
        date: '05.02.2019T17:36:04',
        from: '5213 24** **** 1737',
        to: 'Тинькофф Банк',
        description: 'Входящий перевод',
        operationAmount: { amount: '500.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardTransferIn',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
      },
      {
        id: '12140627351',
        ufsId: null,
        state: 'FINANCIAL',
        date: '05.02.2019T17:35:45',
        from: '5213 24** **** 1737',
        to: 'Тинькофф Банк',
        description: 'Входящий перевод',
        operationAmount: { amount: '4000.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardTransferIn',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
      },
      {
        id: '12067071492',
        ufsId: null,
        state: 'FINANCIAL',
        date: '03.02.2019T15:55:06',
        from: '4276 49** **** 1102',
        to: 'Сбербанк Онлайн',
        description: 'Входящий перевод',
        operationAmount: { amount: '1000.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardTransferIn',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/6f904da7-1663-4e68-801f-fe288c3283f6.png' } }
      },
      {
        id: '12067784460',
        ufsId: null,
        state: 'FINANCIAL',
        date: '03.02.2019T13:26:36',
        from: 'Visa Classic 4276 49** **** 2340',
        to: 'Тинькофф Банк',
        description: 'Перевод',
        operationAmount: { amount: '-1000.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardTransferOut',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
      }
    ]))).toEqual({
      isBalanceAmbiguous: false,
      transactions: [
        {
          id: '12251735104',
          ufsId: null,
          state: 'EXECUTED',
          date: '10.02.2019T09:16:44',
          from: 'Visa Classic 4276 49** **** 2340',
          to: 'Сберегательный счет 40817810549782372548',
          description: 'Перевод между своими счетами',
          operationAmount: { amount: '-10196.85', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'true',
          templatable: 'true',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'InternalPayment',
          imageId: { staticImage: { url: null } }
        },
        {
          id: '12218793772',
          ufsId: null,
          state: 'FINANCIAL',
          date: '08.02.2019T18:45:27',
          from: '2202 20** **** 1290',
          to: 'Сбербанк Онлайн',
          description: 'Входящий перевод',
          operationAmount: { amount: '33000.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardTransferIn',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/6f904da7-1663-4e68-801f-fe288c3283f6.png' } }
        },
        {
          id: '12219040731',
          ufsId: null,
          state: 'FINANCIAL',
          date: '08.02.2019T15:49:52',
          from: 'Visa Classic 4276 49** **** 2340',
          to: 'Тинькофф Банк',
          description: 'Перевод',
          operationAmount: { amount: '-4000.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardTransferOut',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
        },
        {
          id: '12219040704',
          ufsId: null,
          state: 'FINANCIAL',
          date: '08.02.2019T15:49:24',
          from: 'Visa Classic 4276 49** **** 2340',
          to: 'Тинькофф Банк',
          description: 'Перевод',
          operationAmount: { amount: '-30000.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardTransferOut',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
        },
        {
          id: '12199610025',
          ufsId: null,
          state: 'FINANCIAL',
          date: '08.02.2019T08:46:56',
          to: 'Зачисление',
          description: 'Прочие поступления',
          operationAmount: { amount: '44676.17', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardOtherIn',
          imageId: { staticImage: { url: null } }
        },
        {
          id: '12202740545',
          ufsId: null,
          state: 'FINANCIAL',
          date: '08.02.2019T08:05:32',
          from: 'Visa Classic 4276 49** **** 2340',
          to: 'Тинькофф Банк',
          description: 'Перевод',
          operationAmount: { amount: '-30000.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardTransferOut',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
        },
        {
          id: '12244584823',
          ufsId: null,
          state: 'FINANCIAL',
          date: '08.02.2019T00:00:00',
          from: 'Visa Classic 4276 49** **** 2340',
          to: 'OZON.ru',
          description: 'Оплата товаров и услуг',
          operationAmount: { amount: '-2554.45', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardPayment',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/dbcf613f-9b21-4e1b-9d9a-bfc84f00741d.png' } }
        },
        {
          id: '12140627398',
          ufsId: null,
          state: 'FINANCIAL',
          date: '05.02.2019T17:38:16',
          from: 'Visa Classic 4276 49** **** 2340',
          to: 'Тинькофф Банк',
          description: 'Перевод',
          operationAmount: { amount: '-2000.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardTransferOut',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
        },
        {
          id: '12140627379',
          ufsId: null,
          state: 'FINANCIAL',
          date: '05.02.2019T17:36:04',
          from: '5213 24** **** 1737',
          to: 'Тинькофф Банк',
          description: 'Входящий перевод',
          operationAmount: { amount: '500.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardTransferIn',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
        },
        {
          id: '12140627351',
          ufsId: null,
          state: 'FINANCIAL',
          date: '05.02.2019T17:35:45',
          from: '5213 24** **** 1737',
          to: 'Тинькофф Банк',
          description: 'Входящий перевод',
          operationAmount: { amount: '4000.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardTransferIn',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
        },
        {
          id: '12067071492',
          ufsId: null,
          state: 'FINANCIAL',
          date: '03.02.2019T15:55:06',
          from: '4276 49** **** 1102',
          to: 'Сбербанк Онлайн',
          description: 'Входящий перевод',
          operationAmount: { amount: '1000.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardTransferIn',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/6f904da7-1663-4e68-801f-fe288c3283f6.png' } }
        },
        {
          id: '12067784460',
          ufsId: null,
          state: 'FINANCIAL',
          date: '03.02.2019T13:26:36',
          from: 'Visa Classic 4276 49** **** 2340',
          to: 'Тинькофф Банк',
          description: 'Перевод',
          operationAmount: { amount: '-1000.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardTransferOut',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/11ffac45-05f8-4dbd-b7e0-983ffda0bb72.png' } }
        }
      ]
    })
  })

  it('matches transactions with opposite sums', () => {
    expect(adjustTransactionsAndCheckBalance([
      {
        date: '15.02.2019T12:02:31',
        sum: { amount: '+11324.90', currency: { code: 'RUB', name: 'руб.' } },
        description: 'CH Payment RUS MOSCOW IDT:0614 2 RUS MOSCOW AUTOPLATEZH_P2P'
      },
      {
        date: '10.02.2019T05:51:39',
        sum: { amount: '-284.00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'Retail RUS MOSCOW Retail RUS MOSCOW UBER'
      }
    ], [
      {
        id: '12401471400',
        ufsId: null,
        state: 'FINANCIAL',
        date: '15.02.2019T12:02:31',
        from: 'MasterCard Mass 5469 55** **** 2222',
        to: 'Сбербанк',
        description: 'Перевод',
        operationAmount: { amount: '-11324.90', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardTransferOut',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/6f904da7-1663-4e68-801f-fe288c3283f6.png' } }
      },
      {
        id: '12247983163',
        ufsId: null,
        state: 'FINANCIAL',
        date: '09.02.2019T05:51:29',
        from: 'Visa Gold 4279 01** **** 3333',
        to: 'UBER',
        description: 'Оплата товаров и услуг',
        operationAmount: { amount: '-284.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardPayment',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/0429659f-04eb-4949-83b0-0915490b430e.png' } }
      }
    ])).toEqual({
      isBalanceAmbiguous: false,
      transactions: [
        {
          id: '12401471400',
          ufsId: null,
          state: 'FINANCIAL',
          date: '15.02.2019T12:02:31',
          from: 'MasterCard Mass 5469 55** **** 2222',
          to: 'Сбербанк',
          description: 'Перевод',
          operationAmount: { amount: '-11324.90', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardTransferOut',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/6f904da7-1663-4e68-801f-fe288c3283f6.png' } }
        },
        {
          id: '12247983163',
          ufsId: null,
          state: 'FINANCIAL',
          date: '09.02.2019T05:51:29',
          from: 'Visa Gold 4279 01** **** 3333',
          to: 'UBER',
          description: 'Оплата товаров и услуг',
          operationAmount: { amount: '-284.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardPayment',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/0429659f-04eb-4949-83b0-0915490b430e.png' } }
        }
      ]
    })
  })

  it('matches transactions with strange 1 day date difference', () => {
    expect(adjustTransactionsAndCheckBalance([
      {
        date: '10.03.2019T12:19:46',
        sum: { amount: '-141.00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'Retail RUS MOSCOW Retail RUS MOSCOW YANDEX.TAXI'
      },
      {
        date: '10.03.2019T11:52:47',
        sum: { amount: '-141.00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'Retail RUS MOSCOW Retail RUS MOSCOW YANDEX.TAXI'
      },
      {
        date: '17.02.2019T14:48:16',
        sum: { amount: '-105.00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'Retail RUS MOSCOW Retail RUS MOSCOW YANDEX.TAXI'
      },
      {
        date: '15.02.2019T05:51:39',
        sum: { amount: '-284.00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'Retail RUS MOSCOW Retail RUS MOSCOW UBER'
      },
      {
        date: '12.02.2019T21:02:52',
        sum: { amount: '-311.00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'Retail RUS MOSCOW Retail RUS MOSCOW UBER'
      },
      {
        date: '10.02.2019T00:00:00',
        sum: { amount: '-125.00', currency: { code: 'RUB', name: 'руб.' } },
        description: 'Retail RUS BELKACAR.RU   Retail RUS BELKACAR.RU BELKACAR'
      },
      {
        date: '02.02.2019T12:10:03',
        sum: { amount: '-280.80', currency: { code: 'RUB', name: 'руб.' } },
        description: 'Retail RUS RYAZAN Retail RUS RYAZAN IP NIKOLAEVA E.A.'
      }
    ], [
      {
        id: '13147844117',
        ufsId: null,
        state: 'FINANCIAL',
        date: '09.03.2019T12:19:35',
        from: 'Momentum 4817 76** **** 0909',
        to: 'Яндекс.Такси',
        description: 'Оплата товаров и услуг',
        operationAmount: { amount: '-141.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardPayment',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/e61c6173-df6b-462d-af2d-c872fd2b86dc.png' } }
      },
      {
        id: '13147268487',
        ufsId: null,
        state: 'FINANCIAL',
        date: '09.03.2019T11:52:34',
        from: 'Momentum 4817 76** **** 0909',
        to: 'Яндекс.Такси',
        description: 'Оплата товаров и услуг',
        operationAmount: { amount: '-141.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardPayment',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/e61c6173-df6b-462d-af2d-c872fd2b86dc.png' } }
      },
      {
        id: '12443909234',
        ufsId: null,
        state: 'FINANCIAL',
        date: '16.02.2019T14:48:06',
        from: 'MasterCard Gold 5484 40** **** 2222',
        to: 'Яндекс.Такси',
        description: 'Оплата товаров и услуг',
        operationAmount: { amount: '-105.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardPayment',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/e61c6173-df6b-462d-af2d-c872fd2b86dc.png' } }
      },
      {
        id: '12247983163',
        ufsId: null,
        state: 'FINANCIAL',
        date: '14.02.2019T05:51:29',
        from: 'Visa Gold 4279 01** **** 3333',
        to: 'UBER',
        description: 'Оплата товаров и услуг',
        operationAmount: { amount: '-284.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardPayment',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/0429659f-04eb-4949-83b0-0915490b430e.png' } }
      },
      {
        id: '12161617364',
        ufsId: null,
        state: 'FINANCIAL',
        date: '11.02.2019T21:02:08',
        from: 'Visa Gold 4279 01** **** 3333',
        to: 'UBER',
        description: 'Оплата товаров и услуг',
        operationAmount: { amount: '-311.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardPayment',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/0429659f-04eb-4949-83b0-0915490b430e.png' } }
      },
      {
        id: '12161617350',
        ufsId: null,
        state: 'FINANCIAL',
        date: '08.02.2019T15:47:40',
        from: 'Visa Gold 4279 01** **** 3333',
        to: 'BelkaCar',
        description: 'Оплата товаров и услуг',
        operationAmount: { amount: '-125.00', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardPayment',
        imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/cb73d159-a8d0-4d3c-be31-0d9461a48270.png' } }
      },
      {
        id: '12434269174',
        ufsId: null,
        state: 'FINANCIAL',
        date: '02.02.2019T12:10:03',
        from: 'MasterCard Gold 5484 40** **** 2222',
        to: 'IP NIKOLAEVA E.A.',
        description: 'Оплата товаров и услуг',
        operationAmount: { amount: '-280.80', currency: { code: 'RUB', name: 'руб.' } },
        isMobilePayment: 'false',
        copyable: 'false',
        templatable: 'false',
        autopayable: 'false',
        type: 'payment',
        invoiceSubscriptionSupported: 'false',
        invoiceReminderSupported: 'false',
        form: 'ExtCardPayment',
        imageId: { staticImage: { url: null } }
      }
    ])).toEqual({
      isBalanceAmbiguous: false,
      transactions: [
        {
          id: '13147844117',
          ufsId: null,
          state: 'FINANCIAL',
          date: '09.03.2019T12:19:35',
          from: 'Momentum 4817 76** **** 0909',
          to: 'Яндекс.Такси',
          description: 'Оплата товаров и услуг',
          operationAmount: { amount: '-141.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardPayment',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/e61c6173-df6b-462d-af2d-c872fd2b86dc.png' } }
        },
        {
          id: '13147268487',
          ufsId: null,
          state: 'FINANCIAL',
          date: '09.03.2019T11:52:34',
          from: 'Momentum 4817 76** **** 0909',
          to: 'Яндекс.Такси',
          description: 'Оплата товаров и услуг',
          operationAmount: { amount: '-141.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardPayment',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/e61c6173-df6b-462d-af2d-c872fd2b86dc.png' } }
        },
        {
          id: '12443909234',
          ufsId: null,
          state: 'FINANCIAL',
          date: '16.02.2019T14:48:06',
          from: 'MasterCard Gold 5484 40** **** 2222',
          to: 'Яндекс.Такси',
          description: 'Оплата товаров и услуг',
          operationAmount: { amount: '-105.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardPayment',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/e61c6173-df6b-462d-af2d-c872fd2b86dc.png' } }
        },
        {
          id: '12247983163',
          ufsId: null,
          state: 'FINANCIAL',
          date: '14.02.2019T05:51:29',
          from: 'Visa Gold 4279 01** **** 3333',
          to: 'UBER',
          description: 'Оплата товаров и услуг',
          operationAmount: { amount: '-284.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardPayment',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/0429659f-04eb-4949-83b0-0915490b430e.png' } }
        },
        {
          id: '12161617364',
          ufsId: null,
          state: 'FINANCIAL',
          date: '11.02.2019T21:02:08',
          from: 'Visa Gold 4279 01** **** 3333',
          to: 'UBER',
          description: 'Оплата товаров и услуг',
          operationAmount: { amount: '-311.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardPayment',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/0429659f-04eb-4949-83b0-0915490b430e.png' } }
        },
        {
          id: '12161617350',
          ufsId: null,
          state: 'FINANCIAL',
          date: '08.02.2019T15:47:40',
          from: 'Visa Gold 4279 01** **** 3333',
          to: 'BelkaCar',
          description: 'Оплата товаров и услуг',
          operationAmount: { amount: '-125.00', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardPayment',
          imageId: { staticImage: { url: 'https://pfm-stat.online.sberbank.ru/PFM/logos/cb73d159-a8d0-4d3c-be31-0d9461a48270.png' } }
        },
        {
          id: '12434269174',
          ufsId: null,
          state: 'FINANCIAL',
          date: '02.02.2019T12:10:03',
          from: 'MasterCard Gold 5484 40** **** 2222',
          to: 'IP NIKOLAEVA E.A.',
          description: 'Оплата товаров и услуг',
          operationAmount: { amount: '-280.80', currency: { code: 'RUB', name: 'руб.' } },
          isMobilePayment: 'false',
          copyable: 'false',
          templatable: 'false',
          autopayable: 'false',
          type: 'payment',
          invoiceSubscriptionSupported: 'false',
          invoiceReminderSupported: 'false',
          form: 'ExtCardPayment',
          imageId: { staticImage: { url: null } }
        }
      ]
    })
  })
})
